Repository infiniflow/ragflow, pull requests merged in 2024-12, with the labels that each got.

#3780 Update file parsing progress info
  rag/svr/task_executor.py
Labels: ci

#3781 Refactor parse progress
  rag/app/naive.py
  rag/svr/task_executor.py
Labels: ci

#3770 add jina new models in jina connector
  conf/llm_factories.json
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
Labels: ci

#3786 Fix out of boundary.
  api/apps/sdk/session.py
  deepdoc/parser/pdf_parser.py
Labels: ci

#3784 Fix the bug that prevented modifying `dataset_ids`
  api/apps/sdk/chat.py
Labels: ci

#3792 Detect invalid response from api.siliconflow.cn
  rag/llm/embedding_model.py
Labels: ci

#3802 More dataset test cases
  api/apps/kb_app.py
  api/utils/api_utils.py
  sdk/python/test/test_frontend_api/test_dataset.py
Labels: ci

#3808 [DOC] We have no plan to maintain Docker images for ARM. Please build your …
  docs/guides/develop/build_docker_image.mdx
  docs/quickstart.mdx
Labels: documentation

#3795 Fix the bug that the agent could not find the context
  api/apps/sdk/session.py
  api/db/db_models.py
Labels: ci

#3812 Web API test cases
  sdk/python/test/test_frontend_api/common.py
  sdk/python/test/test_frontend_api/test_chunk.py
Labels: ci

#3821 Fix @ in model name issue.
  api/db/services/dialog_service.py
  api/db/services/llm_service.py
Labels: ci

#3809 Add pagerank to KB.
  api/apps/chunk_app.py
  api/apps/kb_app.py
  api/db/db_models.py
  api/db/services/knowledgebase_service.py
  api/db/services/llm_service.py
  api/db/services/task_service.py
  conf/infinity_mapping.json
  rag/nlp/search.py
  rag/svr/task_executor.py
  rag/utils/es_conn.py
  sdk/python/ragflow_sdk/modules/dataset.py
Labels: ci

#3823 Fix the agent reference bug and the session prologue
  api/apps/sdk/session.py
Labels: ci

#3825 Refactor embedding batch_size
  api/db/services/llm_service.py
  rag/benchmark.py
  rag/llm/embedding_model.py
Labels: ci

#3829 Fix parsing JSON file error
  deepdoc/parser/json_parser.py
  rag/app/naive.py
Labels: ci

#3835 Add api for list agents and agent seesions
  api/apps/canvas_app.py
  api/apps/sdk/agent.py
  api/apps/sdk/chat.py
  api/apps/sdk/session.py
  api/db/services/api_service.py
  api/db/services/canvas_service.py
Labels: ci

#3838 Change default error message to English
  rag/llm/chat_model.py
  rag/nlp/__init__.py
Labels: ci

#3837 Email sending tool
  agent/component/__init__.py
  agent/component/email.py
  web/src/assets/svg/email.svg
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/flow/canvas/index.tsx
  web/src/pages/flow/canvas/node/email-node.tsx
  web/src/pages/flow/canvas/node/index.less
  web/src/pages/flow/constant.tsx
  web/src/pages/flow/flow-drawer/index.tsx
  web/src/pages/flow/form/email-form/index.tsx
  web/src/pages/flow/hooks.tsx
Labels: ci

#3652 Web: Fixed the download and preview file not authorized.
  api/apps/file_app.py
  web/package.json
  web/src/components/ui/navigation-menu.tsx
  web/src/hooks/file-manager-hooks.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/pages/add-knowledge/components/knowledge-file/parsing-action-cell/index.tsx
  web/src/pages/document-viewer/hooks.ts
  web/src/pages/document-viewer/pdf/index.tsx
  web/src/pages/file-manager/action-cell/index.tsx
  web/src/pages/knowledge/knowledge-card/index.less
  web/src/pages/user-setting/setting-model/Tencent-modal/index.tsx
  web/src/pages/user-setting/setting-model/azure-openai-modal/index.tsx
  web/src/pages/user-setting/setting-model/bedrock-modal/index.tsx
  web/src/pages/user-setting/setting-model/fish-audio-modal/index.tsx
  web/src/pages/user-setting/setting-model/google-modal/index.tsx
  web/src/pages/user-setting/setting-model/hunyuan-modal/index.tsx
  web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
  web/src/pages/user-setting/setting-model/spark-modal/index.tsx
  web/src/pages/user-setting/setting-model/volcengine-modal/index.tsx
  web/src/pages/user-setting/setting-model/yiyan-modal/index.tsx
  web/src/services/file-manager-service.ts
  web/src/utils/file-util.ts
Labels: ci

#3848 Add sdk for list agents and sessions
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/agent.py
  sdk/python/ragflow_sdk/modules/session.py
  sdk/python/ragflow_sdk/ragflow.py
  sdk/python/test/test_sdk_api/t_agent.py
  sdk/python/test/test_sdk_api/t_dataset.py
  sdk/python/test/test_sdk_api/t_session.py
Labels: ci

#3855 Refine synonym query.
  conf/mapping.json
  rag/nlp/query.py
Labels: ci

#3866 Fix open AI compatible rerank issue.
  api/apps/sdk/session.py
  rag/llm/rerank_model.py
Labels: ci

#3867 Fix chunk position issue.
  api/apps/chunk_app.py
Labels: ci

#3870 Fix HuggingFace model error.
  rag/llm/chat_model.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
Labels: ci

#3875 Feat: Add question parameter to edit chunk modal
  api/apps/chunk_app.py
  api/apps/sdk/doc.py
  conf/infinity_mapping.json
  rag/nlp/query.py
  rag/nlp/search.py
  rag/svr/task_executor.py
  sdk/python/ragflow_sdk/modules/chunk.py
  sdk/python/ragflow_sdk/modules/document.py
Labels: ci

#3877 Fix chunk available issue
  api/apps/chunk_app.py
Labels: ci

#3882 Add a dependency blincker.
  poetry.lock
  pyproject.toml
Labels: ci

#3887 Fix typos
  agent/templates/DB Assistant.json
  agent/templates/customer_service.json
  agent/templates/general_chat_bot.json
  agent/templates/interpreter.json
  agent/templates/medical_consultation.json
  agent/templates/seo_blog.json
  agent/templates/text2sql.json
  agent/templates/websearch_assistant.json
Labels: ci

#3891 release with CI
  .github/workflows/release.yml
  .github/workflows/tests.yml
  Dockerfile
  Dockerfile.deps
  Dockerfile.slim
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  api/versions.py
  docker/.env
  docs/guides/develop/build_docker_image.mdx
  download_deps.py
  ubuntu.sources
Labels: wip, ci

#3902 Fix: Fixed the issue that the agent list page failed to load #3827
  agent/canvas.py
  api/db/services/llm_service.py
Labels: ci

#3908 Remove vector stored in component output.
  agent/component/base.py
Labels: ci

#3907 Introduced NEED_MIRROR
  .github/workflows/tests.yml
  Dockerfile
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  docs/guides/develop/launch_ragflow_from_source.md
Labels: ci

#3911 Refactor UI text
  agent/component/generate.py
  api/apps/dialog_app.py
  api/db/services/dialog_service.py
  docs/guides/deploy_local_llm.mdx
  docs/guides/llm_api_key_setup.md
  docs/guides/start_chat.md
  docs/quickstart.mdx
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
Labels: ci

#3913 Update oc9 docker compose file
  docker/docker-compose-CN-oc9.yml
  docker/docker-compose-gpu-CN-oc9.yml
Labels: ci

#3921 Added static check at PR CI
  .github/workflows/tests.yml
  api/apps/api_app.py
  api/apps/canvas_app.py
  api/apps/chunk_app.py
  api/apps/conversation_app.py
  api/apps/dialog_app.py
  api/apps/document_app.py
  api/apps/file2document_app.py
  api/apps/file_app.py
  api/apps/kb_app.py
  api/apps/llm_app.py
  api/apps/sdk/agent.py
  api/apps/sdk/chat.py
  api/apps/sdk/dataset.py
  api/apps/sdk/dify_retrieval.py
  api/apps/sdk/doc.py
  api/apps/sdk/session.py
  api/apps/system_app.py
  api/apps/tenant_app.py
  api/apps/user_app.py
  deepdoc/parser/pdf_parser.py
  deepdoc/vision/ocr.py
  deepdoc/vision/recognizer.py
  graphrag/entity_embedding.py
Labels: ci

#3929 Add support to iframe chatbot
  agent/canvas.py
  agent/component/base.py
  agent/component/begin.py
  agent/templates/customer_service.json
  api/apps/conversation_app.py
  api/apps/sdk/session.py
  api/apps/system_app.py
  api/db/db_models.py
  api/db/services/canvas_service.py
  api/db/services/conversation_service.py
  api/db/services/dialog_service.py
  api/db/services/document_service.py
Labels: ci

#3931 Fix field missing issue.
  rag/svr/task_executor.py
Labels: ci

#3933 Fixed tmp in Dockerfile
  Dockerfile
  Dockerfile.deps
Labels: ci

#3934 Fix transformers dependencies for slim.
  rag/llm/cv_model.py
Labels: ci

#3936 Fix error message for image access.
  api/apps/document_app.py
  api/db/services/canvas_service.py
  api/db/services/conversation_service.py
Labels: ci

#3939 Fix session API issues.
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  api/db/services/conversation_service.py
Labels: ci

#3941 api http return error
  api/db/services/conversation_service.py
Labels: ci

#3925 organize chunks by document in the prompt
  api/db/services/dialog_service.py
Labels: ci

#3946 Fixed log not displaying
  .github/workflows/tests.yml
  api/ragflow_server.py
  api/utils/log_utils.py
  rag/nlp/__init__.py
  rag/svr/task_executor.py
Labels: ci

#3954 Case insensitive when set doc engine
  api/settings.py
Labels: ci

#3940 Rename page_num_list, top_list, position_list
  Dockerfile
  api/apps/chunk_app.py
  api/apps/sdk/doc.py
  conf/infinity_mapping.json
  graphrag/search.py
  rag/app/presentation.py
  rag/nlp/__init__.py
  rag/nlp/search.py
  rag/svr/task_executor.py
  rag/utils/es_conn.py
  rag/utils/infinity_conn.py
Labels: ci

#3961 Support iframe chatbot.
  agent/canvas.py
  agent/component/base.py
  agent/component/generate.py
  api/apps/canvas_app.py
  api/apps/conversation_app.py
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  api/db/services/conversation_service.py
  api/db/services/dialog_service.py
Labels: ci

#3966 Fixed retrieval TypeError: unhashable type: 'list'
  rag/utils/infinity_conn.py
Labels: ci

#3967 Add back beartype
  agent/__init__.py
  api/__init__.py
  deepdoc/__init__.py
  intergrations/chatgpt-on-wechat/plugins/__init__.py
  rag/__init__.py
  sdk/python/ragflow_sdk/__init__.py
Labels: ci

#3982 Fix exec sql exception issue.
  agent/canvas.py
  agent/component/exesql.py
Labels: ci

#3994 Support debug components.
  agent/canvas.py
  agent/component/base.py
  agent/component/begin.py
  agent/component/generate.py
  api/apps/canvas_app.py
  api/apps/conversation_app.py
  api/apps/document_app.py
  rag/svr/task_executor.py
Labels: ci

#3995 UI updates + RAGFlow image description
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  docs/guides/agentic_rag/general_purpose_chatbot.md
  docs/quickstart.mdx
  docs/references/http_api_reference.md
  docs/release_notes.md
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
Labels: ci

#3983 Try to reuse existing chunks
  api/apps/document_app.py
  api/db/db_models.py
  api/db/services/document_service.py
  api/db/services/task_service.py
  poetry.lock
  pyproject.toml
  rag/svr/task_executor.py
Labels: ci

#4009 Replaced md5 with xxhash64 for chunk id
  api/apps/chunk_app.py
  api/apps/sdk/doc.py
  api/db/services/document_service.py
  api/db/services/task_service.py
  rag/svr/task_executor.py
Labels: ci

#3999 Fix: Completion AttributeError: 'list' object has no attribute 'get'
  api/apps/conversation_app.py
Labels: ci

#3985 Add mssql support
  Dockerfile
  agent/component/exesql.py
  api/apps/canvas_app.py
  poetry.lock
  pyproject.toml
  web/src/locales/config.ts
  web/src/locales/en.ts
  web/src/locales/vi.ts
  web/src/pages/flow/constant.tsx
  web/src/pages/user-setting/setting-locale/index.tsx
Labels: ci

#4004 Fix json file parse
  deepdoc/parser/json_parser.py
Labels: ci

#4012 Component debugging funcionality.
  agent/component/categorize.py
  agent/component/generate.py
  agent/component/keyword.py
  agent/component/relevant.py
  agent/component/rewrite.py
Labels: ci

#4006 Fix bug in hierarchical_merge function
  rag/nlp/__init__.py
Labels: ci

#3996 Fix bugs in agent api and update api document
  agent/canvas.py
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  api/db/services/conversation_service.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/agent.py
  sdk/python/ragflow_sdk/modules/session.py
  sdk/python/test/test_sdk_api/t_agent.py
Labels: ci

#3858 Migrate infinity at startup
  conf/infinity_mapping.json
  docker/docker-compose-base.yml
  poetry.lock
  pyproject.toml
  rag/utils/infinity_conn.py
  sdk/python/ragflow_sdk/modules/agent.py
Labels: ci

#4007 Feat: Supports to debug single component in Agent. #3993
  web/src/hooks/flow-hooks.ts
  web/src/interfaces/request/flow.ts
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/flow/canvas/index.tsx
  web/src/pages/flow/canvas/node/node-header.tsx
  web/src/pages/flow/constant.tsx
  web/src/pages/flow/debug-content/index.less
  web/src/pages/flow/debug-content/index.tsx
  web/src/pages/flow/debug-content/popover-form.tsx
  web/src/pages/flow/flow-drawer/index.less
  web/src/pages/flow/flow-drawer/index.tsx
  web/src/pages/flow/flow-drawer/single-debug-drawer/index.tsx
  web/src/pages/flow/flow-tooltip.tsx
  web/src/pages/flow/form/invoke-form/index.tsx
  web/src/pages/flow/hooks.tsx
  web/src/pages/flow/run-drawer/index.tsx
  web/src/pages/flow/utils.ts
  web/src/pages/login/index.tsx
  web/src/services/flow-service.ts
  web/src/utils/api.ts
  web/src/utils/request.ts
Labels: ci

#4021 Feat: Reparse a file shall reuse existing chunks if possible #3793
  web/src/hooks/document-hooks.ts
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
  web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
Labels: ci

#4025 Set task progress on exception
  rag/svr/task_executor.py
Labels: ci

#4026 Fix xinfo_groups returns unexpected result
  rag/svr/task_executor.py
Labels: ci

#4028 Fix connection error for adding visual llm.
  api/apps/llm_app.py
Labels: ci

#4027 extraction sqlquery
  agent/component/exesql.py
Labels: ci

#4037 Remove Redundant None Check for vector_similarity_weight
  api/apps/dialog_app.py
Labels: ci

#4043 Fix chunk number error after re-parsing.
  api/apps/document_app.py
  api/db/services/task_service.py
Labels: ci

#4051 Cache the result from llm for graphrag and raptor
  api/db/services/task_service.py
  graphrag/__init__.py
  graphrag/claim_extractor.py
  graphrag/community_reports_extractor.py
  graphrag/description_summary.py
  graphrag/entity_resolution.py
  graphrag/extractor.py
  graphrag/graph_extractor.py
  graphrag/mind_map_extractor.py
  graphrag/utils.py
  rag/raptor.py
  rag/svr/task_executor.py
Labels: ci

#4054 Upgrades Document Layout Analysis model.
  api/db/services/task_service.py
  conf/infinity_mapping.json
  deepdoc/vision/__init__.py
  deepdoc/vision/layout_recognizer.py
  deepdoc/vision/operators.py
Labels: ci

#4055 Compatible with former API keys.
  api/apps/system_app.py
Labels: ci

#4063 Fix raptor resuable issue.
  api/db/services/document_service.py
  api/db/services/task_service.py
  graphrag/utils.py
Labels: ci

#4059 Added pagerank support to infinity
  api/apps/kb_app.py
  rag/utils/infinity_conn.py
Labels: ci

#4061 Fix rerank_model bug in chat and markdown bug
  api/apps/sdk/chat.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  rag/app/naive.py
Labels: ci

#4068 Fix position lost issue.
  rag/nlp/search.py
Labels: ci

#4049 Add Architecture-Specific Logic for msodbcsql in Dockerfile #4036
  Dockerfile
Labels: ci

#4078 Fix conversation bug in agent session
  poetry.lock
  pyproject.toml
  sdk/python/ragflow_sdk/modules/session.py
Labels: ci

#4080 Fix arm doc
  docs/guides/develop/build_docker_image.mdx
Labels: ci

#4081 Fix abnormal user invitaion message.
  api/apps/tenant_app.py
Labels: ci

#4083 Refactor trie load and construct
  rag/nlp/rag_tokenizer.py
Labels: ci

#4084 Add huqie trie to docker image.
  Dockerfile
  download_deps.py
Labels: ci

#4085 Update team invite message
  api/apps/tenant_app.py
Labels: ci

#4088 Bump infinity to 0.5.0
  docker/docker-compose-base.yml
  helm/values.yaml
  poetry.lock
  pyproject.toml
Labels: ci

#4089 Fix raptor
  api/db/services/document_service.py
  api/db/services/task_service.py
Labels: ci

#4077 Prepare docs for v0.15.0 release
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/guides/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/references/faq.md
  helm/values.yaml
  poetry.lock
  sdk/python/poetry.lock
  sdk/python/pyproject.toml
Labels: ci

#4110 Fixed infinity exception SCORE() / SCORE_FACTORS() requires Fusion or MATCH TEXT or MATCH TENSOR
  rag/utils/infinity_conn.py
Labels: ci

#4117 Fix fastembed reloading issue.
  rag/llm/embedding_model.py
Labels: ci

#4119 Add parameters for ask_chat and fix bugs in list_sessions
  api/apps/sdk/session.py
  sdk/python/ragflow_sdk/modules/session.py
Labels: ci

#4121 Make fast embed and default embed mutually exclusive.
  rag/llm/embedding_model.py
Labels: ci

#4123 fix chunk method "Table" losing content when the Excel file has multi…
  deepdoc/parser/excel_parser.py
  rag/app/table.py
Labels: ci

#4115 add gemini 2.0
  conf/llm_factories.json
Labels: ci

#4116 Refactor ask decorator
  api/db/services/dialog_service.py
  api/db/services/llm_service.py
Labels: ci

#4129 Mask password in log
  api/utils/__init__.py
Labels: ci

#4140 Fix redis get error.
  graphrag/utils.py
Labels: ci

#4144 Fix position_int on infinity
  docker/.env
  rag/utils/infinity_conn.py
Labels: ci

#4131 Update the component of the agent API with parameters.
  api/apps/sdk/chat.py
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  api/utils/api_utils.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/agent.py
  sdk/python/ragflow_sdk/modules/session.py
Labels: ci

#4153 Validate returned chunk at list_chunks and add_chunk
  api/apps/sdk/doc.py
  rag/utils/infinity_conn.py
Labels: ci

#4171 Fix Voyage re-rank model. Limit file name length.
  api/db/services/file_service.py
  rag/llm/rerank_model.py
Labels: ci

#4167 Use s3 configuration from settings module
  rag/utils/s3_conn.py
Labels: ci

#4156 Fix bug over chunks classification by document in the promp
  api/db/services/dialog_service.py
Labels: ci

#4174 Add Llama3.3
  conf/llm_factories.json
  deepdoc/vision/recognizer.py
  rag/utils/s3_conn.py
Labels: ci

#4177 Fetch chunk by batches.
  rag/nlp/search.py
  rag/utils/es_conn.py
Labels: ci

#4178 Fix 'SCORE' not found bug
  api/db/services/dialog_service.py
  api/db/services/task_service.py
  rag/utils/infinity_conn.py
Labels: ci

#4184 Fix error of changing embedding model
  rag/llm/embedding_model.py
Labels: ci

#4187 Fix duplicated communitiy
  graphrag/leiden.py
Labels: ci

#4185 Added time to progress message
  api/db/services/task_service.py
  rag/svr/task_executor.py
Labels: ci

#4192 Fix raptor bug.
  rag/nlp/search.py
Labels: ci

#4194 Fix score() issue
  rag/utils/infinity_conn.py
Labels: ci

#4193 Update progress time info
  api/db/services/task_service.py
  rag/svr/task_executor.py
Labels: ci

#4202 Catch the exception while parsing pptx.
  deepdoc/parser/ppt_parser.py
Labels: ci

#4203 fix: stop rerank by model when search result is empty
  rag/nlp/search.py
Labels: ci

#4207 Bump infinity to 0.5.2
  docker/docker-compose-base.yml
  poetry.lock
  pyproject.toml
  rag/utils/infinity_conn.py
Labels: ci

#4206 Add user_id for third-party system to record sessions.
  api/apps/sdk/session.py
  api/db/db_models.py
  api/db/services/api_service.py
  api/db/services/conversation_service.py
  docs/references/http_api_reference.md
Labels: ci

#4211 Remove session owner check.
  api/apps/sdk/session.py
Labels: ci

#4212 Fix interface as input variable for component.
  agent/component/base.py
Labels: ci

#4219 Fix misspell.
  api/apps/sdk/session.py
Labels: ci

#4222 Update pyproject.toml to 0.15.1
  pyproject.toml
  sdk/python/pyproject.toml
Labels: ci

#4227 Fix: Q&A chunk modification
  api/apps/chunk_app.py
Labels: ci

#4231 Fix component input error.
  agent/component/base.py
Labels: ci

#4233 Removing invisible chars before tokenization.
  rag/nlp/rag_tokenizer.py
Labels: ci

#4232 Update version info
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/guides/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/references/faq.md
  helm/values.yaml
Labels: ci

#4237 Fixed invoke component parameters #4236
  agent/component/invoke.py
Labels: ci

#4241 Fix bugs
  api/apps/api_app.py
  api/apps/canvas_app.py
  api/apps/conversation_app.py
  api/apps/sdk/session.py
  api/utils/api_utils.py
  rag/utils/infinity_conn.py
Labels: ci

#4244 Fix text
  web/src/locales/en.ts
Labels: ci

#4250 Replace image2text model check with internal image.
  api/apps/llm_app.py
  api/utils/api_utils.py
Labels: ci

#4248 Update UI text
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  web/src/locales/en.ts
Labels: ci

#4258 Add iteration for agent.
  agent/canvas.py
  agent/component/__init__.py
  agent/component/baidu.py
  agent/component/base.py
  agent/component/iteration.py
  agent/component/iterationitem.py
  api/db/services/api_service.py
Labels: ci

#4259 Clean query.
  agent/component/__init__.py
  rag/nlp/query.py
Labels: ci

#4270 Fix chat listing error.
  api/apps/sdk/chat.py
Labels: ci

#4280 Fix some bugs in text2sql.(#4279)(#4281)
  agent/component/exesql.py
  rag/app/qa.py
Labels: ci

#4275 Fix BaiduFanyi TestRun parameter validation and debug method missing …
  agent/component/baidufanyi.py
Labels: ci

#4285 Fix agent session list by user_id.
  api/apps/sdk/session.py
Labels: ci

#4284 Fix the bug in create_dataset function
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/ragflow.py
Labels: ci

#4292 Fix: After executing npm i --force locally, the login page cannot be opened #4290
  Dockerfile
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_zh.md
  docs/guides/develop/launch_ragflow_from_source.md
  web/package-lock.json
  web/package.json
Labels: ci

#4291 Code refactor.
  agent/component/answer.py
  api/apps/canvas_app.py
  api/apps/dialog_app.py
  api/apps/kb_app.py
  api/utils/api_utils.py
  graphrag/graph_prompt.py
  graphrag/utils.py
  rag/app/laws.py
  rag/app/manual.py
  rag/app/table.py
Labels: ci

#4293 Fix bugs in chunk api
  api/apps/chunk_app.py
  api/apps/sdk/doc.py
  docs/references/http_api_reference.md
Labels: ci

#4294 Add top_k for create_chat and update_chat api
  api/apps/sdk/chat.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/chat.py
  sdk/python/ragflow_sdk/ragflow.py
Labels: ci

#4303 Refactor
  agent/component/base.py
  api/apps/__init__.py
  api/apps/conversation_app.py
  api/db/services/document_service.py
  api/utils/api_utils.py
  rag/svr/task_executor.py
Labels: ci

#4299 Update error message for agent name conflict
  api/apps/canvas_app.py
Labels: ci

#4305 Show the errors out.
  rag/raptor.py
  rag/svr/task_executor.py
Labels: ci

#4311 Update displayed_name to display_name
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/dataset.py
  sdk/python/test/test_sdk_api/t_chat.py
  sdk/python/test/test_sdk_api/t_chunk.py
  sdk/python/test/test_sdk_api/t_document.py
  sdk/python/test/test_sdk_api/t_session.py
Labels: ci

#4307 Update exesql component for agent
  agent/component/exesql.py
Labels: ci
