Repository infiniflow/ragflow, pull requests merged in 2025-05, with the labels that each got.

#7446 Feat: Modify the style of the dataset page #3221
  web/src/app.tsx
  web/src/components/icon-font.tsx
  web/src/components/ragflow-avatar.tsx
  web/src/components/ui/switch.tsx
  web/src/components/ui/table.tsx
  web/src/constants/file.ts
  web/src/global.less
  web/src/interfaces/database/knowledge.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/index.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, size:L

#7443 Fix: filed_map was incorrectly persisted
  api/apps/document_app.py
  api/db/services/document_service.py
  api/db/services/knowledgebase_service.py
Labels: 🐞 bug, ci, size:M

#7468 Fix instructions for Ollama
  docs/guides/models/deploy_local_llm.mdx
Labels: 📖 documentation, size:M

#7478 Fix Ollama instructions
  docs/guides/models/deploy_local_llm.mdx
Labels: 📖 documentation, size:S

#7465 Fix:Set CUDA_VISIBLE_DEVICES In DefaultEmbedding
  rag/llm/embedding_model.py
Labels: 🐞 bug, ci, size:XS

#7447 fix(deps): incorrect nltk download dir
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/launch_backend_service.sh
Labels: 🐞 bug, ci, size:S

#7457 fixed errror when vars of cnt begin declare with key contain "begin"
  agent/component/base.py
Labels: 🐞 bug, ci, size:XS

#7392 perf: optimze figure parser
  deepdoc/parser/figure_parser.py
  rag/svr/task_executor.py
Labels: ci, size:M

#7451 refa: Optimize create dataset validation
  api/apps/sdk/dataset.py
  api/settings.py
  api/utils/api_utils.py
  api/utils/validation_utils.py
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
Labels: ci, ☯️ refactor, size:L

#7477 Fix: Sometimes VisionFigureParser.figures may is tuple
  deepdoc/parser/figure_parser.py
Labels: 🐞 bug, ci, size:XS

#7479 Fix: chat solo issue.
  api/db/services/dialog_service.py
Labels: 🐞 bug, ci, size:XS

#7471 Feat: Support knowledge base type input in agent flow debugger
  agent/component/retrieval.py
  web/src/components/knowledge-base-item.tsx
  web/src/pages/flow/constant.tsx
  web/src/pages/flow/debug-content/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#7496 docs: add API key instructions for MCP host mode
  docs/develop/mcp.md
Labels: 📖 documentation, size:S

#6553 Feat: Improve 'user_canvan_version' delete and 'document' delete performance
  api/apps/api_app.py
  api/db/services/common_service.py
  api/db/services/document_service.py
  api/db/services/user_canvas_version.py
Labels: ci, size:M

#7500 Fix:When sharing the knowledge base of multiple tenants with one person, when this person queries the knowledge base of both tenants, they will only query the question of the first person's knowledge base
  api/apps/sdk/doc.py
Labels: ci, size:XS

#7359 Docs: Initial editorial pass to MCP server
  docker/docker-compose.yml
  docs/configurations.md
  docs/develop/acquire_ragflow_api_key.md
  docs/develop/launch_mcp_server.md
  docs/develop/mcp.md
  docs/guides/agent/agent_component_reference/generate.mdx
  docs/guides/dataset/construct_knowledge_graph.md
  docs/guides/team/share_agents.md
  docs/guides/team/share_chat_assistant.md
  docs/guides/team/share_model.md
  docs/references/http_api_reference.md
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, ci, size:L, lgtm

#7514 Docs: minor format updates
  docs/develop/launch_mcp_server.md
Labels: size:XS

#7513 Fix: retrieval component for shared KB issue.
  agent/component/retrieval.py
Labels: 🐞 bug, ci, size:XS

#7507 Docs: correct wrong URL for related_questions HTTP API
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:S

#7521 Feat: Add `/login/channels` route and improve auth logic for frontend third-party login integration
  api/apps/auth/README.md
  api/apps/auth/oauth.py
  api/apps/auth/oidc.py
  api/apps/user_app.py
  conf/service_conf.yaml
  docker/service_conf.yaml.template
Labels: 📖 documentation, 💞 feature, ci, size:M

#7312 fix bug #7309 deepseek-ai/deepseek-vl2 model can not be select as a VL model to parse pdf image
  conf/llm_factories.json
Labels: 🐞 bug, ci, size:M

#7522 Feat: Add API to support get chunk by id
  api/apps/api_app.py
Labels: 💞 feature, ci, size:S

#7525 Refa: text order be robuster.
  deepdoc/parser/pdf_parser.py
Labels: ci, ☯️ refactor, size:S

#7526 Feat: Adjust the operation cell of the table on the file management page and dataset page #3221.
  web/package-lock.json
  web/package.json
  web/public/iconfont.js
  web/src/components/bulk-operate-bar.tsx
  web/src/components/icon-font.tsx
  web/src/components/new-document-link.tsx
  web/src/components/ui/badge.tsx
  web/src/components/ui/table.tsx
  web/src/hooks/logic-hooks/use-row-selection.ts
  web/src/hooks/use-document-request.ts
  web/src/pages/dataset/dataset/dataset-action-cell.tsx
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/index.tsx
  web/src/pages/files/knowledge-cell.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7532 Test: Configure test case priorities to reduce CI execution time
  .github/workflows/tests.yml
  sdk/python/pyproject.toml
  sdk/python/test/test_http_api/conftest.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  sdk/python/test/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
  sdk/python/test/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
  sdk/python/test/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  sdk/python/test/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
Labels: ci, size:L, 🧪 test

#7533 Updated MCP
  docs/develop/launch_mcp_server.md
  docs/release_notes.md
Labels: 📖 documentation, size:S

#7536 Docs: UI updates
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:M

#7541 Error storing tag in Redis
  rag/app/tag.py
Labels: 🐞 bug, ci, size:XS

#7534 Fix:local_es_tag
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7547 Feat: Replace the submit form button with ButtonLoading #3221
  web/src/components/chunk-method-dialog/index.tsx
  web/src/components/file-upload-dialog/index.tsx
  web/src/components/rename-dialog/index.tsx
  web/src/components/ui/button.tsx
  web/src/pages/dataset/dataset/set-meta-dialog.tsx
  web/src/pages/files/link-to-dataset-dialog.tsx
  web/src/pages/files/move-dialog.tsx
Labels: size:M

#7548 CI: add daily test
  .github/workflows/tests.yml
Labels: ci, size:S, 🧪 test

#7546 Feat: KB detail supports document total size
  api/apps/kb_app.py
  api/db/services/document_service.py
Labels: 💞 feature, ci, size:S

#7549 Feat: add document enabled
  api/apps/sdk/doc.py
Labels: 💞 feature, ci, size:S, lgtm

#7551 Fix: empty query issue.
  deepdoc/parser/pdf_parser.py
  rag/nlp/query.py
Labels: 🐞 bug, ci, size:XS

#7554 Feat: Cross-language query #7376 #4503 #5710 #7470
  web/src/components/cross-language-item.tsx
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx
  web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#7560 Refa: remove ollama keep alive.
  rag/llm/chat_model.py
  rag/llm/cv_model.py
Labels: ci, ☯️ refactor, size:S

#7559 Perf: Increase database connection pool size
  api/db/services/common_service.py
  api/db/services/llm_service.py
  conf/service_conf.yaml
  docker/service_conf.yaml.template
Labels: ci, size:L

#7563 Fix: helm template redis
  helm/templates/redis.yaml
  helm/values.yaml
Labels: 🐞 bug, size:XS

#7564 Refa: HTTP API update dataset / test cases / docs
  api/apps/sdk/dataset.py
  api/utils/api_utils.py
  api/utils/validation_utils.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/ragflow.py
  sdk/python/test/libs/utils/hypothesis_utils.py
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/test_dataset_mangement/conftest.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
Labels: 🐞 bug, 📖 documentation, ci, ☯️ refactor, size:XXL, 🧪 test

#7578 Test: skip unstable test cases
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
Labels: ci, size:XS, 🧪 test

#7565 Docs: Restructured MCP-specific documents
  docs/develop/mcp/_category_.json
  docs/develop/mcp/launch_mcp_server.md
  docs/develop/mcp/mcp_client_example.md
  docs/develop/mcp/mcp_tools.md
  docs/guides/dataset/construct_knowledge_graph.md
  docs/release_notes.md
Labels: 📖 documentation, size:M

#7562 feat: Enable antialiasing for PDF image extraction to improve OCR accuracy
  deepdoc/parser/pdf_parser.py
Labels: 💞 feature, ci, size:XS

#7568 docs: add langfuse documentation
  docs/guides/tracing.mdx
Labels: 📖 documentation, size:M

#7574 Set helm resource-policy to be keep
  helm/templates/elasticsearch.yaml
  helm/templates/infinity.yaml
  helm/templates/minio.yaml
  helm/templates/mysql.yaml
  helm/templates/redis.yaml
Labels: 💞 feature, size:S

#7575 Fix:Discrepancy between Document.list_chunks() API documentation and implementation
  api/apps/sdk/doc.py
  sdk/python/ragflow_sdk/modules/document.py
Labels: 🐞 bug, ci, size:S

#7583 Docs:Updated langfuse guide
  docs/develop/mcp/launch_mcp_server.md
  docs/guides/agent/text2sql_agent.md
  docs/guides/tracing.mdx
Labels: 📖 documentation, size:S, lgtm

#7550 Fix: InfiniteScroll sometimes can not fetch next page
  web/src/pages/flow/list/index.tsx
Labels: 🐞 bug, 🧰 typescript, size:M

#7570 Fix: markdown table conversion error
  rag/app/naive.py
Labels: 🐞 bug, size:XS

#7515 Feat: Add http api to create, update, or delete agents.
  api/apps/sdk/agent.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/ragflow.py
Labels: 📖 documentation, 💞 feature, ci, size:L

#7540 Feat: add support for OpenAi gpt 4.1 series
  conf/llm_factories.json
Labels: 💞 feature, ci, size:S

#7589 Fix(api): correct default value handling in dataset parser config
  api/apps/sdk/dataset.py
  api/utils/validation_utils.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
Labels: 🐞 bug, ci, size:L

#7588 Feat: Add FormContainer component #3221
  web/src/components/chunk-method-dialog/dynamic-page-range.tsx
  web/src/components/chunk-method-dialog/index.tsx
  web/src/components/form-container.tsx
  web/src/components/slider-input-form-field.tsx
  web/src/components/ui/dual-range-slider.tsx
  web/src/components/ui/form.tsx
Labels: 💞 feature, size:L

#7590 Docs: Guide on enabling Excel2HTML
  docs/develop/mcp/launch_mcp_server.md
  docs/guides/dataset/enable_excel2html.md
  web/src/locales/de.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:M

#7586 Fix: missing graph resolution and community extraction in graphrag tasks
  graphrag/general/index.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7595 FIX:ZeroDivisionError when using large page_size in client.retrieve()
  api/apps/api_app.py
  rag/nlp/search.py
Labels: 🐞 bug, ci, size:XS

#7609 Feat: Adjust the display position of recall test item images #7608
  web/src/interfaces/database/knowledge.ts
  web/src/pages/add-knowledge/components/knowledge-testing/testing-result/index.less
  web/src/pages/add-knowledge/components/knowledge-testing/testing-result/index.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#7610 Feat: add image preview to retrieval test.
  conf/infinity_mapping.json
  rag/app/manual.py
  rag/app/picture.py
  rag/app/presentation.py
  rag/app/qa.py
  rag/nlp/__init__.py
  rag/nlp/search.py
Labels: 💞 feature, ci, size:S

#7614 Docs: Restructured docs
  docs/develop/mcp/launch_mcp_server.md
  docs/guides/chat/best_practices/_category_.json
  docs/guides/chat/best_practices/accelerate_question_answering.mdx
  docs/guides/dataset/best_practices/_category_.json
  docs/guides/dataset/best_practices/accelerate_doc_indexing.mdx
  docs/guides/dataset/enable_excel2html.md
Labels: 📖 documentation, size:M

#7616 Feat: Fixed the issue where the chat page would jump after entering the homepage #3221
  web/src/components/chunk-method-dialog/dynamic-page-range.tsx
  web/src/components/confirm-delete-dialog.tsx
  web/src/hooks/use-chat-request.ts
  web/src/pages/home/chat-list.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#7624 Feat: let image citation being shown.
  agent/component/retrieval.py
  api/apps/conversation_app.py
  rag/prompts.py
Labels: 💞 feature, ci, size:XS

#7625 Feat: Show images in reply messages #7608
  web/src/pages/chat/markdown-content/index.less
  web/src/pages/chat/markdown-content/index.tsx
Labels: 💞 feature, 🧰 typescript, size:S

#7630 Fix: file name length limit mismtach
  api/db/services/file_service.py
Labels: 🐞 bug, ci, size:XS

#7596 FIX: knowledge will not render a paginator when count is greater than 30
  web/src/pages/knowledge/index.tsx
Labels: 🐞 bug, size:M

#7553 Feat: Add frontend support for third-party login integration
  web/src/assets/svg/sso.svg
  web/src/hooks/auth-hooks.ts
  web/src/hooks/login-hooks.ts
  web/src/pages/login/index.less
  web/src/pages/login/index.tsx
  web/src/services/user-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ☯️ refactor, size:L

#7636 Fix: docx get image exception.
  rag/app/naive.py
  rag/prompts.py
Labels: 🐞 bug, ci, size:XS

#7607 Docs: Update README.md
  README.md
Labels: 📖 documentation, size:S

#7639 Docs: update 7 readme
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:L

#7638 Feat: Display inline (non-quoted) images in the chat and search modules #7623
  web/src/interfaces/database/chat.ts
  web/src/pages/add-knowledge/components/knowledge-testing/testing-result/index.tsx
  web/src/pages/chat/markdown-content/index.tsx
  web/src/utils/chat.ts
Labels: 💞 feature, size:S

#7646 Feat: Add data set configuration form #3221
  web/src/components/page-rank-form-field.tsx
  web/src/components/parse-configuration/graph-rag-form-fields.tsx
  web/src/pages/dataset/setting/category-panel.tsx
  web/src/pages/dataset/setting/chunk-method-form.tsx
  web/src/pages/dataset/setting/configuration/audio.tsx
  web/src/pages/dataset/setting/configuration/book.tsx
  web/src/pages/dataset/setting/configuration/common-item.tsx
  web/src/pages/dataset/setting/configuration/email.tsx
  web/src/pages/dataset/setting/configuration/knowledge-graph.tsx
  web/src/pages/dataset/setting/configuration/laws.tsx
  web/src/pages/dataset/setting/configuration/manual.tsx
  web/src/pages/dataset/setting/configuration/naive.tsx
  web/src/pages/dataset/setting/configuration/one.tsx
  web/src/pages/dataset/setting/configuration/paper.tsx
  web/src/pages/dataset/setting/configuration/picture.tsx
  web/src/pages/dataset/setting/configuration/presentation.tsx
  web/src/pages/dataset/setting/configuration/qa.tsx
  web/src/pages/dataset/setting/configuration/resume.tsx
  web/src/pages/dataset/setting/configuration/table.tsx
  web/src/pages/dataset/setting/configuration/tag.tsx
  web/src/pages/dataset/setting/general-form.tsx
  web/src/pages/dataset/setting/hooks.ts
  web/src/pages/dataset/setting/index.tsx
  web/src/pages/dataset/setting/tag-item.tsx
  web/src/pages/dataset/setting/tag-table/index.tsx
  web/src/pages/dataset/setting/tag-table/rename-dialog/index.tsx
  web/src/pages/dataset/setting/tag-table/rename-dialog/rename-form.tsx
  web/src/pages/dataset/setting/tag-tabs.tsx
  web/src/pages/dataset/setting/tag-word-cloud.tsx
Labels: 💞 feature, 🧰 typescript, size:XXL

#7647 Docs: Chat assistant relative time expressions were enabled in 0.17.1.
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:S

#7620 Feat: update llm factories for SILICONFLOW
  conf/llm_factories.json
Labels: 💞 feature, ci, size:L

#7649 Fix: Anonymize profile input defaults
  web/src/pages/profile-setting/profile/index.tsx
Labels: 🧰 typescript, size:XS

#7653 Trival.
  api/apps/conversation_app.py
Labels: 🐞 bug, ci, size:XS

#7648 Docs: Miscellaneous UI updates
  docs/guides/dataset/configure_knowledge_base.md
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:M

#7656 Feat: When Delete Chunk Will Also Delete Chunk Related Image
  api/apps/chunk_app.py
Labels: 💞 feature, ci, size:XS

#7654 Fix: setuptools package definitions
  pyproject.toml
Labels: 🐞 bug, ci, size:XS

#7652 Fix: Setuptools project.license as a TOML table deprecation
  pyproject.toml
Labels: 🐞 bug, ci, size:XS

#7587 Refa: Deprecate `/github_callback` in favor of `/oauth/callback/<channel>` for GitHub OAuth integration
  api/apps/auth/README.md
  api/apps/auth/__init__.py
  api/apps/auth/github.py
  api/apps/user_app.py
  conf/service_conf.yaml
  docker/service_conf.yaml.template
Labels: 📖 documentation, ci, ☯️ refactor, size:M

#7674 Docs: Added a guide on AI search
  docs/guides/ai_search.md
Labels: 📖 documentation, size:M

#7677 Feat: Add the JS code (or other) executor component to Agent. #4977
  web/src/constants/agent.ts
  web/src/interfaces/database/flow.ts
  web/src/locales/en.ts
  web/src/locales/ja.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/flow/constant.tsx
  web/src/pages/flow/flow-drawer/index.tsx
  web/src/pages/flow/form/code-form/dynamic-input-variable.tsx
  web/src/pages/flow/form/code-form/dynamic-output-variable.tsx
  web/src/pages/flow/form/code-form/index.less
  web/src/pages/flow/form/code-form/index.tsx
  web/src/pages/flow/form/components/dynamic-input-variable.tsx
  web/src/pages/flow/hooks.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7669 Fix: Use DOMPurify to filter out dangerous HTML #7668
  web/src/pages/chat/markdown-content/index.tsx
Labels: 🐞 bug, size:XS

#7666 Feat: Fixed the issue where the dataset configuration page kept refreshing #3221
  web/src/components/form-container.tsx
  web/src/components/parse-configuration/graph-rag-form-fields.tsx
  web/src/hooks/llm-hooks.tsx
  web/src/pages/dataset/setting/chunk-method-form.tsx
  web/src/pages/dataset/setting/configuration-form-container.tsx
  web/src/pages/dataset/setting/configuration/audio.tsx
  web/src/pages/dataset/setting/configuration/book.tsx
  web/src/pages/dataset/setting/configuration/email.tsx
  web/src/pages/dataset/setting/configuration/knowledge-graph.tsx
  web/src/pages/dataset/setting/configuration/laws.tsx
  web/src/pages/dataset/setting/configuration/manual.tsx
  web/src/pages/dataset/setting/configuration/naive.tsx
  web/src/pages/dataset/setting/configuration/one.tsx
  web/src/pages/dataset/setting/configuration/paper.tsx
  web/src/pages/dataset/setting/configuration/picture.tsx
  web/src/pages/dataset/setting/configuration/presentation.tsx
  web/src/pages/dataset/setting/configuration/qa.tsx
  web/src/pages/dataset/setting/configuration/resume.tsx
  web/src/pages/dataset/setting/configuration/table.tsx
  web/src/pages/dataset/setting/configuration/tag.tsx
  web/src/pages/dataset/setting/form-schema.ts
  web/src/pages/dataset/setting/general-form.tsx
  web/src/pages/dataset/setting/hooks.ts
  web/src/pages/dataset/setting/index.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7657 Refa: HTTP API delete dataset / test cases / docs
  api/apps/sdk/dataset.py
  api/utils/validation_utils.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/test/test_http_api/conftest.py
  sdk/python/test/test_http_api/test_dataset_mangement/conftest.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
Labels: 📖 documentation, ci, ☯️ refactor, size:L, 🧪 test

#7672 Feat: add code agent component
  agent/component/__init__.py
  agent/component/code.py
Labels: 💞 feature, ci, size:L

#7678 Fix:Fail to get list_sessions
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:XS

#7671 Feat: launch sandbox from docker-compose
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  api/settings.py
  docker/.env
  docker/docker-compose-base.yml
Labels: 📖 documentation, 💞 feature, ci, size:L

#7682 Fix: Fixed the issue where the height of the chat page shared externally did not fill the window #7460
  web/src/pages/chat/share/index.less
Labels: size:XS

#7675 Docs: Improve oauth configuration documentation and examples
  api/apps/auth/README.md
  conf/service_conf.yaml
  docker/README.md
  docker/service_conf.yaml.template
  docs/configurations.md
Labels: 📖 documentation, ci, size:L

#7684 Test: change variable for ZHIPU_AI_API_KEY
  .github/workflows/tests.yml
  sdk/python/test/test_http_api/conftest.py
Labels: ci, size:XS, 🧪 test

#7685 Docs: Added contribution guidelines and sandbox-related tips
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docs/contribution/_category_.json
  docs/contribution/contributing.md
  docs/quickstart.mdx
Labels: 📖 documentation, size:M

#7691 Fix: Fixed the issue where message references could not be displayed
  web/src/pages/chat/markdown-content/index.tsx
Labels: 🐞 bug, size:S

#7689 Feat: Rendering recall test page #3221
  web/src/components/list-filter-bar/index.tsx
  web/src/components/rerank.tsx
  web/src/components/similarity-slider/index.tsx
  web/src/components/slider-input-form-field.tsx
  web/src/hooks/use-knowledge-request.ts
  web/src/pages/chat/markdown-content/index.tsx
  web/src/pages/dataset/dataset-title.tsx
  web/src/pages/dataset/setting/index.tsx
  web/src/pages/dataset/testing/index.tsx
  web/src/pages/dataset/testing/testing-form.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7692 Docs: Added a guide on switching document engine
  docs/develop/acquire_ragflow_api_key.md
  docs/develop/mcp/_category_.json
  docs/develop/switch_doc_engine.md
  docs/guides/team/join_or_leave_team.md
  docs/guides/team/manage_team_members.md
  docs/guides/team/share_agents.md
  docs/guides/team/share_chat_assistant.md
  docs/guides/team/share_knowledge_bases.md
  docs/guides/team/share_model.md
Labels: 📖 documentation, size:M

#7697 Fix: value too long error for chat name
  api/apps/conversation_app.py
Labels: 🐞 bug, ci, size:XS

#7700 fix: Fix the problem that concurrent execution limit in task executor fails and causes OOM (issue#7580)
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7690 When creating an assistant, no dataset is specified, a different default system promt is used
  api/apps/dialog_app.py
Labels: 💞 feature, ci, size:S

#7693 Feat: repair corrupted PDF files on upload automatically
  .github/workflows/tests.yml
  Dockerfile
  api/apps/document_app.py
  api/db/services/file_service.py
  api/utils/file_utils.py
Labels: 💞 feature, ci, size:XL

#7683 Fix: uncaptured image data with position information
  deepdoc/parser/figure_parser.py
Labels: 🐞 bug, ci, size:S

#7710 Refa: more fallbacks for bad citation format
  api/db/services/dialog_service.py
Labels: ci, ☯️ refactor, size:M

#7714 Feat: Modify the Python language template code of the code operator #4977
  web/src/constants/agent.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/pages/dataset/testing/index.tsx
  web/src/pages/dataset/testing/testing-result.tsx
  web/src/pages/flow/form/code-form/index.tsx
Labels: 💞 feature, size:L

#7325 Fix:When you create a new API module named xxxa_api, the access route will become xxx instead of xxxa. For example, when I create a new API module named 'data_api', the access route will become 'dat' instead of 'data
  api/apps/__init__.py
  api/apps/kb_app.py
Labels: 🐞 bug, ci, size:XS

#7709 Feat: Add OAuth `state` parameter for CSRF protection
  api/apps/auth/oauth.py
  api/apps/user_app.py
Labels: 💞 feature, ci, size:S

#7720 Refa: HTTP API list datasets / test cases / docs
  api/apps/sdk/dataset.py
  api/utils/api_utils.py
  api/utils/validation_utils.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
Labels: 📖 documentation, ci, ☯️ refactor, size:XXL, 🧪 test

#7723 Feat: The image displayed in the reply message can also be clicked to display the location of the source document where the slice is located #7623
  web/src/components/image/index.tsx
  web/src/pages/chat/markdown-content/index.less
  web/src/pages/chat/markdown-content/index.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#7731 Feat: Migrate the code operator to the new agent. #3221
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/code-form/dynamic-input-variable.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/hooks.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7739 Feat: sandox enhancement
  docker/.env
  docker/docker-compose-base.yml
Labels: 💞 feature, ci, size:XS

#7738 Fix: wrong type hint
  api/db/services/dialog_service.py
Labels: 🐞 bug, ci, size:XS

#7740 Feat: Rename agent #3221
  web/src/hooks/use-agent-request.ts
  web/src/pages/agents/agent-card.tsx
  web/src/pages/agents/agent-dropdown.tsx
  web/src/pages/agents/index.tsx
  web/src/pages/agents/use-rename-agent.ts
Labels: 💞 feature, size:L

#7747 0519 pdfparser
  docs/develop/mcp/launch_mcp_server.md
  docs/develop/switch_doc_engine.md
  docs/guides/ai_search.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/dataset/select_pdf_parser.md
  docs/guides/dataset/set_metadata.md
  web/src/locales/de.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:M

#7727 Feat: delete useless image blobs when task executor meet edge cases
  rag/svr/task_executor.py
Labels: 💞 feature, ci, size:S

#7756 Feat: Fixed the issue where the page would refresh continuously when opening the sheet on the right side of the canvas #3221
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
  web/src/pages/agent/hooks.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7770 Feat: Switching the programming language of the code operator will switch the corresponding language template #3221
  web/src/pages/agent/canvas/node/note-node.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-watch-form-change.ts
Labels: 💞 feature, 🧰 typescript, size:L

#7776 Feat: Add return value widget to CodeForm #3221
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7765 Fix: improve task cancel lag
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7782 Fix: resolve regex library warnings
  deepdoc/parser/resume/entities/corporations.py
  deepdoc/parser/resume/step_two.py
  rag/nlp/__init__.py
Labels: ci, ☯️ refactor, size:S

#7769 fix：When creating a new assistant, an avatar was uploaded, but when selecting the assistant to start a new chat, the default avatar still appears in the chat window instead of the one uploaded during creation
  web/src/pages/chat/chat-container/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:XS

#7777 Feat: change default models
  api/apps/sdk/chat.py
  api/apps/user_app.py
  api/settings.py
  conf/llm_factories.json
  sdk/python/test/conftest.py
  sdk/python/test/test_http_api/conftest.py
  sdk/python/test/test_sdk_api/t_chat.py
Labels: 💞 feature, wip, ci, size:L

#7792 Feat: Refactor BeginForm with shadcn #3221
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/hooks.ts
  web/src/pages/agent/form/begin-form/index.less
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/next-begin-dynamic-options.tsx
  web/src/pages/agent/form/begin-form/next-paramater-modal.tsx
  web/src/pages/agent/form/begin-form/query-table.tsx
Labels: 💞 feature, ci, size:L

#7794 Feat: Verify the parameters of the begin operator #3221
  web/src/components/ui/button.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/paramater-dialog.tsx
  web/src/utils/common-util.ts
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7801 Feat: more robust fallbacks for citations
  api/db/services/dialog_service.py
Labels: 🐞 bug, 💞 feature, ci, size:XS

#7799 Fix baidu request error
  agent/component/baidu.py
Labels: 🐞 bug, ci, size:M

#7798 Feat: Synchronize BeginForm's query data to the canvas #3221
  web/src/pages/agent/form/begin-form/begin-dynamic-options.tsx
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/next-begin-dynamic-options.tsx
  web/src/pages/agent/form/begin-form/paramater-modal.tsx
  web/src/pages/agent/form/begin-form/parameter-dialog.tsx
  web/src/pages/agent/form/begin-form/use-edit-query.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7793 Fix backquotes in text2sql causing execution errors
  agent/component/exesql.py
Labels: 🐞 bug, ci, size:XS

#7807 Feat: Reconstruct the QueryTable of BeginForm using shandcn #3221
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/query-table.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7809 Feat: add claude4 models
  conf/llm_factories.json
Labels: 💞 feature, ci, size:S

#7812 Docs: Added instructions on cross-language search
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/dataset/run_retrieval_test.md
  docs/quickstart.mdx
  docs/references/glossary.mdx
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  docs/references/supported_models.mdx
Labels: 📖 documentation, size:M

#7811 Feat: Translate the begin operator #3221
  web/src/components/collapse.tsx
  web/src/components/ui/form.tsx
  web/src/components/ui/tooltip.tsx
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7806 Fix: Improve First Chunk Size
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:XS

#7813 Docs: Added instructions on cross-language search (#7812)
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/dataset/run_retrieval_test.md
  docs/quickstart.mdx
  docs/references/glossary.mdx
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  docs/references/supported_models.mdx
Labels: 📖 documentation, size:M

#7818 Docs: Added v0.19.0 release notes
  docs/release_notes.md
Labels: 📖 documentation, size:S

#7814 Feat: add code_executor_manager
  .gitignore
  sandbox/Makefile
  sandbox/README.md
  sandbox/asserts/code_executor_manager.svg
  sandbox/docker-compose.yml
  sandbox/executor_manager/Dockerfile
  sandbox/executor_manager/api/__init__.py
  sandbox/executor_manager/api/handlers.py
  sandbox/executor_manager/api/routes.py
  sandbox/executor_manager/core/__init__.py
  sandbox/executor_manager/core/config.py
  sandbox/executor_manager/core/container.py
  sandbox/executor_manager/core/logger.py
  sandbox/executor_manager/main.py
  sandbox/executor_manager/models/__init__.py
  sandbox/executor_manager/models/enums.py
  sandbox/executor_manager/models/schemas.py
  sandbox/executor_manager/requirements.txt
  sandbox/executor_manager/seccomp-profile-default.json
  sandbox/executor_manager/services/__init__.py
  sandbox/executor_manager/services/execution.py
  sandbox/executor_manager/services/limiter.py
  sandbox/executor_manager/services/security.py
  sandbox/executor_manager/util.py
  sandbox/executor_manager/utils/__init__.py
  sandbox/executor_manager/utils/common.py
  sandbox/pyproject.toml
  sandbox/sandbox_base_image/nodejs/Dockerfile
  sandbox/sandbox_base_image/nodejs/package-lock.json
  sandbox/sandbox_base_image/nodejs/package.json
  sandbox/sandbox_base_image/python/Dockerfile
  sandbox/sandbox_base_image/python/requirements.txt
  sandbox/scripts/restart.sh
  sandbox/scripts/start.sh
  sandbox/scripts/stop.sh
  sandbox/scripts/wait-for-it-http.sh
  sandbox/scripts/wait-for-it.sh
  sandbox/tests/sandbox_security_tests_full.py
  sandbox/uv.lock
Labels: 💞 feature, ci, size:XXL

#7816 Update rag/nlp/query.py
  rag/nlp/query.py
Labels: 🐞 bug, ci, size:S

#7823 Docs: update for v0.19.0
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/develop/build_docker_image.mdx
  docs/faq.mdx
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/tracing.mdx
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/release_notes.md
  helm/values.yaml
  pyproject.toml
  sdk/python/pyproject.toml
  sdk/python/uv.lock
  uv.lock
Labels: 📖 documentation, ci, size:L

#7821 Docs: Added code component reference
  docs/guides/agent/agent_component_reference/code.mdx
  docs/guides/agent/agent_component_reference/note.mdx
  docs/release_notes.md
Labels: 📖 documentation, size:M

#7820 Feat: Refactor the MessageForm with shadcn #3221
  web/src/components/prompt-editor/index.tsx
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/begin-dynamic-options.tsx
  web/src/pages/agent/form/code-form/dynamic-input-variable.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
  web/src/pages/agent/form/message-form/index.tsx
Labels: 💞 feature, ci, ☯️ refactor, size:L

#7825 Fix: Fixed the issue that the script text of the code operator is not displayed after refreshing the page after saving the script text of the code operator #4977
  web/src/pages/flow/form/code-form/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:S

#7822 Refa: update gemini2.5
  conf/llm_factories.json
Labels: ci, ☯️ refactor, size:XS

#7826 Fix: Fixed the issue that the script text of the code operator is not displayed after refreshing the page after saving the script text of the code operator #4977
  web/src/pages/flow/form/code-form/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:S

#7827 Fix: catch non-begin component output
  agent/component/code.py
Labels: 🐞 bug, ci, size:S

#7843 Fix: list out of boundary
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:XS

#7844 Fix: restore task limiter.
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7862 Feat: Add the WaitingDialogue operator. #3221
  web/src/pages/agent/agent-sidebar.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/query-table.tsx
  web/src/pages/agent/form/waiting-dialogue-form/index.tsx
  web/src/pages/agent/hooks/use-watch-form-change.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7857 update xgboost and dep scripts for local build on MacOS
  .gitignore
  download_deps.py
  pyproject.toml
  uv.lock
Labels: ci, size:S

#7873 Fix: task limiter issue.
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7887 Fix: patch regex vulnerability in filename handling
  api/db/services/__init__.py
Labels: 🐞 bug, ci, size:L

#7878 Perf: reduce upload to minio limiter scope
  rag/svr/task_executor.py
Labels: ci, size:M

#7892 Feat: Add the SelectWithSearch component #3221
  web/src/components/large-model-form-field.tsx
  web/src/components/llm-select/index.tsx
  web/src/components/llm-select/next.tsx
  web/src/components/llm-setting-items/next.tsx
  web/src/components/llm-setting-items/slider.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/categorize-form/index.tsx
  web/src/pages/agent/form/generate-form/index.tsx
  web/src/pages/agent/form/keyword-extract-form/index.tsx
  web/src/pages/agent/form/rewrite-question-form/index.tsx
  web/src/utils/file-util.ts
Labels: 💞 feature, ci, 🧰 typescript, size:XL

#7864 Update README.md
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:S

#7903 fix: resolve “has no attribute 'max_length'” error in keyword_extraction
  api/apps/api_app.py
Labels: 🐞 bug, ci, size:S

#7899 Fix: KeyError: 'method' when build run_graphrag
  graphrag/general/index.py
Labels: 🐞 bug, ci, size:XS
