Repository infiniflow/ragflow, pull requests merged in 2025-08, with the labels that each got.

#9142 Feat: Delete the operator node and hide the corresponding sheet #3221
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/begin-node.tsx
  web/src/pages/agent/canvas/node/note-node/index.tsx
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/hooks/use-show-drawer.tsx
  web/src/pages/agent/operator-icon.tsx
Labels: 💞 feature, ci, size:M

#9139 Fix: Redis stream lag can be nil
  api/db/services/document_service.py
Labels: 🐞 bug, ci, size:XS

#9150 Fix: Fix share-chat bugs
  web/src/components/next-message-item/index.tsx
  web/src/hooks/logic-hooks.ts
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/hooks/use-cache-chat-log.ts
  web/src/pages/agent/interface.ts
  web/src/pages/agents/agent-log-detail-modal.tsx
  web/src/pages/next-chats/share/index.tsx
  web/src/pages/next-chats/share/parameter-dialog.tsx
Labels: 🐞 bug, ci, size:L

#9166 Fix: Fixed share-log UI issues and log-template bugs
  web/src/components/next-message-item/index.less
  web/src/components/next-message-item/index.tsx
  web/src/components/ui/button.tsx
  web/src/hooks/use-send-message.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/log-sheet/toolTimelineItem.tsx
  web/src/pages/agent/log-sheet/workFlowTimeline.tsx
  web/src/pages/agents/agent-log-detail-modal.tsx
  web/src/pages/agents/agent-log-page.tsx
  web/src/pages/agents/agent-templates.tsx
  web/src/pages/next-chats/share/index.tsx
  web/tailwind.css
Labels: 🐞 bug, ci, size:L

#9169 Docs: Updated docs for 0.20.0
  docs/guides/agent/agent_component_reference/agent.mdx
  docs/guides/agent/agent_component_reference/await_response.mdx
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/guides/agent/agent_component_reference/categorize.mdx
  docs/guides/agent/agent_component_reference/code.mdx
  docs/guides/agent/agent_component_reference/concentrator.mdx
  docs/guides/agent/agent_component_reference/generate.mdx
  docs/guides/agent/agent_component_reference/interact.mdx
  docs/guides/agent/agent_component_reference/iteration.mdx
  docs/guides/agent/agent_component_reference/keyword.mdx
  docs/guides/agent/agent_component_reference/message.mdx
  docs/guides/agent/agent_component_reference/note.mdx
  docs/guides/agent/agent_component_reference/retrieval.mdx
  docs/guides/agent/agent_component_reference/switch.mdx
  docs/guides/agent/agent_component_reference/template.mdx
  docs/guides/agent/agent_component_reference/text_processing.mdx
  docs/guides/agent/agent_introduction.md
  docs/guides/agent/embed_agent_into_webpage.md
  docs/guides/agent/general_purpose_chatbot.md
  docs/guides/agent/text2sql_agent.md
  docs/guides/dataset/use_tag_sets.md
Labels: 📖 documentation, size:XXL

#9164 Docs: Update version references to v0.20.0 in READMEs and docs
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/develop/build_docker_image.mdx
  docs/faq.mdx
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/tracing.mdx
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/references/glossary.mdx
  helm/values.yaml
  pyproject.toml
  sdk/python/pyproject.toml
  sdk/python/uv.lock
  uv.lock
Labels: 📖 documentation, size:L

#8245 Feat: Add the migration script and its doc, added `backup` as default…
  .gitignore
  docker/migration.sh
  docs/guides/migration/migrate_from_docker_compose.md
Labels: 📖 documentation, 💞 feature, ci, size:L

#9103 Fix: list tags api by using tenant id instead of user id
  api/apps/kb_app.py
Labels: 🐞 bug, ci, size:S

#9196 Fix:Repeated images when parsing markdown files with images
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:S

#9198 Refactor: support config strong test
  api/settings.py
  api/utils/api_utils.py
Labels: ci, ☯️ refactor, size:XS

#9204 Fix: migrate deprecated Langfuse API from v2 to v3
  api/db/services/dialog_service.py
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:M

#9212 fix #8424 NPE in dify_retrieval.py, add log exception
  api/apps/sdk/dify_retrieval.py
Labels: 🐞 bug, ci, size:XS

#9209 fix "TypeError: '<' not supported between instances of 'Emu' and 'Non…
  deepdoc/parser/ppt_parser.py
Labels: 🐞 bug, ci, size:XS

#9211 fix "out of memory" if slide.get_thumbnail() to a huge image
  rag/app/presentation.py
Labels: 🐞 bug, ci, size:XS

#9214 Feat: list documents supports range filtering
  api/apps/document_app.py
  api/apps/sdk/doc.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/dataset.py
Labels: 🌈 python, ci, size:M

#9218 v0.20.0 release notes
  docs/release_notes.md
Labels: 📖 documentation, size:M

#9219 Fix: Fixed the issue where the agent's chat box could not automatically scroll to the bottom #3221
  web/src/hooks/logic-hooks.ts
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/chat/chat-container/index.tsx
  web/src/pages/chat/hooks.ts
  web/src/pages/next-chats/share/index.tsx
Labels: 🐞 bug, ci, size:M

#9222 Fix: Add prompt text to the form in the MCP module
  web/src/locales/en.ts
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
Labels: 🐞 bug, ci, size:S

#9217 Fix: self-deployed LLM error,
  api/apps/sdk/dify_retrieval.py
  api/db/services/canvas_service.py
  api/db/services/llm_service.py
  rag/utils/s3_conn.py
Labels: ci, ☯️ refactor, size:S

#9223 Refa: ensure Redis stream queue could be created properly
  rag/utils/redis_conn.py
Labels: ci, ☯️ refactor, size:S

#9235 Docs: Updated tips for max rounds
  docs/guides/agent/agent_component_reference/agent.mdx
  docs/release_notes.md
Labels: 📖 documentation, size:S

#9238 Fix: Set the maximum number of rounds for the agent to 1 #3221
  web/src/components/originui/number-input.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/form-config-map.tsx
  web/src/pages/agent/form/answer-form/index.tsx
  web/src/pages/agent/form/categorize-form/index.tsx
  web/src/pages/agent/form/concentrator-form/index.tsx
  web/src/pages/agent/form/generate-form/index.tsx
  web/src/pages/agent/form/invoke-form/index.less
  web/src/pages/agent/form/iteration-form/index.tsx
  web/src/pages/agent/form/message-form/index.tsx
  web/src/pages/agent/form/string-transform-form/index.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/template-form/index.tsx
  web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: ci, size:L

#9233 Fix: fix mismatch of assitant message and its reference
  api/apps/conversation_app.py
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:S

#9242 Refactor:Improve the chat stream logic for NvidiaCV
  rag/llm/cv_model.py
Labels: ci, ☯️ refactor, size:XS

#9251 Fix: resolve the prompt problem of Customer Support Workflow
  agent/templates/customer_service.json
  agent/templates/customer_support.json
Labels: 🐞 bug, ci, size:S

#9255 Fix: local variable issue.
  rag/llm/cv_model.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#9260 Update readme
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:S

#9173 Added French language support
  web/src/constants/common.ts
  web/src/locales/config.ts
  web/src/locales/fr.ts
  web/src/pages/agent/options.ts
  web/src/pages/flow/constant.tsx
Labels: 💞 feature, ci, size:XXL

#9266 Feat: Added history management and paste handling features #3221
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/components/prompt-editor/paste-handler-plugin.tsx
  web/src/pages/agent/index.tsx
  web/src/pages/agent/use-agent-history-manager.ts
Labels: ci, size:L

#9246 FIX: If chunk["content_with_weight"] contains one or more unpaired surrogate characters (such as incomplete emoji or other special characters), then calling .encode("utf-8") directly will raise a UnicodeEncodeError.
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#9267 Fix:remove a img close which can not operate
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:XS

#9264 Refactor:Improve the logic so that it does not decode base 64 for the test image each time
  api/apps/llm_app.py
  api/utils/base64_image.py
Labels: ci, ☯️ refactor, size:XS

#9269 Feat: Create a conversation #3221
  web/src/hooks/use-chat-request.ts
  web/src/pages/home/chat-list.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/hooks/use-rename-chat.ts
  web/src/pages/next-chats/index.tsx
  web/src/services/next-chat-service .ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:L

#9273 Refa: add provider info while adding model.
  api/apps/llm_app.py
  rag/svr/task_executor.py
  rag/utils/s3_conn.py
Labels: ci, ☯️ refactor, size:M

#9252 Add **kwargs to model base class constructors
  rag/llm/chat_model.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
  rag/llm/sequence2txt_model.py
  rag/llm/tts_model.py
Labels: 🐞 bug, size:M

#9289 fix: add missing env vars and default values of service_conf.yaml
  docker/.env
  docker/service_conf.yaml.template
  rag/utils/opendal_conn.py
Labels: 🐞 bug, ci, size:XS

#9297 fix: Optimized popups and the search page
  web/src/components/ui/modal/modal-manage.tsx
  web/src/components/ui/modal/modal.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agents/agent-log-detail-modal.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/dataset/setting/index.tsx
  web/src/pages/next-chats/share/parameter-dialog.tsx
  web/src/pages/next-searches/index.tsx
  web/src/pages/next-searches/search-card.tsx
Labels: 🐞 bug, ci, size:L

#9298 Feat: Render chat page #3221
  web/src/hooks/use-chat-request.ts
  web/src/pages/next-chats/chat-card.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings-sheet.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/sessions.tsx
  web/src/pages/next-chats/hooks/use-button-disabled.tsx
  web/src/pages/next-chats/hooks/use-click-card.ts
  web/src/pages/next-chats/hooks/use-create-conversation.ts
  web/src/pages/next-chats/hooks/use-select-conversation-list.ts
  web/src/pages/next-chats/hooks/use-send-chat-message.ts
Labels: 💞 feature, ci, size:XL

#9296 Refactor:naive_merge_with_images close useless images
  rag/nlp/__init__.py
Labels: ci, ☯️ refactor, size:XS

#9282 Fix: virtual file cannot be displayed in KB
  api/apps/document_app.py
Labels: 🐞 bug, ci, size:S

#9301 Feat: Configure colors according to the design draft#3221
  web/src/components/edit-tag/index.tsx
  web/src/components/next-message-item/index.tsx
  web/src/components/ui/badge.tsx
  web/src/components/ui/button.tsx
  web/src/components/ui/card.tsx
  web/src/components/ui/table.tsx
  web/src/locales/en.ts
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/categorize-node.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/embed-dialog/index.tsx
  web/src/pages/agent/form/agent-form/agent-tools.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/log-sheet/toolTimelineItem.tsx
  web/src/pages/agent/log-sheet/workFlowTimeline.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/next-chats/chat/sessions.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, size:L

#9304 Fix: bytes style image issue.
  api/settings.py
  rag/llm/cv_model.py
  rag/utils/s3_conn.py
Labels: 🐞 bug, ci, size:S

#9308 Fix: model type error.
  agent/tools/retrieval.py
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:XS

#9311 Add files viaContribute a new workflow template: SQL Assistant upload
  agent/templates/SQL Assistant.json
Labels: ci, size:XS

#9309 Fix: update broken agent completion due to v0.20.0 changes
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
Labels: 🐞 bug, ci, size:M

#9312 Feat: Render agent setting dialog #3221
  web/src/components/ragflow-form.tsx
  web/src/components/shared-badge.tsx
  web/src/components/ui/radio-group.tsx
  web/src/hooks/use-agent-request.ts
  web/src/interfaces/database/flow.ts
  web/src/pages/agent/index.tsx
  web/src/pages/agent/setting-dialog/index.tsx
  web/src/pages/agent/setting-dialog/setting-form.tsx
  web/src/pages/agents/agent-card.tsx
  web/tailwind.config.js
Labels: 💞 feature, ci, size:L

#9320 Feat: supports GPT-5
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  conf/llm_factories.json
Labels: 💞 feature, ci, size:M

#9250 fix model type
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:XS

#9321 Feat: Add xai logo #1853
  web/src/assets/svg/llm/grok.svg
  web/src/assets/svg/llm/xai.svg
  web/src/constants/llm.ts
Labels: 💞 feature, ci, size:XS

#9327 Feat: Set the description of the agent, which can be null #3221
  web/src/pages/agent/setting-dialog/setting-form.tsx
Labels: ci, size:XS

#9322 Fix: add prologue to api.
  api/apps/canvas_app.py
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:S

#9331 Docs: v0.20.1 release notes
  docs/guides/agent/agent_component_reference/agent.mdx
  docs/release_notes.md
Labels: 📖 documentation, size:M

#9339 Fix: canvas sharing bug.
  api/apps/canvas_app.py
  api/db/services/canvas_service.py
Labels: 🐞 bug, size:M

#9342 Refa: code format.
  api/apps/canvas_app.py
Labels: ci, ☯️ refactor, size:XS

#9344 Feat: New search page components and features
  web/src/components/ragflow-avatar.tsx
  web/src/components/ui/multi-select.tsx
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/pages/next-search/index.less
  web/src/pages/next-search/index.tsx
  web/src/pages/next-search/search-home.tsx
  web/src/pages/next-search/search-setting.tsx
  web/src/pages/next-search/searching.tsx
  web/src/pages/next-search/spotlight.tsx
  web/src/pages/next-searches/hooks.ts
  web/src/pages/next-searches/index.tsx
  web/src/pages/next-searches/search-card.tsx
  web/src/pages/next-searches/search-dropdown.tsx
  web/src/routes.ts
  web/src/services/search-service.ts
  web/src/utils/api.ts
Labels: 🐞 bug, 💞 feature, ci, size:XXL

#9362 Support Russian in UI
  web/src/locales/ru.ts
Labels: ci, size:XXL

#9354 Fix broken data stream when writing image file
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#9381 Fix: Remove default dataset_ids from Chat class initialization
  sdk/python/ragflow_sdk/modules/chat.py
Labels: 🐞 bug, ci, size:XS

#9386 Fix: Update test assertions and add GraphRAG config in dataset tests
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_update_chunk.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
Labels: 🐞 bug, ci, size:XS

#9324 Fix: handle missing dataset_ids when creating chat assistant
  api/apps/sdk/chat.py
Labels: 🐞 bug, ci, size:XS

#9225 Support the case of one cell split by multiple columns.
  rag/app/table.py
Labels: 🐞 bug, ci, size:L

#9393 Feat: Allow chat to use meta data #3221
  web/.umirc.ts
  web/src/hooks/common-hooks.tsx
  web/src/hooks/use-knowledge-request.ts
  web/src/locales/en.ts
  web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
  web/src/pages/chat/chat-configuration-modal/metadata-filter-conditions.tsx
  web/src/pages/chat/constants.ts
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/sessions.tsx
  web/src/services/knowledge-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci

#9400 Fix: Update test assertions and simplify test cases
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
Labels: ci, size:XS, 🧪 test

#9394 Refa: migrate chat models to LiteLLM
  api/apps/llm_app.py
  api/db/services/llm_service.py
  pyproject.toml
  rag/llm/__init__.py
  rag/llm/chat_model.py
  uv.lock
  web/src/locales/config.ts
  web/src/locales/ru.ts
Labels: ci, ☯️ refactor, size:XXL

#9399 Fix:HTTP request component failed to retrieve the corresponding value
  agent/component/invoke.py
Labels: 🐞 bug, ci, size:XS

#9374 Add fallback to use 'calamine' parse engine in excel_parser.py
  deepdoc/parser/excel_parser.py
  pyproject.toml
  uv.lock
Labels: 🐞 bug, ci, size:S

#9363 Fix:TypeError: OllamaCV.chat() got an unexpected keyword argument 'stop'
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:S

#9416 Fix: Patch LiteLLM
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:M

#9413 Fix: remove doc error.
  api/db/services/document_service.py
Labels: 🐞 bug, ci, size:XS

#9417 Feat: Added meta data to the chat configuration page #8531
  web/src/interfaces/database/chat.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
  web/src/pages/chat/chat-configuration-modal/metadata-filter-conditions.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-model-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings-sheet.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/subhead.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-chats/chat/sessions.tsx
Labels: 💞 feature, ci, size:L

#9420 Refa: Update LLM stream response type to Generator
  agent/component/llm.py
Labels: ci, ☯️ refactor, size:XS

#9404 Feat: allows setting multiple types of default models in service config
  api/apps/user_app.py
  api/db/init_data.py
  api/settings.py
  conf/service_conf.yaml
Labels: 💞 feature, ci, size:L

#9430 Feat: Fixed the issue where some fields in the chat configuration could not be displayed #3221
  api/db/services/dialog_service.py
  web/src/components/llm-setting-items/next.tsx
  web/src/components/llm-setting-items/slider.tsx
  web/src/components/llm-setting-items/use-watch-change.ts
  web/src/components/rerank.tsx
  web/src/components/similarity-slider/index.tsx
  web/src/components/slider-input-form-field.tsx
  web/src/components/top-n-item.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/next-chats/chat/app-settings/chat-model-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-chats/chat/sessions.tsx
Labels: ci, size:L

#9428 Refactor:Improve the float compare for LocalAIRerank
  rag/llm/rerank_model.py
Labels: ci, ☯️ refactor, size:XS

#9434 Docs: Update HTTP API reference with new response fields
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:XS

#9435 Fix: no doc hits after meta data filter.
  api/db/services/dialog_service.py
  rag/prompts/citation_prompt.md
  rag/utils/s3_conn.py
Labels: 🐞 bug, ci, size:S

#9443 Feat: Show multiple chat boxes #3221
  web/src/components/originui/password-input.tsx
  web/src/components/page-header.tsx
  web/src/components/password-input/index.tsx
  web/src/components/tavily-form-field.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx
  web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/use-add-box.ts
  web/src/pages/profile-setting/profile/index.tsx
Labels: 💞 feature, ci, size:L

#9464 Docs: Deprecated 'Create session with agent'
  agent/templates/sql_assistant.json
  api/apps/sdk/chat.py
  api/db/db_models.py
  docs/references/http_api_reference.md
  sdk/python/ragflow_sdk/modules/chat.py
  sdk/python/ragflow_sdk/ragflow.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  test/testcases/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  test/testcases/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_create_chat_assistant.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_update_chat_assistant.py
  web/src/locales/en.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/flow/constant.tsx
Labels: 📖 documentation, ci, size:M

#9477 Feat: Send data to compare the performance of different models' answers #3221
  web/src/hooks/logic-hooks.ts
  web/src/interfaces/database/chat.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx
  web/src/pages/next-chats/hooks/use-build-form-refs.ts
  web/src/pages/next-chats/hooks/use-send-multiple-message.ts
Labels: 💞 feature, ci, size:L

#9474 fix: preserve correct MIME & unify data URL handling for vision inputs (relates #9248)
  rag/llm/cv_model.py
Labels: 🐞 bug, ci, size:S

#9483 Feat: Upload files in the chat box #3221
  web/src/hooks/logic-hooks.ts
  web/src/hooks/use-chat-request.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx
  web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/hooks/use-send-chat-message.ts
  web/src/pages/next-chats/hooks/use-send-multiple-message.ts
  web/src/pages/next-chats/hooks/use-upload-file.ts
  web/src/services/next-chat-service.ts
Labels: 💞 feature, ci, size:L

#9484 Feat: add citation option to agent and enlarge the timeouts.
  agent/component/agent_with_tools.py
  agent/component/llm.py
  graphrag/entity_resolution.py
  graphrag/general/community_reports_extractor.py
  graphrag/general/index.py
  rag/svr/task_executor.py
Labels: 💞 feature, ci, size:M

#9491 Feat: Delete or filter conversations #3221
  web/src/hooks/logic-hooks/use-change-search.ts
  web/src/hooks/use-chat-request.ts
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/conversation-dropdown.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/llm-select-form.tsx
  web/src/pages/next-chats/chat/sessions.tsx
  web/src/pages/next-chats/hooks/use-select-conversation-list.ts
Labels: 💞 feature, ci, size:L

#9496 Refactor:Standardize image conf and add private registry support
  helm/templates/elasticsearch.yaml
  helm/templates/infinity.yaml
  helm/templates/minio.yaml
  helm/templates/mysql.yaml
  helm/templates/opensearch.yaml
  helm/templates/ragflow.yaml
  helm/templates/redis.yaml
  helm/values.yaml
Labels: ☯️ refactor, size:L

#9500 Fix: unexpected truncated Excel files
  deepdoc/parser/excel_parser.py
  rag/app/naive.py
Labels: 🐞 bug, ci, size:S

#9485 Feat: conversation completion can specify different model
  api/apps/conversation_app.py
  api/db/db_models.py
  api/db/services/dialog_service.py
Labels: 💞 feature, ci, size:M

#9487 Fix the bug in enablePrologue under agent task mode
  web/src/pages/agent/form/begin-form/index.tsx
Labels: 🐞 bug, ci, size:S

#9536 Refa: refine search app
  api/apps/conversation_app.py
  api/apps/sdk/session.py
  api/db/db_models.py
  api/db/services/dialog_service.py
Labels: ci, ☯️ refactor, size:L

#9535 feat(search): Optimized search functionality and user interface #3221
  web/src/interfaces/request/chat.ts
  web/src/layouts/next-header.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/log-sheet/tool-timeline-item.tsx
  web/src/pages/agent/log-sheet/workflow-timeline.tsx
  web/src/pages/next-search/embed-app-modal.tsx
  web/src/pages/next-search/hooks.ts
  web/src/pages/next-search/index.tsx
  web/src/pages/next-search/markdown-content/index.tsx
  web/src/pages/next-search/mindmap-drawer.tsx
  web/src/pages/next-search/search-home.tsx
  web/src/pages/next-search/search-setting.tsx
  web/src/pages/next-search/search-view.tsx
  web/src/pages/next-search/share/index.tsx
  web/src/pages/next-searches/hooks.ts
  web/src/pages/search/hooks.ts
Labels: 🐞 bug, ci, size:L

#9534 Feat: Allow agent operators to select speech-to-text models #3221
  web/src/components/large-model-form-field.tsx
  web/src/components/llm-select/next.tsx
  web/src/components/message-item/index.less
  web/src/components/message-item/index.tsx
  web/src/hooks/logic-hooks.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/sessions.tsx
Labels: 💞 feature, ci, size:M

#9528 Fix: ensure update_progress loop always waits between iterations
  api/ragflow_server.py
Labels: 🐞 bug, ci, size:XS

#9524 Feat: Support metadata auto filer for Search.
  agent/canvas.py
  agent/component/agent_with_tools.py
  agent/tools/base.py
  agent/tools/exesql.py
  api/db/services/dialog_service.py
  rag/nlp/__init__.py
  rag/prompts/ask_summary.md
  rag/prompts/prompts.py
Labels: 💞 feature, ci, size:M

#9539 Refactor:Improve VoyageRerank not texts handling
  rag/llm/rerank_model.py
Labels: ci, ☯️ refactor, size:XS

#9553 Docs: Updated v0.20.2 release notes
  docs/release_notes.md
Labels: 📖 documentation, size:XS

#9552 Refa: OpenAI whisper-1
  api/apps/dialog_app.py
  conf/llm_factories.json
  rag/app/audio.py
  rag/llm/sequence2txt_model.py
Labels: 🐞 bug, ci, ☯️ refactor, size:M

#9542 Fix: Fixed the issue where clicking the SQL tool test button did not request the interface #9541
  web/src/components/metadata-filter/index.tsx
  web/src/components/metadata-filter/metadata-filter-conditions.tsx
  web/src/constants/chat.ts
  web/src/layouts/next-header.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/exesql-form/use-submit-form.ts
  web/src/pages/agent/form/tool-form/exesql-form/index.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-chats/hooks/use-build-form-refs.ts
  web/src/pages/next-chats/hooks/use-rename-chat.ts
  web/src/pages/next-search/search-setting.tsx
  web/src/pages/next-searches/hooks.ts
Labels: 🐞 bug, ci, size:L

#9561 Docs: Updated workarounds for uploading file to an agent
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:S

#9558 Refa: create new name for duplicated dialog name
  api/apps/dialog_app.py
Labels: ci, ☯️ refactor, size:S

#9566 Fix: no effect on retrieval_test in term of metadata filter.
  api/apps/chunk_app.py
  api/apps/conversation_app.py
  api/db/services/dialog_service.py
Labels: 🐞 bug, ci, size:M

#9569 Fix (next search): Optimize the search problem interface and related functions #3221
  web/src/components/home-card.tsx
  web/src/pages/agents/agent-card.tsx
  web/src/pages/agents/index.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/next-chats/chat-card.tsx
  web/src/pages/next-chats/index.tsx
  web/src/pages/next-search/hooks.ts
  web/src/pages/next-search/search-view.tsx
  web/src/pages/next-searches/search-card.tsx
Labels: 🐞 bug, ci, size:L

#9574 Fix dataset card not responding to click events
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/locales/zh.ts
  web/src/pages/agents/agent-card.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/home/search-list.tsx
  web/src/pages/next-chats/chat-card.tsx
  web/src/pages/next-searches/index.tsx
  web/src/pages/next-searches/search-card.tsx
Labels: 🐞 bug, ci, size:S

#9583 Docs: Updated v0.20.3 release notes
  docs/release_notes.md
Labels: 📖 documentation, size:XS

#9592 Revert "Feat: reference should also be list after 0.20.x"
  api/db/services/canvas_service.py
Labels: size:XS

#9591 Fix (web): Update the style of segmented controls and add metallic texture gradients
  web/src/components/ui/segmented.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 🐞 bug, ci, size:S

#9571 Fix:KeyError: 'globals' KeyError： 'globals'
  agent/canvas.py
Labels: 🐞 bug, ci, size:S

#9600 Fix: enlarge raptor timeout limits.
  rag/app/naive.py
  rag/raptor.py
Labels: 🐞 bug, ci, size:XS

#8707 Feat: expand the capabilities of the MCP Server
  mcp/server/server.py
Labels: 💞 feature, ci, size:L

#9605 Feature (web): Optimize dataset pages and segmented components #3221
  web/src/components/ui/segmented.tsx
  web/src/locales/en.ts
  web/src/pages/dataset/dataset/dataset-action-cell.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/home/applications.tsx
Labels: 🐞 bug, ci, size:S

#9618 Fix: Remove the file size and quantity restrictions of the upload control #9613 #9598
  web/src/app.tsx
  web/src/components/file-upload-dialog/index.tsx
  web/src/components/file-uploader.tsx
  web/src/pages/agent/upload-agent-dialog/upload-agent-form.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/profile-setting/mcp/import-mcp-dialog/import-mcp-form.tsx
Labels: 🐞 bug, ci, size:S

#9620 Fix (style): Optimized Datasets color scheme and layout #3221
  web/src/components/ui/progress.tsx
  web/src/pages/dataset/dataset/constant.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/parsing-card.tsx
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/home/datasets.tsx
  web/src/pages/next-search/index.tsx
Labels: 🐞 bug, ci, size:M

#9633 Feat: Allow users to parse documents directly after uploading files #3221
  web/src/components/file-upload-dialog/index.tsx
  web/src/hooks/use-document-request.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-upload-document.ts
  web/src/pages/datasets/dataset-creating-dialog.tsx
  web/src/pages/files/use-upload-file.ts
Labels: 💞 feature, ci, size:L

#9628 Chore: Update infinity-sdk from 0.6.0.dev4 to 0.6.0.dev5
  pyproject.toml
  uv.lock
Labels: ci, ♾️infinity, size:XS, lgtm

#9642 Fix: Fixed an issue where knowledge base could not be shared #9634
  web/src/components/home-card.tsx
  web/src/components/ragflow-form.tsx
  web/src/components/shared-badge.tsx
  web/src/constants/permission.ts
  web/src/pages/dataset/setting/general-form.tsx
  web/src/pages/dataset/setting/index.tsx
  web/src/pages/datasets/dataset-card.tsx
Labels: 🐞 bug, ci, size:M

#9640 fix(sdk): add default empty dict for metadata_condition
  api/apps/sdk/dify_retrieval.py
Labels: ci, size:M, 🐖api

#9656 Fix: Document Previewer is not working #9606
  web/src/hooks/use-llm-request.ts
  web/src/hooks/use-user-setting-request.tsx
  web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx
  web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/hooks/use-rename-chat.ts
  web/src/pages/next-chats/hooks/use-send-multiple-message.ts
Labels: 🐞 bug, ci, size:XL

#9671 Fix: code executor timeout
  agent/tools/code_exec.py
  sandbox/executor_manager/core/config.py
Labels: 🐞 bug, ci, size:XS

#9661 Fix: unexpected LLM parameters
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:S

#9670 Fix: meta data error.
  graphrag/general/index.py
  rag/prompts/prompts.py
Labels: 🐞 bug, ci, size:XS

#9677 Fix: Wrap VersionDialog in DropdownProvider for proper context
  web/src/pages/agent/index.tsx
Labels: 🐞 bug, ci, size:XS

#9692 Feat: Exclude operator_permission field from renaming chat fields #3221
  web/src/app.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/hooks/use-rename-chat.ts
Labels: 💞 feature, ci, size:S

#9674 Fix: grow reference list
  api/db/services/canvas_service.py
Labels: 🐞 bug, ci, size:XS

#9666 fix: Create conversation sessions will lost prologue
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:S, 🐖api

#9693 Refa: replace Chat Ollama implementation with LiteLLM
  rag/llm/__init__.py
  rag/llm/chat_model.py
Labels: ci, ☯️ refactor, size:M

#9687 Fix: meta data filter with AND logic operations.
  api/db/services/dialog_service.py
  api/utils/api_utils.py
  graphrag/entity_resolution.py
  graphrag/general/community_reports_extractor.py
  graphrag/general/index.py
  graphrag/utils.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:M

#9702 Fix: Delete the uploaded file in the chat input box, the corresponding file ID is not deleted #9701
  web/src/components/message-input/next.tsx
  web/src/hooks/use-agent-request.ts
  web/src/hooks/use-chat-request.ts
  web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx
  web/src/pages/next-chats/hooks/use-send-chat-message.ts
  web/src/pages/next-chats/hooks/use-upload-file.ts
Labels: 🐞 bug, ci, size:L

#9703 Fix: Optimize table style #3221
  web/src/components/ui/table.tsx
  web/src/locales/en.ts
  web/src/pages/dataset/dataset/dataset-action-cell.tsx
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/files-table.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 🐞 bug, ci, size:L

#9707 Refactor: for total_token_count method use if to check first.
  rag/llm/rerank_model.py
Labels: ci, ☯️ refactor, size:S

#9711 Fix: Chunk error when re-parsing created file #9665
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
Labels: 🐞 bug, ci, size:M

#9714 Update llm_factories.json
  conf/llm_factories.json
Labels: 💞 feature, size:M

#9715 Feat: add Zhipu GLM-4.5 model series
  conf/llm_factories.json
Labels: 💞 feature, ci, size:M

#9717 Fix: Try to fix the issue of not being able to log in through Oauth2 #9601
  web/src/hooks/auth-hooks.ts
  web/src/routes.ts
Labels: 🐞 bug, ci, size:XS

#9727 Fix(i18n): Added new translations #3221
  web/src/components/large-model-form-field.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/components/table-skeleton.tsx
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/agent-tools.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/parameter-dialog.tsx
  web/src/pages/agent/form/begin-form/query-table.tsx
  web/src/pages/agent/form/components/api-key-field.tsx
  web/src/pages/agent/form/components/description-field.tsx
  web/src/pages/agent/form/components/output.tsx
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/form/exesql-form/index.tsx
  web/src/pages/agent/form/google-form/index.tsx
  web/src/pages/agent/form/invoke-form/variable-dialog.tsx
  web/src/pages/agent/form/invoke-form/variable-table.tsx
  web/src/pages/agent/form/iteration-form/dynamic-output.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/string-transform-form/index.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/tavily-extract-form/index.tsx
  web/src/pages/agent/form/tavily-form/dynamic-domain.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
  web/src/pages/agent/form/user-fill-up-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/agents/index.tsx
  web/src/utils/form.ts
Labels: 🐞 bug, ci, size:L

#9729 Docs: Miscellaneous updates
  api/utils/api_utils.py
  docs/develop/acquire_ragflow_api_key.md
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  docs/release_notes.md
  web/src/locales/en.ts
Labels: 📖 documentation, size:S

#9675 Feat: Upgrade html parser
  deepdoc/parser/html_parser.py
  rag/app/naive.py
Labels: ci, size:L

#9758 Docs: Update version references to v0.20.4 in READMEs and docs
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/develop/build_docker_image.mdx
  docs/faq.mdx
  docs/guides/agent/agent_component_reference/agent.mdx
  docs/guides/agent/agent_component_reference/retrieval.mdx
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/tracing.mdx
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/references/glossary.mdx
  helm/values.yaml
  pyproject.toml
  sdk/python/pyproject.toml
  sdk/python/uv.lock
  uv.lock
Labels: 📖 documentation, size:L

#9766 Fix typo
  api/apps/chunk_app.py
  api/apps/dialog_app.py
  api/apps/llm_app.py
  api/apps/mcp_server_app.py
  api/apps/search_app.py
  deepdoc/vision/seeit.py
  rag/nlp/__init__.py
  rag/utils/mcp_tool_call_conn.py
  rag/utils/redis_conn.py
Labels: ci, ☯️ refactor, size:M

#9735 Refactor: Improve the try logic for upload_to_minio
  rag/svr/task_executor.py
Labels: ci, ☯️ refactor, size:XS

#9773 add Russian in translation table index.tsx
  web/src/pages/user-setting/setting-locale/index.tsx
Labels: 🧰 typescript, size:XS

#9749 Clarify installation of pre-commit alongside uv in README
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:S

#9777 Feat: Add AvatarUpload component #3221
  web/src/components/avatar-upload.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
Labels: 💞 feature, ci, size:M

#9746 The agent directly outputs the results under the task model #9745
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/agent/hooks/use-send-shared-message.ts
  web/src/pages/agent/interface.ts
  web/src/pages/agent/share/index.tsx
Labels: 💞 feature, ci, size:L

#9762 Improve model tag rendering by splitting comma-separated string into styled <Tag> components
  web/src/pages/user-setting/setting-model/index.tsx
Labels: 💞 feature, ci, size:M

#9784 Fix: agent template error.
  agent/templates/ecommerce_customer_service_workflow.json
  agent/templates/trip_planner.json
Labels: 🐞 bug, ci, size:S

#9792 Refa: unify reference format of agent completion and OpenAI-compatible completion API
  api/apps/sdk/session.py
  api/db/services/canvas_service.py
  docs/references/http_api_reference.md
Labels: 🐞 bug, 📖 documentation, ci, ☯️ refactor, size:L, 🐖api

#9794 Fix: Fixed the issue where the thinking mode on the chat page could not be turned off #9789
  web/src/components/llm-setting-items/next.tsx
  web/src/components/message-item/index.less
  web/src/interfaces/database/chat.ts
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-chats/chat/sessions.tsx
Labels: 🐞 bug, ci, size:M

#9815 Fix: Optimized Input and MultiSelect component functionality and dataSet-chunk page styling #9779
  web/package-lock.json
  web/package.json
  web/src/components/edit-tag/index.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/components/ui/input.tsx
  web/src/components/ui/multi-select.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/checkbox-sets.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
Labels: 🐞 bug, ci, size:L

#9821 Fix: Fixed the issue that similarity threshold modification in chat and search configuration failed #3221
  web/src/pages/next-chats/chat/app-settings/chat-settings.tsx
  web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx
  web/src/pages/next-search/search-setting.tsx
Labels: 🐞 bug, ci, size:S

#9699 Feat: add SearXNG search tool to Agent (frontend + backend, i18n)
  agent/tools/searxng.py
  web/src/assets/svg/searxng.svg
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/fr.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/ru.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/form-config-map.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/searxng-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/searxng-form/index.tsx
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
  web/src/pages/agent/operator-icon.tsx
Labels: 💞 feature, 🌈 python, ci, size:L

#9824 Fix: Optimized the style and functionality of multiple components #3221
  web/src/components/skeleton-card.tsx
  web/src/components/ui/select.tsx
  web/src/components/ui/tooltip.tsx
  web/src/pages/dataset/testing/index.tsx
  web/src/pages/dataset/testing/testing-result.tsx
  web/src/pages/next-search/search-view.tsx
  web/src/pages/next-search/spotlight.tsx
Labels: 🐞 bug, ci

#9828 Refa: revise the implementation of LightRAG and enable response caching
  conf/llm_factories.json
  graphrag/general/extractor.py
  graphrag/general/index.py
  graphrag/light/__init__.py
  graphrag/light/graph_extractor.py
  graphrag/light/graph_prompt.py
  graphrag/utils.py
  rag/llm/chat_model.py
  sandbox/executor_manager/services/execution.py
Labels: 🐞 bug, ci, ☯️ refactor, size:XL
