Repository infiniflow/ragflow, pull requests merged in 2025-06, with the labels that each got.

#7997 Update synonym dictionary file
  rag/res/synonym.json
Labels: ☯️ refactor, size:XS

#8013 Fix: url path join issue.
  rag/llm/chat_model.py
  rag/llm/cv_model.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
Labels: 🐞 bug, ci, size:M

#8015 Feat: sync test group to top pyproject.toml
  pyproject.toml
  uv.lock
Labels: 💞 feature, 🌈 python, ci, size:S

#8012 Feat: Construct RetrievalForm with original fields #3221
  web/src/components/rerank.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/categorize-form/dynamic-example.tsx
  web/src/pages/agent/form/categorize-form/index.tsx
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8021 Fix: no kb selected for an assistant.
  api/apps/dialog_app.py
Labels: 🐞 bug, ci, size:M

#8023 Fix: Grammar and clarity improvements in prompt templates
  rag/prompts.py
Labels: ci, size:M

#8037 Fix: /v1/conversation/completion KeyError: 'conversation_id'
  api/apps/conversation_app.py
Labels: 🐞 bug, ci, size:XS

#8042 Refa: Move HTTP API tests to top-level test directory
  pyproject.toml
  test/configs.py
  test/conftest.py
  test/libs/__init__.py
  test/libs/auth.py
  test/testcases/test_http_api/common.py
  test/testcases/test_http_api/conftest.py
  test/testcases/test_http_api/test_chat_assistant_management/conftest.py
  test/testcases/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  test/testcases/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  test/testcases/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py
  test/testcases/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/conftest.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  test/testcases/test_http_api/test_dataset_mangement/conftest.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_http_api/test_file_management_within_dataset/conftest.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_download_document.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  test/testcases/test_http_api/test_session_management/conftest.py
  test/testcases/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
  test/utils/__init__.py
  test/utils/file_utils.py
  test/utils/hypothesis_utils.py
Labels: ci, ☯️ refactor, size:XXL

#8041 Fix: Allow None value for parser_config in create_dataset SDK method
  sdk/python/ragflow_sdk/ragflow.py
Labels: 🐞 bug, ci, size:S

#8045 Feat: Add RunSheet component #3221
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/chat/chat-sheet.tsx
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/debug-content/popover-form.tsx
  web/src/pages/agent/index.tsx
  web/src/pages/agent/run-sheet/index.tsx
Labels: 💞 feature, ci, size:XL

#8047 Fix: data missing after upgrading.
  docker/docker-compose.yml
Labels: 🐞 bug, ci

#8058 Fix: DataSet.update() now refreshes object data
  api/apps/sdk/dataset.py
  sdk/python/ragflow_sdk/modules/base.py
  sdk/python/ragflow_sdk/modules/dataset.py
Labels: 🐞 bug, ci, size:M

#8063 Don't use '，' (U+FF0C) but ', ' (U+2C U+20)
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/session.py
  web/src/interfaces/request/base.ts
Labels: 🐞 bug, 📖 documentation, size:S

#8069 Update api_utils.py
  api/utils/api_utils.py
Labels: 🐞 bug, ci, size:XS

#7998 Fix: Authentication Bypass via predictable JWT secret and empty token validation
  api/apps/__init__.py
  api/apps/user_app.py
  api/db/services/user_service.py
  api/settings.py
Labels: 🐞 bug, ci, size:M

#8064 Fix: set output for Message template
  agent/component/message.py
Labels: 🐞 bug, ci, size:XS

#8080 Feat: Solved the problem that BeginForm would get stuck when modifying data #3221
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/begin-form/use-edit-query.ts
  web/src/pages/agent/form/begin-form/use-values.ts
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8078 Fix:when stream=false，new message without sessionid does no
  api/db/services/conversation_service.py
Labels: 🐞 bug, ci, size:S

#8084 Fix: Resolve JSON download errors in Document.download()
  sdk/python/ragflow_sdk/modules/document.py
Labels: 🐞 bug, ci, size:XS

#8090 Fix(python-sdk): Add name filtering support to Dataset.list_documents()
  sdk/python/ragflow_sdk/modules/dataset.py
Labels: 🐞 bug, 🌈 python, ci, size:XS

#8094 Test: add sdk Document test cases
  sdk/python/ragflow_sdk/modules/document.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_http_api/test_file_management_within_dataset/conftest.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  test/testcases/test_sdk_api/common.py
  test/testcases/test_sdk_api/conftest.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/conftest.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_delete_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_download_document.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_stop_parse_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_upload_documents.py
Labels: ci, size:XXL, 🧪 test

#8093 Docs: Updated server launching code
  docs/develop/mcp/launch_mcp_server.md
Labels: 📖 documentation, size:XS

#8095 Fix:Unimplemented function in ppt_parser
  deepdoc/parser/ppt_parser.py
Labels: 🐞 bug, ci, size:XS

#7330 fix: single task executor getting all tasks from Redis queue
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#8102 task_limiter with trio.Semaphore
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#8100 Feat: Receive reply messages of different event types from the agent #3221
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/chat-sheet.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/form-sheet/next.tsx
Labels: 💞 feature, ci, size:L

#8108 Feat: Enables the message operator form to reference the data defined by the begin operator #3221
  web/src/components/llm-setting-items/use-watch-change.ts
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/agent/canvas/node/popover.tsx
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/context.ts
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/agent-form/dynamic-prompt.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/begin-form/use-values.ts
  web/src/pages/agent/form/begin-form/utils.ts
  web/src/pages/agent/form/components/output.tsx
  web/src/pages/agent/form/components/prompt-editor/constant.ts
  web/src/pages/agent/form/components/prompt-editor/index.css
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/components/prompt-editor/theme.ts
  web/src/pages/agent/form/components/prompt-editor/variable-node.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-on-change-plugin.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx
  web/src/pages/agent/form/generate-form/index.tsx
  web/src/pages/agent/form/message-form/index.tsx
  web/src/pages/agent/form/template-form/index.tsx
  web/src/pages/agent/hooks/use-build-dsl.ts
  web/src/pages/agent/hooks/use-export-json.ts
  web/src/pages/agent/hooks/use-fetch-data.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/agent/hooks/use-save-graph.ts
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, 🧰 typescript, size:XL

#8112 Test: Refactor test concurrency handling and add SDK chunk management tests
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  test/testcases/test_sdk_api/common.py
  test/testcases/test_sdk_api/conftest.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/conftest.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_add_chunk.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_delete_chunks.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_update_chunk.py
Labels: ci, ☯️ refactor, size:XXL, 🧪 test

#8123 Fix task_limiter in raptor.py
  rag/raptor.py
Labels: 🐞 bug, ci, size:XS

#8130 Fix: Set default rerank_model to empty string in Chat class
  sdk/python/ragflow_sdk/modules/chat.py
Labels: 🐞 bug, 🌈 python, ci, size:XS

#8125 Fix: chat module update LLM defaults
  sdk/python/ragflow_sdk/modules/chat.py
Labels: 🐞 bug, ci, size:S

#8121 Perf: pass useless check for tidy graph
  graphrag/general/index.py
  graphrag/utils.py
Labels: ci, size:S

#8132 Refa: dataset operations to simplify error handling
  api/apps/sdk/dataset.py
Labels: ci, ☯️ refactor, size:L

#8131 Test: Add SDK API tests for chat assistant management and improve con…
  test/testcases/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  test/testcases/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py
  test/testcases/test_sdk_api/common.py
  test/testcases/test_sdk_api/conftest.py
  test/testcases/test_sdk_api/test_chat_assistant_management/conftest.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_create_chat_assistant.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_delete_chat_assistants.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_list_chat_assistants.py
  test/testcases/test_sdk_api/test_chat_assistant_management/test_update_chat_assistant.py
Labels: ci, size:XL, 🧪 test

#8133 Fix: presentation of PDF using vlm.
  rag/app/presentation.py
Labels: 🐞 bug, ci, size:S

#8137 Feat: Convert the prompt field of the agent operator to an array #3221
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/form/agent-form/constant.ts
  web/src/pages/agent/form/agent-form/dynamic-prompt.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/use-values.ts
  web/src/pages/agent/form/agent-form/use-watch-change.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
Labels: 💞 feature, ci, size:L

#8140 Feat: Display chat content on the agent page #3221
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/retrieval-form/use-values.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
Labels: 💞 feature, ci, size:L

#8141 Test: Refactor test fixtures and add SDK session management tests
  test/testcases/test_http_api/conftest.py
  test/testcases/test_http_api/test_chat_assistant_management/conftest.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/conftest.py
  test/testcases/test_http_api/test_file_management_within_dataset/conftest.py
  test/testcases/test_http_api/test_session_management/conftest.py
  test/testcases/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
  test/testcases/test_sdk_api/common.py
  test/testcases/test_sdk_api/conftest.py
  test/testcases/test_sdk_api/test_chat_assistant_management/conftest.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/conftest.py
  test/testcases/test_sdk_api/test_session_management/conftest.py
  test/testcases/test_sdk_api/test_session_management/test_create_session_with_chat_assistant.py
  test/testcases/test_sdk_api/test_session_management/test_delete_sessions_with_chat_assistant.py
  test/testcases/test_sdk_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_sdk_api/test_session_management/test_update_session_with_chat_assistant.py
Labels: ci, ☯️ refactor, size:XL, 🧪 test

#8144 Feat: Add agent operator node from agent form #3221
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/context.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8136 Fix: use jwks_uri from OIDC metadata for JWKS client
  api/apps/auth/oidc.py
Labels: 🐞 bug, ci, size:XS

#8152 Feat: Constructing query parameter options for the Retrieval operator #3221
  web/src/components/originui/select-with-search.tsx
  web/src/interfaces/database/flow.ts
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8145 Test: Migrate test workflow to use top-level test directory
  .github/workflows/tests.yml
Labels: ci, size:S, 🧪 test

#8170 Docs: UI updates
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, ci, size:S

#8167 Improve image rotation logic for text recognition
  deepdoc/vision/ocr.py
Labels: 🐞 bug, ci, size:S

#8169 Feat: Display agent operator call log #3221
  web/package-lock.json
  web/package.json
  web/src/components/next-message-item/feedback-modal.tsx
  web/src/components/next-message-item/group-button.tsx
  web/src/components/next-message-item/hooks.ts
  web/src/components/next-message-item/index.less
  web/src/components/next-message-item/index.tsx
  web/src/components/next-message-item/prompt-modal.tsx
  web/src/components/ui/accordion.tsx
  web/src/components/ui/toggle-group.tsx
  web/src/components/ui/toggle.tsx
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/chat-sheet.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/context.ts
  web/src/pages/agent/hooks/use-cache-chat-log.ts
  web/src/pages/agent/hooks/use-show-drawer.tsx
  web/src/pages/agent/log-sheet/index.tsx
  web/src/pages/demo.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, 🧰 typescript, size:XXL

#8185 Feat: Display the agent node running timeline #3221
  web/src/components/originui/timeline.tsx
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/chat/chat-sheet.tsx
  web/src/pages/agent/log-sheet/data.ts
  web/src/pages/agent/log-sheet/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:XL

#8188 Fix: Improve dataset name validation in KB app
  api/apps/kb_app.py
Labels: 🐞 bug, ci, size:XS

#8200 Feat: Add SwitchForm component #3221
  web/public/iconfont.js
  web/src/pages/agent/form/code-form/dynamic-input-variable.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
  web/src/pages/agent/form/components/dynamic-input-variable.tsx
  web/src/pages/agent/form/components/next-dynamic-input-variable.tsx
  web/src/pages/agent/form/invoke-form/dynamic-variables.tsx
  web/src/pages/agent/form/switch-form/index.less
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/switch-form/use-values.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
Labels: 💞 feature, size:XL

#8190 Fix: auto-keyword and auto-question fail with qwq model
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:M

#8210 Refa: chat with tools.
  rag/llm/chat_model.py
  rag/prompts.py
Labels: ci, ☯️ refactor, size:L

#8172 Fix: Improve TS Warning For http_api_reference.md
  web/src/custom.d.ts
Labels: 🐞 bug, ci, 🧰 typescript, size:XS

#8215 Fix: Add pagerank validation for non-elasticsearch doc engines
  api/apps/kb_app.py
Labels: 🐞 bug, ci, size:XS

#8220 Refa: Test configs
  test/testcases/test_http_api/common.py
  test/testcases/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  test/testcases/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  test/testcases/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py
  test/testcases/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_download_document.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  test/testcases/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
Labels: ci, ☯️ refactor, size:M, 🧪 test

#8223 Refa: GraphRAG and explaining GraphRAG stalling behavior on large files
  graphrag/entity_resolution.py
  graphrag/general/community_reports_extractor.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:L

#8177 Fix：The OpenAI-Compatible Agent API returns an incorrect message
  agent/canvas.py
  agent/component/answer.py
  agent/component/base.py
  api/db/services/canvas_service.py
Labels: 🐞 bug, ci, size:M

#8231 Feat: Connect conditional operators to other operators #3221
  web/src/interfaces/database/agent.ts
  web/src/interfaces/database/flow.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/switch-form/use-values.ts
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/agent/store.ts
Labels: 💞 feature, ci, size:L

#8237 Docs: Miscellaneous editorial updates
  docs/guides/dataset/autokeyword_autoquestion.mdx
  docs/guides/dataset/use_tag_sets.md
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:S

#8238 Fix: Update customer_service.json
  agent/templates/customer_service.json
Labels: 🐞 bug, ci, size:S

#8232 Fix: unify opendal config key from ‎`schema` to ‎`scheme`
  conf/service_conf.yaml
  rag/utils/opendal_conn.py
Labels: 🐞 bug, ci, size:S

#8250 Feat: implement novitaAI embedding and reranking.
  rag/llm/__init__.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
Labels: 💞 feature, ci, size:S

#8249 Feat: Add canvas node toolbar #3221
  web/src/components/xyflow/base-node.tsx
  web/src/components/xyflow/tooltip-node.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/hooks.ts
  web/src/pages/agent/canvas/node/node-header.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/operator-icon.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:XL

#8252 Fix: Update customer service template with query references to RewriteQuestion
  agent/templates/customer_service.json
Labels: 🐞 bug, ci, size:S

#8253 Fix: incorrect progress updating
  api/db/services/task_service.py
Labels: 🐞 bug, ci, size:M

#8258 Refa: Translate test file content from Chinese to English in file_utils.py
  test/utils/file_utils.py
Labels: ci, size:S, 🧪 test

#8259 Feat: Let number of task ahead be visible.
  api/apps/document_app.py
  api/db/services/document_service.py
Labels: 💞 feature, ci, size:S

#8262 Feat: Reset the default values ​​of large model parameters
  web/src/components/llm-setting-items/index.tsx
  web/src/constants/knowledge.ts
  web/src/utils/chat.ts
Labels: 💞 feature, 🧰 typescript, size:M

#8264 Docs: Sandbox quickstart
  docs/guides/agent/sandbox_quickstart.md
Labels: 📖 documentation, size:L

#8276 Refa: Structure Ask Message
  sdk/python/ragflow_sdk/modules/session.py
Labels: ci, ☯️ refactor, size:M

#8260 Fix: avoid mixing different embedding models in document parsing
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:XS

#8293 Docs: add authorization header for MCP server based on OAuth 2.1
  docs/develop/mcp/mcp_client_example.md
Labels: 📖 documentation, size:XS

#8288 Feat: Use the node ID as the key to destroy different types of form components to switch the form values ​​of the same type of operators #3221
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/interface.ts
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8304 Update readme
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, ci

#8299 Feat: Modify the anchor point positioning of the classification operator node #3221
  web/src/pages/agent/canvas/node/categorize-node.tsx
  web/src/pages/agent/canvas/node/node-wrapper.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/canvas/node/use-build-categorize-handle-positions.ts
  web/src/pages/agent/canvas/node/use-build-switch-handle-positions.ts
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/switch-form/use-watch-change.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8292 Feat: add authorization header for MCP server based on OAuth 2.1
  mcp/client/client.py
  mcp/server/server.py
Labels: 💞 feature, ci, size:L

#8309 Feat: Add a child operator node by clicking the operator node anchor point #3221
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/begin-node.tsx
  web/src/pages/agent/canvas/node/categorize-node.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/canvas/node/handle.tsx
  web/src/pages/agent/canvas/node/index.tsx
  web/src/pages/agent/canvas/node/logic-node.tsx
  web/src/pages/agent/canvas/node/message-node.tsx
  web/src/pages/agent/canvas/node/retrieval-node.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/context.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, 🧰 typescript, size:XL

#8321 Fix: Add validation for empty filenames in document_app.py
  api/apps/document_app.py
Labels: 🐞 bug, ci, size:XS

#8318 Refa: Implement centralized file name length limit using FILE_NAME_LEN_LIMIT constant
  api/apps/document_app.py
  api/apps/sdk/doc.py
  api/constants.py
  api/db/services/file_service.py
Labels: ci, ☯️ refactor, size:M

#8314 Feat: Add child nodes and their connecting lines by clicking #3221
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/begin-node.tsx
  web/src/pages/agent/canvas/node/categorize-node.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/canvas/node/index.tsx
  web/src/pages/agent/canvas/node/message-node.tsx
  web/src/pages/agent/canvas/node/retrieval-node.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8335 Feat: Add tool nodes and tool drop-down menu #3221
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/tool-node.tsx
  web/src/pages/agent/form/agent-form/dynamic-tool.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/agent-form/use-values.ts
Labels: 💞 feature, ci, size:L

#8348 Fix: illegal variable name in Jinja2
  agent/component/template.py
Labels: 🐞 bug, ci, size:S

#8341 Refactor code
  deepdoc/vision/recognizer.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
  sdk/python/test/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py
  test/testcases/test_sdk_api/test_session_management/test_list_sessions_with_chat_assistant.py
Labels: ci, ☯️ refactor, size:M

#8331 Fix: Raptor: [Bug]: **ERROR**: Unknown field for GenerationConfig: max_tokens
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:XS

#8320 Feat: wrap search app
  api/apps/search_app.py
  api/db/db_models.py
  api/db/services/dialog_service.py
  api/db/services/search_service.py
Labels: 💞 feature, size:L

#8358 Fix: duplicated task
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:M

#8362 Fix: desc parameter parsing
  api/apps/document_app.py
Labels: 🐞 bug, ci, size:XS

#8366 Docs: Update version references to v0.19.1 in READMEs and docs
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/README.md
  docs/configurations.md
  docs/develop/build_docker_image.mdx
  docs/faq.mdx
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/tracing.mdx
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  docs/references/glossary.mdx
  helm/values.yaml
  pyproject.toml
  sdk/python/pyproject.toml
  sdk/python/uv.lock
  uv.lock
Labels: 📖 documentation, size:L

#8377 Feat: Synchronize the data of the tavily form to the canvas node #3221
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/retrieval-form/index.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tavily-form/use-values.ts
  web/src/pages/agent/form/tavily-form/use-watch-change.ts
  web/src/pages/agent/form/tool-form/constant.ts
  web/src/pages/agent/store.ts
  web/src/pages/agent/utils.ts
  web/src/utils/form.ts
Labels: 💞 feature, ci, size:L

#8372 Docs: add curl example for interacting with the RAGFlow MCP server
  docs/develop/mcp/mcp_client_example.md
Labels: 📖 documentation, size:L

#8390 Feat: Improve the tavily form #3221
  web/src/pages/agent/form/components/output.tsx
  web/src/pages/agent/form/tavily-form/dynamic-domain.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tavily-form/use-values.ts
  web/src/pages/agent/form/tavily-form/use-watch-change.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8386 Refa: Pdf 2 Slices page to new style
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/hooks/use-chunk-request.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/tag-feature-item.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/checkbox-sets.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-toolbar/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/document-header.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/hooks.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/constant.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/hooks.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/utils.ts
  web/src/pages/chunk/parsed-result/add-knowledge/constant.ts
  web/src/pages/chunk/parsed-result/add-knowledge/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/index.tsx
  web/src/routes.ts
Labels: ci, ☯️ refactor, size:XXL

#8393 Fix: Fixed the issue where tag content would overflow the container #8392
  web/src/components/edit-tag/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:M

#8400 Feat: Add Tavily operator #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/agent-form/agent-tools.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tavily-form/use-values.ts
  web/src/pages/agent/form/tavily-form/use-watch-change.ts
  web/src/pages/agent/form/tool-form/constant.ts
  web/src/pages/agent/form/tool-form/tavily-form/index.tsx
  web/src/pages/agent/form/tool-form/use-values.ts
  web/src/pages/agent/form/tool-form/use-watch-change.ts
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, size:L

#8416 Fix: rank feature score should be greater than 0.
  rag/prompts.py
Labels: 🐞 bug, ci, size:XS

#8413 Feat: Solved the conflict between the Handle click and drag events of the canvas node #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/canvas/node/handle.tsx
  web/src/pages/agent/canvas/node/message-node.tsx
Labels: 💞 feature, ci, size:M

#8418 Fix: doc_aggs issue.
  rag/nlp/search.py
Labels: 🐞 bug, ci, size:S

#8408 Fix: Database Query Vulnerable to Injection Attacks in rag/utils/opendal_conn.py
  rag/utils/opendal_conn.py
Labels: 🐞 bug, ci, size:XS

#8422 Feat: The delete button is displayed only when the cursor is hovered over the connection line #3221
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/toolbar.tsx
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/store.ts
  web/src/pages/agent/utils.ts
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8401 Feat: Add HTTPS setup instructions and configuration for Nginx
  docker/README.md
  docker/nginx/ragflow.https.conf
Labels: 📖 documentation, ci, size:L

#8426 Fix: AzureChat model code
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:M

#8412 Update .env ,Defaults to the v0.19.1-slim edition
  docker/.env
Labels: ci, size:XS

#8263 Feat: Scratch MCP tool calling support.
  Dockerfile
  Dockerfile.scratch.oc9
  api/apps/mcp_server_app.py
  api/db/__init__.py
  api/db/db_models.py
  api/db/services/mcp_server_service.py
  mcp/server/simple_tools_server.py
  mcp_client/__init__.py
  mcp_client/mcp_tool_call.py
  rag/llm/chat_model.py
  uv.lock
  web/src/interfaces/database/mcp-server.ts
  web/src/services/mcp-server-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:L

#8434 Feat: Use the message_id returned by the interface as the id of the reply message #3221
  web/src/hooks/logic-hooks.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/tool-form/constant.ts
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/utils.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8432 fix a bug when using huggingface embedding api
  rag/llm/embedding_model.py
Labels: 🐞 bug, ci, size:S

#8456 Test: Add document app tests
  test/testcases/test_http_api/common.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  test/testcases/test_web_api/common.py
  test/testcases/test_web_api/conftest.py
  test/testcases/test_web_api/test_document_app/conftest.py
  test/testcases/test_web_api/test_document_app/test_create_document.py
  test/testcases/test_web_api/test_document_app/test_list_documents.py
  test/testcases/test_web_api/test_document_app/test_paser_documents.py
  test/testcases/test_web_api/test_document_app/test_rm_documents.py
  test/testcases/test_web_api/test_document_app/test_upload_documents.py
Labels: ci, size:XXL, 🧪 test

#8399 FIX:Saving an RGBA image directly as JPEG will cause an error. If the…
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#8461 Feat: Add IterationNode component #3221
  web/src/pages/agent/canvas/index.less
  web/src/pages/agent/canvas/node/iteration-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/form/iteration-form/index.tsx
  web/src/pages/agent/form/iteration-form/use-values.ts
  web/src/pages/agent/form/iteration-from/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8465 Docs: exporting created knowledge graphs is not supported
  docs/guides/dataset/construct_knowledge_graph.md
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:S

#8460 Feat: add MCP dashboard operations
  api/apps/mcp_server_app.py
  api/apps/search_app.py
  api/db/__init__.py
  api/db/db_models.py
  api/db/services/mcp_server_service.py
  api/utils/web_utils.py
  mcp/server/simple_tools_server.py
Labels: 💞 feature, ci, size:L

#8449 Feat: add MCP treamable-http transport
  mcp/client/streamable_http_client.py
  mcp/server/server.py
Labels: 💞 feature, ci, size:L

#8464 Fix: Solve the OOM issue when passing large PDF files while using QA chunking method.
  rag/app/qa.py
Labels: 🐞 bug, ci, size:XS

#8470 helm add oidc configuration
  helm/templates/env.yaml
  helm/templates/ragflow.yaml
  helm/templates/ragflow_config.yaml
  helm/values.yaml
Labels: ci, size:L

#8479 Refa: improve GraphRAG similarity sensitivity to numeric differences
  graphrag/entity_resolution.py
  rag/nlp/__init__.py
Labels: ci, ☯️ refactor, size:M

#8485 Feat: Filter the query variable drop-down box options by type #3221
  web/src/components/originui/select-with-search.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/begin-form/use-edit-query.ts
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/form/iteration-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/agent/hooks/use-show-drawer.tsx
  web/src/pages/agent/store.ts
  web/src/pages/flow/constant.tsx
  web/src/pages/flow/form/iteration-start-from/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8473 fix the error 'Unknown field for GenerationConfig: max_tokens' when u…
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:XS

#8478 Adds retrieval result fields to Chunk
  sdk/python/ragflow_sdk/modules/chunk.py
Labels: 💞 feature, ci, size:XS

#8491 Feat: Add retrieval tool #3221
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/agent-form/tool-popover/use-update-tools.ts
  web/src/pages/agent/form/baidu-fanyi-form/index.tsx
  web/src/pages/agent/form/bing-form/index.tsx
  web/src/pages/agent/form/components/description-field.tsx
  web/src/pages/agent/form/crawler-form/index.tsx
  web/src/pages/agent/form/deepl-form/index.tsx
  web/src/pages/agent/form/exesql-form/index.tsx
  web/src/pages/agent/form/google-form/index.tsx
  web/src/pages/agent/form/jin10-form/index.tsx
  web/src/pages/agent/form/qweather-form/index.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/rewrite-question-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.ts
  web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
  web/src/pages/agent/form/tool-form/use-values.ts
  web/src/pages/agent/form/tushare-form/index.tsx
  web/src/pages/agent/form/wencai-form/index.tsx
  web/src/pages/agent/form/wikipedia-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/options.ts
Labels: 💞 feature, ci, 🧰 typescript, size:XXL

#8498 Feat: Allow operators inside the loop operator to reference the output parameters of external operators #3221
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/use-form-config-map.tsx
  web/src/pages/agent/form/iteration-start-from/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/flow/constant.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8505 Feat: add MCP dashboard functionalities list_tools and test_tool
  api/apps/mcp_server_app.py
  api/ragflow_server.py
  api/utils/web_utils.py
  mcp_client/mcp_tool_call.py
Labels: 💞 feature, ci, size:L

#8516 Fix: Add input validation to chunk creation endpoint
  api/apps/chunk_app.py
Labels: 🐞 bug, ci, size:S

#8511 fix(prompt-editor): resolve initial cursor position and auto-newline …
  web/src/components/prompt-editor/variable-picker-plugin.tsx
Labels: 🐞 bug, ci, size:XS

#8518 fix: list index out of range
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:XS

#8502 Fix: user_default_llm configuration doesn't work for OpenAI API compatible LLM factory
  api/db/services/llm_service.py
Labels: 🐞 bug, ci, size:S

#8522 Fix memory leaks in PIL image and BytesIO handling during chunk processing
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:M

#8519 Feat: allow users to choose which MCP tools are enabled
  api/apps/mcp_server_app.py
Labels: 💞 feature, ci, size:M

#8530 Feat: Fixed the issue where the prompt menu content was hidden #3221
  web/package-lock.json
  web/package.json
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx
  web/src/pages/agent/form/string-transform-form/use-values.ts
  web/tailwind.config.js
Labels: 💞 feature, ci, size:M

#8539 Feat: Fixed the issue where the begin operator parameters could not be submitted during debugging #3221
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/form/components/query-variable.tsx
  web/src/pages/agent/run-sheet/index.tsx
Labels: 💞 feature, ci, size:M

#8543 Refa: limit embedding concurrency and fix `chat_with_tool`
  rag/llm/chat_model.py
  rag/raptor.py
Labels: 🐞 bug, ci, ☯️ refactor, size:L

#8569 Feat: Allow users to enter text in the middle of a chat #3221
  web/src/components/next-message-item/index.tsx
  web/src/hooks/logic-hooks.ts
  web/src/hooks/use-send-message.ts
  web/src/interfaces/database/chat.ts
  web/src/pages/agent/canvas/node/begin-node.tsx
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/chat/input-form.tsx
  web/src/pages/agent/form/begin-form/use-edit-query.ts
  web/src/pages/agent/form/begin-form/use-watch-change.ts
  web/src/pages/agent/form/iteration-form/use-watch-form-change.ts
  web/src/pages/agent/form/user-fill-up-form/use-watch-change.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8573 Feat: Support GiteeAI model #1853
  web/src/assets/svg/llm/gitee-ai.svg
  web/src/constants/llm.ts
Labels: 💞 feature, ci, 🧰 typescript, size:XS

#8579 Feat: Fixed the issue that the top toolbar disappears when opening the agent operator form #3221
  web/src/app.tsx
  web/src/pages/agent/canvas/index.less
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/index.tsx
Labels: 💞 feature, ci, size:S

#8526 Adding semaphore usage on the '/run' endpoint
  sandbox/executor_manager/api/handlers.py
  sandbox/executor_manager/api/routes.py
  sandbox/executor_manager/core/container.py
  sandbox/executor_manager/requirements.txt
  sandbox/uv.lock
Labels: ci, size:M

#8583 Feat: In a dialog message, users can enter different types of data #3221
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/run-sheet/index.tsx
  web/src/pages/agent/utils.ts
Labels: 💞 feature, ci, size:L
