Repository infiniflow/ragflow, pull requests merged in 2025-09, with the labels that each got.

#9863 Fix: agent second round issue.
  agent/component/llm.py
Labels: 🐞 bug, ci, size:XS

#9864 Fix: Fixed the issue where the agent and chat cards on the home page could not be deleted #3221
  web/src/pages/home/agent-list.tsx
  web/src/pages/home/application-card.tsx
  web/src/pages/home/chat-list.tsx
Labels: 🐞 bug, ci, size:L

#9867 Feat: By default, 50 records are displayed per page. #3221
  web/src/hooks/route-hook.ts
  web/src/pages/next-searches/hooks.ts
  web/src/pages/next-searches/index.tsx
Labels: 💞 feature, ci, size:XS

#9812 Fix JSON serialization error for ModelMetaclass objects
  api/utils/api_utils.py
Labels: 🐞 bug, ci, size:M

#9879 Add jemalloc install instruction for mac
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:S

#9887 Fix: The operator added by clicking the plus sign will overlap with the original operator. #9886
  web/src/constants/agent.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
Labels: 🐞 bug, ci, size:M

#9884 Docs: Updated the Code component reference
  docs/guides/agent/agent_component_reference/code.mdx
  docs/guides/agent/agent_component_reference/retrieval.mdx
Labels: 📖 documentation, size:L

#9885 Feat: add `canvas_category` field for UserCanvas and CanvasTemplate
  api/apps/canvas_app.py
  api/db/__init__.py
  api/db/db_models.py
  api/db/services/canvas_service.py
Labels: 💞 feature, ci, size:M

#9890 Docs: Updated instructions on importing third-party packages to Sandbox
  docs/guides/agent/agent_component_reference/code.mdx
Labels: 📖 documentation, size:M

#9904 Update README
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:S

#9898 Feat: Allow users to enter SQL in the SQL operator #9897
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/exesql-form/index.tsx
Labels: 💞 feature, ci, size:S

#9900 During the chat, the assistant's response cited documents outside current chat's kbs
  api/db/services/dialog_service.py
Labels: ci, size:S

#9920 Feat: Display AvatarUpload and RAGFlowAvatar in Storybook #9914
  web/.eslintrc.js
  web/.storybook/preview.ts
  web/src/stories/avatar-upload.stories.ts
  web/src/stories/ragflow-avatar.stories.ts
  web/src/stories/ragflow-form.stories.tsx
  web/src/stories/ragflow-pagination.stories.ts
  web/src/stories/skeleton-card.stories.ts
Labels: 💞 feature, ci, size:XL

#9908 before docker-compose up, first down it,and cleans.
  .github/workflows/tests.yml
Labels: 🐞 bug, ci, size:XS, lgtm

#9913 Fix kb isolation infinity conn
  rag/utils/infinity_conn.py
Labels: 🐞 bug, ci, ♾️infinity, size:XS, lgtm

#9924 fix: Optimize internationalization configuration #3221
  web/src/components/cross-language-form-field.tsx
  web/src/components/delimiter-form-field.tsx
  web/src/components/indented-tree/indented-tree.tsx
  web/src/components/knowledge-base-item.tsx
  web/src/components/list-filter-bar/filter-popover.tsx
  web/src/components/max-token-number-from-field.tsx
  web/src/components/message-input/next.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/components/ui/form.tsx
  web/src/components/ui/multi-select.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/index.tsx
  web/src/pages/agents/index.tsx
  web/src/pages/agents/template-sidebar.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/dataset/setting/configuration/common-item.tsx
  web/src/pages/dataset/setting/utils.ts
  web/src/pages/dataset/testing/testing-form.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/files/index.tsx
  web/src/pages/home/applications.tsx
  web/src/pages/home/datasets.tsx
  web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx
  web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx
  web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx
  web/src/pages/next-chats/chat/index.tsx
  web/src/pages/next-chats/chat/sessions.tsx
  web/src/pages/next-chats/index.tsx
  web/src/pages/next-search/index.tsx
  web/src/pages/next-search/search-setting.tsx
  web/src/pages/next-search/search-view.tsx
  web/src/pages/next-searches/index.tsx
  web/tailwind.config.js
Labels: 🐞 bug, ci, size:L

#9909 fix xss in excel_parser
  deepdoc/parser/excel_parser.py
Labels: ci, size:XS

#9929 Refactor: Use re compile for weight method
  rag/nlp/term_weight.py
Labels: ci, ☯️ refactor, size:S

#9936 Feat: Allow users to select prompt word templates in agent operators. #9935
  web/src/hooks/use-agent-request.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/use-build-prompt-options.ts
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-node.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-on-change-plugin.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx
  web/src/services/agent-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:L

#9951 Feat: Use sonner to replace the requested prompt message component #3221
  web/src/components/ui/message.ts
  web/src/hooks/file-manager-hooks.ts
  web/src/hooks/login-hooks.ts
  web/src/hooks/use-document-request.ts
  web/src/hooks/use-file-request.ts
  web/src/hooks/user-setting-hooks.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/hooks/use-calculate-sheet-right.ts
  web/src/pages/agent/log-sheet/index.tsx
Labels: 💞 feature, ci, size:M

#9776 Fix miscalculated token count
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:XS

#9958 Refa: import issue.
  api/apps/sdk/dify_retrieval.py
  api/apps/sdk/doc.py
  api/db/services/dialog_service.py
Labels: ci, ☯️ refactor, size:M, 🐖api

#9959 add model: qwen3-max-preview
  conf/llm_factories.json
Labels: ci, size:XS

#9971 Feat: Delete unused code in the data pipeline #9869
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/hooks/use-send-shared-message.ts
  web/src/pages/data-flow/canvas/index.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form-sheet/form-config-map.tsx
  web/src/pages/data-flow/form/akshare-form/index.tsx
  web/src/pages/data-flow/form/arxiv-form/index.tsx
  web/src/pages/data-flow/form/baidu-fanyi-form/index.tsx
  web/src/pages/data-flow/form/baidu-form/index.tsx
  web/src/pages/data-flow/form/bing-form/index.tsx
  web/src/pages/data-flow/form/deepl-form/index.tsx
  web/src/pages/data-flow/form/duckduckgo-form/index.tsx
  web/src/pages/data-flow/form/github-form/index.tsx
  web/src/pages/data-flow/form/google-scholar-form/index.tsx
  web/src/pages/data-flow/form/jin10-form/index.tsx
  web/src/pages/data-flow/form/parser-form/index.tsx
  web/src/pages/data-flow/form/pubmed-form/index.tsx
  web/src/pages/data-flow/form/qweather-form/index.tsx
  web/src/pages/data-flow/form/searxng-form/index.tsx
  web/src/pages/data-flow/form/tavily-extract-form/index.tsx
  web/src/pages/data-flow/form/tavily-form/dynamic-domain.tsx
  web/src/pages/data-flow/form/tavily-form/index.tsx
  web/src/pages/data-flow/form/tavily-form/use-values.ts
  web/src/pages/data-flow/form/tavily-form/use-watch-change.ts
  web/src/pages/data-flow/form/tushare-form/index.tsx
  web/src/pages/data-flow/form/wencai-form/index.tsx
  web/src/pages/data-flow/form/wikipedia-form/index.tsx
  web/src/pages/data-flow/form/yahoo-finance-form/index.tsx
  web/src/pages/data-flow/hooks.tsx
  web/src/pages/data-flow/hooks/use-add-node.ts
  web/src/pages/data-flow/hooks/use-send-shared-message.ts
  web/src/pages/data-flow/share/index.tsx
  web/src/pages/data-flow/share/parameter-dialog.tsx
Labels: ci, ☯️ refactor, size:XXL

#9978 Fix: Update the pagination prompt text in zh.ts, changing "page" to "item/page" #3221
  web/src/components/ui/ragflow-pagination.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
Labels: 🐞 bug, ci, size:S

#9982 Feat: The agent's external page should be able to fill in the begin parameter after being reset in task mode #9745
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/hooks/use-send-shared-message.ts
  web/src/pages/agent/share/index.tsx
  web/src/pages/data-flow/canvas/index.tsx
  web/src/pages/data-flow/canvas/node/chunker-node.tsx
  web/src/pages/data-flow/canvas/node/parser-node.tsx
  web/src/pages/data-flow/canvas/node/tokenizer-node.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/hooks.tsx
  web/src/pages/data-flow/hooks/use-add-node.ts
  web/src/pages/data-flow/hooks/use-agent-tool-initial-values.ts
  web/src/pages/data-flow/index.tsx
  web/src/pages/data-flow/operator-icon.tsx
Labels: ci, size:XXL

#9985 Fix: re sub error.
  agent/component/llm.py
  api/utils/api_utils.py
Labels: 🐞 bug, ci, size:XS

#9989 Fix: Issue of ineffective weight adjustment for retrieval_test API-related functions #9854
  web/src/interfaces/request/knowledge.ts
  web/src/pages/dataset/testing/testing-form.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:S

#9994 Fix: Highlight the edges after running #9538
  web/src/components/llm-setting-items/next.tsx
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/agent/share/index.tsx
  web/src/pages/next-search/search-setting-aisummery-config.tsx
Labels: 🐞 bug, ci, size:M

#10002 Fix: Optimize search functionality #3221
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/next-search/hooks.ts
  web/src/pages/next-search/index.tsx
  web/src/pages/next-search/search-home.tsx
  web/src/pages/next-search/share/index.tsx
Labels: 🐞 bug, ci, size:S

#10001 Feat: The prompt words "plan" are displayed only when the agent operator has sub-agent operators or sub-tool operators. #10000
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/use-build-prompt-options.ts
  web/src/pages/agent/utils.ts
  web/src/pages/agents/agent-card.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#10006 Docs: v0.20.5 - Added Framework prompt block documentation for the Agent component
  docs/guides/agent/agent_component_reference/agent.mdx
Labels: 📖 documentation, size:M

#10010 Feat: Translate the maxRounds field of the chat settings #3221
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx
  web/src/pages/next-chats/hooks/use-rename-chat.ts
Labels: ci, 🧰 typescript, size:M

#10011 Fix: typo.
  rag/prompts/next_step.md
  rag/prompts/prompts.py
Labels: ci, ☯️ refactor, size:XS

#10014 Docs: Added v0.20.5 release notes.
  docs/release_notes.md
Labels: 📖 documentation, size:S

#10003 Feat: dataflow supports markdown
  rag/flow/parser/parser.py
  rag/flow/tests/dsl_examples/general_pdf_all.json
Labels: 💞 feature, ci, size:M

#10025 Feat: Add type card to create agent dialog #9869
  web/src/components/ragflow-form.tsx
  web/src/components/ui/dialog.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agents/agent-templates.tsx
  web/src/pages/agents/create-agent-dialog.tsx
  web/src/pages/agents/create-agent-form.tsx
  web/src/pages/agents/index.tsx
Labels: ci, size:L

#10079 Feat: Translate the fields of the parsing operator #9869
  web/src/components/llm-setting-items/llm-form-field.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form/parser-form/common-form-fields.tsx
  web/src/pages/data-flow/form/parser-form/email-form-fields.tsx
  web/src/pages/data-flow/form/parser-form/index.tsx
  web/src/pages/data-flow/form/parser-form/pdf-form-fields.tsx
Labels: ci, size:M

#10099 Fix: judge not empty before delete
  deepdoc/vision/ocr.py
  deepdoc/vision/recognizer.py
Labels: 🐞 bug, ci, size:XS

#10109 Fix(agent template): wrap template variables in curly braces
  agent/templates/sql_assistant.json
Labels: 🐞 bug, ci, size:M

#10115 Feat: Add splitter form #9869
  web/src/pages/data-flow/canvas/index.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form-sheet/form-config-map.tsx
  web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx
  web/src/pages/data-flow/form/splitter-form/index.tsx
Labels: 💞 feature, ci, size:L

#10067 Docs: Removed `/v1` from Ollama base URLs
  docs/guides/chat/start_chat.md
  docs/guides/models/deploy_local_llm.mdx
Labels: 📖 documentation, size:XS

#10138 Feat: Add SliderInputFormField story #9869
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/data-flow/hooks/use-show-drawer.tsx
  web/src/pages/data-flow/run-sheet/index.tsx
  web/src/pages/data-flow/run-sheet/uploader.tsx
  web/src/stories/slider-input-form-field.stories.tsx
Labels: ci, size:L

#10133 Feat: parse audio
  deepdoc/parser/pdf_parser.py
  rag/flow/parser/parser.py
  rag/flow/tests/dsl_examples/general_pdf_all.json
  rag/llm/sequence2txt_model.py
Labels: 🐞 bug, 💞 feature, ci, size:M

#10132 feat(dataset): Added data pipeline configuration functionality #9869
  web/public/iconfont.js
  web/src/components/data-pipeline-select/index.tsx
  web/src/components/entity-types-form-field.tsx
  web/src/components/home-card.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/components/parse-configuration/graph-rag-form-fields.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/components/slider-input-form-field.tsx
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/hooks/use-agent-request.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/interfaces/database/agent.ts
  web/src/pages/dataset/dataset-setting/components/link-data-pipeline.tsx
  web/src/pages/dataset/dataset-setting/components/link-data-pipline-modal.tsx
  web/src/pages/dataset/dataset-setting/configuration-form-container.tsx
  web/src/pages/dataset/dataset-setting/configuration/common-item.tsx
  web/src/pages/dataset/dataset-setting/form-schema.ts
  web/src/pages/dataset/dataset-setting/general-form.tsx
  web/src/pages/dataset/dataset-setting/hooks.ts
  web/src/pages/dataset/dataset-setting/index.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/datasets/dataset-creating-dialog.tsx
  web/src/pages/datasets/hooks.ts
  web/src/services/agent-service.ts
  web/src/utils/component-util.ts
Labels: 💞 feature, ci, size:XL

#10139 Support image recognition for url links in Markdown file, fix log error in code_exec
  agent/tools/code_exec.py
  api/apps/HEALTHCHECK_TESTING.md
  api/apps/system_app.py
  api/utils/health.py
  rag/app/naive.py
Labels: 🐞 bug, 💞 feature, ci, size:L

#10128 Correct the text of `vectorSimilarityWeight` in zh.ts
  web/src/locales/zh.ts
Labels: size:XS

#10113 Docs: Updated database types supported by the Execute SQL tool
  docs/guides/agent/agent_component_reference/execute_sql.md
Labels: 📖 documentation, size:XS

#10119 Feat: add CometAPI to LLMFactory and update related mappings
  conf/llm_factories.json
  docs/references/supported_models.mdx
  rag/llm/chat_model.py
  rag/llm/embedding_model.py
  rag/llm/sequence2txt_model.py
  rag/llm/tts_model.py
  web/src/assets/svg/llm/cometapi.svg
  web/src/constants/llm.ts
  web/src/utils/common-util.ts
Labels: 📖 documentation, 💞 feature, ci, size:L

#10134 Feat: add support for KB document basic info
  api/apps/kb_app.py
  api/db/services/document_service.py
Labels: 💞 feature, ci, size:M

#10153 Feat: Upload files on the data flow page #9869
  web/src/components/ragflow-form.tsx
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/debug-content/uploader.tsx
  web/src/pages/agent/run-sheet/index.tsx
  web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx
  web/src/pages/data-flow/hooks/use-run-dataflow.ts
  web/src/pages/data-flow/hooks/use-save-graph.ts
  web/src/pages/data-flow/run-sheet/index.tsx
  web/src/pages/data-flow/run-sheet/uploader.tsx
Labels: 💞 feature, ci, size:L

#10148 Feat: migrate OpenAI-compatible chats to LiteLLM
  rag/llm/__init__.py
  rag/llm/chat_model.py
Labels: 🌈 python, ci, size:L

#10159 Fix: Updated color parsing functions and optimized component logic.
  web/src/components/originui/timeline.tsx
  web/src/components/ui/modal/modal.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/dataflow-result/chunker.tsx
  web/src/pages/dataflow-result/components/rerun-button/index.tsx
  web/src/pages/dataflow-result/components/time-line/index.tsx
  web/src/pages/dataflow-result/hooks.ts
  web/src/pages/dataflow-result/index.tsx
  web/src/pages/dataflow-result/parser.tsx
  web/src/pages/dataset/dataset-overview/hook.ts
  web/src/pages/dataset/dataset-overview/index.tsx
  web/src/pages/dataset/dataset-overview/overview-table.tsx
  web/src/services/knowledge-service.ts
  web/src/utils/api.ts
  web/src/utils/common-util.ts
Labels: 🐞 bug, ci, size:L

#10152 Add Firecrawl integration for RAGFlow
  intergrations/firecrawl/INSTALLATION.md
  intergrations/firecrawl/README.md
  intergrations/firecrawl/__init__.py
  intergrations/firecrawl/example_usage.py
  intergrations/firecrawl/firecrawl_config.py
  intergrations/firecrawl/firecrawl_connector.py
  intergrations/firecrawl/firecrawl_processor.py
  intergrations/firecrawl/firecrawl_ui.py
  intergrations/firecrawl/integration.py
  intergrations/firecrawl/ragflow_integration.py
  intergrations/firecrawl/requirements.txt
Labels: 💞 feature, ci, size:XXL

#10158 Feat: Add file convert to document API just like file2document_app.py
  api/apps/sdk/files.py
Labels: 💞 feature, ci, size:M, 🐖api

#10150 Support server health check by http://localhost:<port>/v1/system/healthz
  api/apps/HEALTHCHECK_TESTING.md
  api/apps/system_app.py
  api/utils/health_utils.py
  docs/guides/run_health_check.md
  docs/references/http_api_reference.md
Labels: 💞 feature, ci, size:L

#10167 Feat: pipeline supports PPTX
  rag/flow/parser/parser.py
  rag/flow/tests/dsl_examples/general_pdf_all.json
  rag/flow/tokenizer/tokenizer.py
  rag/llm/embedding_model.py
Labels: 💞 feature, ci, size:M

#10173 Feat: add support for Anthropic third-party API
  rag/llm/__init__.py
  web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
Labels: 💞 feature, ci, size:S

#10181 Feat: parse email
  api/db/services/file_service.py
  api/utils/file_utils.py
  pyproject.toml
  rag/app/email.py
  rag/flow/parser/parser.py
  rag/flow/tests/dsl_examples/general_pdf_all.json
  uv.lock
Labels: 🐞 bug, 💞 feature, ci, size:L

#10187 Chat Widget
  chat_demo/index.html
  chat_demo/widget_demo.html
  web/src/components/embed-dialog/index.tsx
  web/src/components/floating-chat-widget.tsx
  web/src/pages/next-chats/widget/index.tsx
  web/src/routes.ts
Labels: 💞 feature, ci, size:XL

#10195 Feat: Add suffix field to all operators #9869
  web/src/components/delimiter-form-field.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx
  web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx
  web/src/pages/data-flow/log-sheet/index.tsx
  web/src/pages/data-flow/utils.ts
Labels: 💞 feature, ci, size:L

#10198 Feat: Remove useless files from the data flow #9869
  web/src/pages/data-flow/canvas/node/use-build-categorize-handle-positions.ts
  web/src/pages/data-flow/canvas/node/use-build-switch-handle-positions.ts
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form-sheet/form-config-map.tsx
  web/src/pages/data-flow/form-sheet/next.tsx
  web/src/pages/data-flow/form-sheet/single-debug-sheet/index.tsx
  web/src/pages/data-flow/form/begin-form/begin-dynamic-options.tsx
  web/src/pages/data-flow/form/begin-form/index.tsx
  web/src/pages/data-flow/form/begin-form/parameter-dialog.tsx
  web/src/pages/data-flow/form/begin-form/query-table.tsx
  web/src/pages/data-flow/form/begin-form/use-edit-query.ts
  web/src/pages/data-flow/form/begin-form/use-values.ts
  web/src/pages/data-flow/form/begin-form/use-watch-change.ts
  web/src/pages/data-flow/form/begin-form/utils.ts
  web/src/pages/data-flow/form/components/api-key-field.tsx
  web/src/pages/data-flow/form/components/description-field.tsx
  web/src/pages/data-flow/form/components/dynamic-input-variable.tsx
  web/src/pages/data-flow/form/components/next-dynamic-input-variable.tsx
  web/src/pages/data-flow/form/components/prompt-editor/constant.ts
  web/src/pages/data-flow/form/components/prompt-editor/index.css
  web/src/pages/data-flow/form/components/prompt-editor/index.tsx
  web/src/pages/data-flow/form/components/prompt-editor/paste-handler-plugin.tsx
  web/src/pages/data-flow/form/components/prompt-editor/theme.ts
  web/src/pages/data-flow/form/components/prompt-editor/variable-node.tsx
  web/src/pages/data-flow/form/components/prompt-editor/variable-on-change-plugin.tsx
  web/src/pages/data-flow/form/components/prompt-editor/variable-picker-plugin.tsx
  web/src/pages/data-flow/form/components/query-variable.tsx
  web/src/pages/data-flow/form/splitter-form/index.tsx
  web/src/pages/data-flow/hooks/use-add-node.ts
  web/src/pages/data-flow/hooks/use-before-delete.tsx
  web/src/pages/data-flow/hooks/use-chat-logic.ts
  web/src/pages/data-flow/hooks/use-export-json.ts
  web/src/pages/data-flow/hooks/use-find-mcp-by-id.ts
  web/src/pages/data-flow/hooks/use-get-begin-query.tsx
  web/src/pages/data-flow/hooks/use-iteration.ts
  web/src/pages/data-flow/hooks/use-run-dataflow.ts
  web/src/pages/data-flow/hooks/use-show-drawer.tsx
  web/src/pages/data-flow/index.tsx
  web/src/pages/data-flow/options.ts
  web/src/pages/data-flow/upload-agent-dialog/index.tsx
  web/src/pages/data-flow/upload-agent-dialog/upload-agent-form.tsx
  web/src/pages/data-flow/utils/chat.ts
Labels: 💞 feature, ci, size:XXL

#10202 Add tree_merge for law parsers, significantly outperforming hierarchical_merge
  api/utils/health_utils.py
  rag/app/laws.py
  rag/nlp/__init__.py
Labels: 💞 feature, ci, size:L

#10197 Refactor: use the same implement for total token count from res
  rag/llm/chat_model.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
  rag/utils/__init__.py
Labels: ci, ☯️ refactor, size:M

#10209 Feat: Exporting the results of data flow tests #9869
  web/src/pages/data-flow/hooks/use-download-output.ts
  web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx
  web/src/pages/data-flow/log-sheet/index.tsx
Labels: 💞 feature, ci, size:M

#10252 Fix:max_tokens must be at least 1, got -950, BadRequestError
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, ☯️ refactor, size:XS

#10206 Fix: pipeline debug...
  api/apps/HEALTHCHECK_TESTING.md
  api/apps/canvas_app.py
  api/apps/kb_app.py
  api/db/services/document_service.py
  api/utils/base64_image.py
  rag/flow/hierarchical_merger/hierarchical_merger.py
  rag/flow/parser/parser.py
  rag/flow/pipeline.py
  rag/flow/splitter/splitter.py
  rag/flow/tokenizer/tokenizer.py
  rag/nlp/__init__.py
  rag/svr/task_executor.py
Labels: 🐞 bug, 💞 feature, ci, size:L

#10251 UI: Update Russian language ru.ts
  web/src/locales/ru.ts
Labels: ci, size:L

#10250 Fix: Russian language config.ts
  web/src/locales/config.ts
Labels: ci, size:XS

#10263 add Qwen models
  conf/llm_factories.json
Labels: 💞 feature, ci, size:M

#10264 Feat: add foundational support for GraphRAG dataset pipeline logs
  api/apps/kb_app.py
  api/db/__init__.py
  api/db/db_models.py
  api/db/services/document_service.py
  api/db/services/pipeline_operation_log_service.py
  api/db/services/task_service.py
  graphrag/general/index.py
  rag/flow/pipeline.py
  rag/nlp/search.py
  rag/svr/task_executor.py
Labels: 💞 feature, ci, size:XL

#10272 fix: Wrong Qwen models's ID
  conf/llm_factories.json
Labels: 🐞 bug, ci, size:M

#10275 fix: replace traceback.print_exc() with logging.exception(e) in conve…
  api/apps/conversation_app.py
Labels: 🐞 bug, ci, size:XS

#10200 Refactor: fix typos
  agent/component/base.py
  agent/component/categorize.py
  agent/component/llm.py
  agent/component/message.py
  api/apps/sdk/files.py
  api/db/__init__.py
  api/db/services/__init__.py
Labels: ci, ☯️ refactor, size:M

#10203 Refactor: move encrypt/decrypt to one file
  api/apps/user_app.py
  api/utils/__init__.py
  api/utils/crypt.py
  api/utils/t_crypt.py
Labels: ci, ☯️ refactor, size:L

#10276 Refa: fake doc ID.
  api/apps/kb_app.py
  api/db/services/document_service.py
  api/db/services/pipeline_operation_log_service.py
  api/db/services/task_service.py
  api/utils/api_utils.py
  rag/svr/task_executor.py
Labels: ci, ☯️ refactor, size:M

#10279 Feat: Allows the extractor operator's prompt to reference the output of an upstream operator #9869
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx
  web/src/pages/agent/form/iteration-form/use-build-options.ts
  web/src/pages/agent/hooks/use-get-begin-query.tsx
  web/src/pages/data-flow/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form-sheet/form-config-map.tsx
  web/src/pages/data-flow/form/extractor-form/index.tsx
  web/src/pages/data-flow/hooks/use-add-node.ts
  web/src/pages/data-flow/hooks/use-build-options.tsx
  web/src/pages/data-flow/operator-icon.tsx
  web/src/utils/canvas-util.tsx
Labels: 💞 feature, ci, size:L

#10284 Feat(nlp): add "怎么办" pattern to question word removal
  rag/nlp/query.py
Labels: 💞 feature, ci, size:XS

#10306 feat: add IBM DB2 support
  agent/component/agent_with_tools.py
  agent/component/base.py
  agent/component/invoke.py
  agent/component/llm.py
  agent/component/message.py
  agent/component/switch.py
  agent/tools/code_exec.py
  agent/tools/exesql.py
  api/apps/canvas_app.py
  pyproject.toml
  rag/flow/base.py
  uv.lock
  web/src/pages/agent/options.ts
  web/src/pages/data-flow/options.ts
  web/src/pages/flow/constant.tsx
Labels: 💞 feature, 🌈 python, ci, size:L

#10309 Feat: Bring the parser operator when creating a new data flow #9869
  web/src/less/mixins.less
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agents/hooks/use-create-agent.ts
  web/src/pages/agents/index.tsx
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/hooks/use-run-dataflow.ts
  web/src/pages/data-flow/index.tsx
  web/src/pages/data-flow/utils.ts
Labels: 💞 feature, ci, size:M

#10311 Fix: debug pipeline...
  api/apps/canvas_app.py
  api/apps/dataflow_app.py
  api/apps/document_app.py
  api/apps/kb_app.py
  api/db/services/knowledgebase_service.py
  api/db/services/pipeline_operation_log_service.py
  api/db/services/task_service.py
  deepdoc/parser/pdf_parser.py
  rag/flow/extractor/extractor.py
  rag/flow/extractor/schema.py
  rag/flow/hierarchical_merger/hierarchical_merger.py
  rag/flow/hierarchical_merger/schema.py
  rag/flow/parser/parser.py
  rag/flow/pipeline.py
  rag/flow/splitter/splitter.py
  rag/flow/tokenizer/schema.py
  rag/flow/tokenizer/tokenizer.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XL

#10325 Fix:After setting user's is_active to 0, the user can still log in to RAGFlow.
  api/apps/user_app.py
Labels: 🐞 bug, ci, size:XS

#10330 fix: remove ibm-db dependency and refactor import order
  agent/tools/exesql.py
  pyproject.toml
  uv.lock
Labels: 🐞 bug, ci, size:XS

#10335 Feat: add support for deleting KB tasks
  api/apps/kb_app.py
Labels: 💞 feature, ci, size:M

#10319 Fix bug of image parser and prompt of parser supports customization
  rag/flow/parser/parser.py
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/data-flow/constant.tsx
  web/src/pages/data-flow/form/parser-form/image-form-fields.tsx
  web/src/pages/data-flow/form/parser-form/index.tsx
  web/src/pages/data-flow/utils.ts
Labels: 🐞 bug, ci, size:M

#10317 Fix: floating widget match style with original one
  web/src/components/floating-chat-widget-markdown.less
  web/src/components/floating-chat-widget-markdown.tsx
  web/src/components/floating-chat-widget.tsx
  web/src/components/pdf-drawer/index.tsx
Labels: 🐞 bug, ci, size:XL

#10339 Fix: The dataset uses the new id to obtain the knowledge graph #10333
  web/src/pages/add-knowledge/components/knowledge-graph/index.tsx
  web/src/pages/add-knowledge/components/knowledge-graph/use-delete-graph.ts
  web/src/pages/dataset/knowledge-graph/index.tsx
  web/src/pages/dataset/knowledge-graph/use-delete-graph.ts
Labels: 🐞 bug, ci, size:XS

#10344 Feat: Filter the agent list by owner and category #9869
  web/src/components/data-pipeline-select/index.tsx
  web/src/constants/agent.ts
  web/src/hooks/use-agent-request.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agents/agent-card.tsx
  web/src/pages/agents/hooks/use-create-agent.ts
  web/src/pages/agents/hooks/use-selelct-filters.ts
  web/src/pages/agents/index.tsx
  web/src/pages/datasets/use-select-owners.ts
  web/src/services/agent-service.ts
  web/src/utils/api.ts
  web/src/utils/dataset-util.ts
  web/src/utils/list-filter-util.ts
Labels: 💞 feature, ci, size:L

#10347 Feat: Displays the loading status of the data flow log #9869
  web/src/hooks/use-agent-request.ts
  web/src/locales/en.ts
  web/src/pages/agent/log-sheet/workflow-timeline.tsx
  web/src/pages/data-flow/form/tokenizer-form/index.tsx
  web/src/pages/data-flow/hooks/use-cancel-dataflow.ts
  web/src/pages/data-flow/hooks/use-fetch-log.ts
  web/src/pages/data-flow/index.tsx
  web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx
  web/src/pages/data-flow/log-sheet/index.tsx
Labels: 💞 feature, ci, size:L

#10343 Fix: unexpected operation of file management
  api/apps/file_app.py
Labels: 🐞 bug, ci, size:XS

#10337 Fix: debug hierachical merging...
  api/apps/canvas_app.py
  api/apps/kb_app.py
  api/db/services/canvas_service.py
  api/db/services/document_service.py
  api/db/services/pipeline_operation_log_service.py
  api/db/services/task_service.py
  rag/flow/hierarchical_merger/hierarchical_merger.py
  rag/flow/parser/parser.py
  rag/flow/pipeline.py
  rag/flow/splitter/splitter.py
  rag/flow/tokenizer/schema.py
  rag/flow/tokenizer/tokenizer.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:L

#10141 Feat: Keep connection status during generating agent by drag and drop …
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/placeholder-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-connection-drag.ts
  web/src/pages/agent/hooks/use-dropdown-position.ts
  web/src/pages/agent/hooks/use-placeholder-manager.ts
  web/src/pages/agent/hooks/use-show-drawer.tsx
Labels: 💞 feature, ci, size:XL

#10355 Feat: Move the github icon to the right #9869
  web/public/iconfont.js
  web/src/hooks/use-agent-request.ts
  web/src/layouts/next-header.tsx
  web/src/locales/en.ts
  web/src/pages/data-flow/form/tokenizer-form/index.tsx
Labels: ci, size:M

#10356 Feat: add support for international Dashscope service
  rag/llm/chat_model.py
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/fr.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/ru.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
Labels: 💞 feature, ci, size:M

#10367 Feat: Remove the copy icon from the toolbar for the Splitter and Parser nodes #9869
  web/src/pages/data-flow/canvas/edge/index.tsx
  web/src/pages/data-flow/canvas/index.tsx
  web/src/pages/data-flow/canvas/node/context-node.tsx
  web/src/pages/data-flow/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/data-flow/canvas/node/extractor-node.tsx
  web/src/pages/data-flow/canvas/node/index.tsx
  web/src/pages/data-flow/canvas/node/logic-node.tsx
  web/src/pages/data-flow/canvas/node/parser-node.tsx
  web/src/pages/data-flow/canvas/node/tokenizer-node.tsx
  web/src/pages/data-flow/canvas/node/toolbar.tsx
  web/src/pages/data-flow/constant.tsx
Labels: 💞 feature, ci, size:L

#10365 Fix: debug PDF positions..
  api/apps/canvas_app.py
  api/apps/kb_app.py
  api/db/services/pipeline_operation_log_service.py
  deepdoc/parser/pdf_parser.py
  rag/flow/extractor/extractor.py
  rag/flow/parser/parser.py
  rag/flow/splitter/splitter.py
  rag/llm/embedding_model.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:L

#10370 Fix: Added read-only mode support and optimized navigation logic #9869
  web/public/iconfont.js
  web/src/components/originui/timeline.tsx
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
  web/src/pages/data-flow/log-sheet/index.tsx
  web/src/pages/dataflow-result/components/chunk-result-bar/index.tsx
  web/src/pages/dataflow-result/components/parse-editer/hook.ts
  web/src/pages/dataflow-result/components/parse-editer/index.tsx
  web/src/pages/dataflow-result/components/parse-editer/interface.ts
  web/src/pages/dataflow-result/components/parse-editer/json-parser.tsx
  web/src/pages/dataflow-result/components/parse-editer/object-parser.tsx
  web/src/pages/dataflow-result/components/time-line/index.tsx
  web/src/pages/dataflow-result/constant.ts
  web/src/pages/dataflow-result/hooks.ts
  web/src/pages/dataflow-result/index.tsx
  web/src/pages/dataflow-result/interface.ts
  web/src/pages/dataflow-result/parser.tsx
  web/src/pages/dataset/dataset-overview/hook.ts
  web/src/pages/dataset/dataset-overview/index.tsx
  web/src/pages/dataset/dataset-overview/overview-table.tsx
  web/src/pages/dataset/dataset/constant.ts
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/services/knowledge-service.ts
  web/src/utils/common-util.ts
  web/tailwind.config.js
  web/tailwind.css
Labels: 🐞 bug, ci, size:XL

#10374 Feat: add support for LongCat-Flash-Thinking and Claude Sonnet 4.5
  conf/llm_factories.json
Labels: 💞 feature, size:S

#10378 Fix: reset tools in/out-put.
  agent/component/agent_with_tools.py
Labels: 🐞 bug, ci, size:XS

#10386 Fix: input
  rag/flow/parser/parser.py
Labels: 🐞 bug, ci, size:XS

#10381 Feat/service manage
  admin/admin_client.py
  admin/config.py
  admin/services.py
  api/apps/system_app.py
  api/utils/common.py
  api/utils/health_utils.py
  docs/guides/manage_users_and_services.md
  rag/utils/es_conn.py
  rag/utils/redis_conn.py
Labels: 💞 feature, ci, size:L

#10392 Feat: View data flow test results #9869
  web/src/hooks/use-chunk-request.ts
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agents/create-agent-dialog.tsx
  web/src/pages/agents/create-agent-form.tsx
  web/src/pages/agents/name-form-field.tsx
  web/src/pages/data-flow/context.ts
  web/src/pages/data-flow/hooks/use-run-dataflow.ts
  web/src/pages/data-flow/index.tsx
  web/src/pages/data-flow/log-sheet/index.tsx
  web/src/pages/dataflow-result/components/document-preview/hooks.ts
  web/src/pages/dataflow-result/constant.ts
  web/src/pages/dataflow-result/hooks.ts
  web/src/pages/dataflow-result/index.tsx
  web/src/pages/dataflow-result/interface.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:L

#10391 Doc: Fixed a typo
  docs/develop/mcp/launch_mcp_server.md
Labels: 📖 documentation, size:XS

#10345 Fix highlight with infinity
  README.md
  download_deps.py
  pyproject.toml
  rag/utils/infinity_conn.py
  uv.lock
Labels: 🐞 bug, ci, ♾️infinity, size:L
