Repository infiniflow/ragflow, pull requests merged in 2025-07, with the labels that each got.

#8578 Refa: change mcp_client module to rag/utils/conn
  Dockerfile
  Dockerfile.scratch.oc9
  api/apps/mcp_server_app.py
  api/ragflow_server.py
  mcp_client/__init__.py
  rag/utils/mcp_tool_call_conn.py
Labels: ci, ☯️ refactor, size:M

#8590 doc: change to chunk_token num
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
Labels: 📖 documentation, size:XS

#8395 Feat: Add file management HTTP_API
  api/apps/sdk/files.py
Labels: 💞 feature, ci, size:XL

#8597 Trivals.
  api/utils/log_utils.py
  graphrag/general/index.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:S

#8616 Test: Add tests for chunk API endpoints
  api/apps/chunk_app.py
  test/testcases/test_http_api/conftest.py
  test/testcases/test_web_api/common.py
  test/testcases/test_web_api/conftest.py
  test/testcases/test_web_api/test_chunk_app/conftest.py
  test/testcases/test_web_api/test_chunk_app/test_create_chunk.py
  test/testcases/test_web_api/test_chunk_app/test_list_chunks.py
  test/testcases/test_web_api/test_chunk_app/test_retrieval_chunks.py
  test/testcases/test_web_api/test_chunk_app/test_rm_chunks.py
  test/testcases/test_web_api/test_chunk_app/test_update_chunk.py
Labels: ci, size:XXL, 🧪 test

#8610 Feat: Construct the to field of the classification operator when saving data #3221
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/store.ts
  web/src/pages/agent/utils.ts
Labels: 💞 feature, ci, size:M

#8607 Add service_conf and llm_factories options to Helm chart
  helm/templates/ragflow.yaml
  helm/templates/ragflow_config.yaml
  helm/values.yaml
Labels: 💞 feature, ci, size:M

#8623 Feat: Convert the arguments parameter of the code operator to a dictionary #3221
  web/src/components/next-message-item/index.tsx
  web/src/interfaces/database/chat.ts
  web/src/pages/agent/canvas/node/iteration-node.tsx
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/chat/input-form.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/begin-form/use-watch-change.ts
  web/src/pages/agent/form/code-form/use-values.ts
  web/src/pages/agent/form/code-form/use-watch-change.ts
  web/src/pages/agent/form/components/prompt-editor/variable-node.tsx
  web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8628 Update Chrome download URL in use_china_mirrors configuration
  download_deps.py
Labels: 🌈 python, ci, size:XS

#8633 Fix: anthropic llm issue.
  api/settings.py
  conf/llm_factories.json
  rag/llm/chat_model.py
  rag/utils/opensearch_conn.py
Labels: 🐞 bug, ci, size:M

#8603 Fix: page_size can be None error
  api/db/services/task_service.py
Labels: 🐞 bug, ci, size:XS

#8638 Feat: Combine the output logs of the same operator together #3221
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/log-sheet/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:M

#8645 Feat: Display the iteration operator toolbar #3221
  web/src/components/xyflow/tooltip-node.tsx
  web/src/pages/agent/canvas/node/iteration-node.tsx
  web/src/pages/agent/constant.tsx
Labels: 💞 feature, ci, size:M

#8649 Feat: Edit the output data of the code operator #3221
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/code-form/next-variable.tsx
  web/src/pages/agent/form/code-form/schema.ts
  web/src/pages/agent/form/code-form/use-values.ts
  web/src/pages/agent/form/code-form/use-watch-change.ts
  web/src/pages/agent/utils/build-output-list.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8647 Update svg of SiliconFlow with new LOGO
  web/src/assets/svg/llm/siliconflow.svg
Labels: size:XS

#8651 Refa: automatic LLMs registration
  rag/llm/__init__.py
  rag/llm/chat_model.py
  rag/llm/cv_model.py
  rag/llm/embedding_model.py
  rag/llm/rerank_model.py
  rag/llm/sequence2txt_model.py
  rag/llm/tts_model.py
Labels: ci, ☯️ refactor, size:XXL

#8662 Fix: Fixed the issue where the debug form Switch component had no default value #3221
  web/src/pages/agent/debug-content/index.tsx
Labels: 🐞 bug, ci, size:M

#8657 Fix: The data set created by API call failed to parse after uploading the file.
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#8665 feat: use official sources for chromedriver-linux in download_deps.py
  download_deps.py
Labels: 💞 feature, ci, size:XS

#8655 fix:Optimized the style of the dataset configuration page and added the l…
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-select-filters.ts
  web/src/pages/dataset/setting/chunk-method-form.tsx
  web/src/pages/dataset/setting/general-form.tsx
  web/src/pages/dataset/setting/index.tsx
Labels: 🐞 bug, ci, size:L

#8667 Refa: refactor prompts into markdown-style structure using Jinja2
  rag/prompt_template.py
  rag/prompts.py
  rag/prompts/citation_prompt.md
  rag/prompts/content_tagging_prompt.md
  rag/prompts/cross_languages_sys_prompt.md
  rag/prompts/cross_languages_user_prompt.md
  rag/prompts/full_question_prompt.md
  rag/prompts/keyword_prompt.md
  rag/prompts/question_prompt.md
  rag/prompts/vision_llm_describe_prompt.md
  rag/prompts/vision_llm_figure_describe_prompt.md
Labels: ci, ☯️ refactor, size:XL

#8676 fix: optimize the chunk result page
  web/src/components/ui/message.ts
  web/src/components/ui/ragflow-pagination.tsx
  web/src/components/ui/spin.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
Labels: 🐞 bug, ci, size:L

#8671 Fix: Wrong Citation Display #8594 #8474
  web/src/pages/chat/markdown-content/index.tsx
  web/src/pages/chat/utils.ts
Labels: 🐞 bug, ci, size:S

#8673 Fix a small typo in count of used fragments
  rag/prompts.py
Labels: 🐞 bug, ci, size:XS

#8678 Fix: add ES re-connect once request timeout.
  rag/utils/es_conn.py
Labels: 🐞 bug, ci, size:M

#8687 fix task_service.py
  api/db/services/task_service.py
Labels: 🐞 bug, ci, size:XS

#8697 Feat: Support uploading files when running agent #3221
  web/src/components/file-upload.tsx
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/debug-content/uploader.tsx
  web/src/pages/agent/utils.ts
  web/src/pages/agent/utils/chat.ts
  web/src/services/flow-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, 🧰 typescript, size:XXL

#8693 Refa: Update Minio image to specific release version in docker-compose-base.yml
  docker/docker-compose-base.yml
Labels: ci, ☯️ refactor, size:XS

#8696 Fix: typo process_duration
  api/apps/document_app.py
  api/apps/sdk/doc.py
  api/db/db_models.py
  api/db/services/document_service.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/ragflow_sdk/modules/document.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_stop_parse_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_web_api/test_document_app/test_paser_documents.py
  web/src/interfaces/database/document.ts
  web/src/interfaces/database/knowledge.ts
  web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
  web/src/pages/dataset/dataset/parsing-card.tsx
Labels: 📖 documentation, ci, ☯️ refactor, size:M

#8695 fix:Use use-chunk-request.ts to replace chunk-hooks.ts; implement chunk selectAll, enable, disable and other functions
  web/src/hooks/use-chunk-request.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/checkbox-sets.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:L

#8692 Fix:disallowed special token while embedding
  rag/llm/embedding_model.py
Labels: 🐞 bug, ci, size:XS

#8698 Fix: suppress docker-compose warning
  docker/docker-compose-base.yml
  docker/docker-compose.yml
Labels: 🐞 bug, ci, ☯️ refactor, size:XS

#8710 Fix: EsLint Problem of index.tsx
  web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
Labels: ci, 🧰 typescript, size:S

#8712 fix：Added support for preview of txt, md, excel, csv, ppt, image, doc and other files
  web/package.json
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/csv-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/doc-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/excel-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/image-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/pdf-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/ppt-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/txt-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
Labels: 🐞 bug, ci, size:XL

#8729 Test: Add dialog app test suite and update common.py with dialog endpoints
  test/testcases/test_web_api/common.py
  test/testcases/test_web_api/conftest.py
  test/testcases/test_web_api/test_dialog_app/conftest.py
  test/testcases/test_web_api/test_dialog_app/test_create_dialog.py
  test/testcases/test_web_api/test_dialog_app/test_delete_dialogs.py
  test/testcases/test_web_api/test_dialog_app/test_dialog_edge_cases.py
  test/testcases/test_web_api/test_dialog_app/test_get_dialog.py
  test/testcases/test_web_api/test_dialog_app/test_list_dialogs.py
  test/testcases/test_web_api/test_dialog_app/test_update_dialog.py
Labels: ci, size:XXL, 🧪 test

#8726 fix: Change the data in the dataset page to be obtained using the interface
  web/src/components/list-filter-bar/filter-popover.tsx
  web/src/components/list-filter-bar/index.tsx
  web/src/hooks/use-document-request.ts
  web/src/interfaces/database/document.ts
  web/src/interfaces/request/knowledge.ts
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.less
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/checkbox-sets.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-select-filters.ts
  web/src/pages/dataset/testing/index.tsx
  web/src/services/knowledge-service.ts
  web/src/utils/api.ts
Labels: 🐞 bug, ci, 🧰 typescript, size:L

#8731 Docs: miscellaneous editorial updates
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/quickstart.mdx
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:S

#8732 Fix:use the same logic to handle pos in tokenize_chunks_with_images
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:XS

#8730 Feat: List MCP servers #3221
  web/src/hooks/use-mcp-request.ts
  web/src/interfaces/database/mcp.ts
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
  web/src/pages/profile-setting/mcp/index.tsx
  web/src/pages/profile-setting/mcp/mcp-card.tsx
  web/src/pages/profile-setting/mcp/mcp-dropdown.tsx
  web/src/pages/profile-setting/mcp/use-edit-mcp.ts
  web/src/pages/profile-setting/sidebar/hooks.tsx
  web/src/pages/profile-setting/sidebar/index.tsx
  web/src/routes.ts
  web/src/services/mcp-server-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:XL

#8723 Feat: add advanced document filter
  api/apps/api_app.py
  api/apps/document_app.py
  api/apps/file2document_app.py
  api/db/db_models.py
  api/db/services/document_service.py
  api/db/services/file_service.py
Labels: 💞 feature, ci, size:L

#8737 Feat: Display MCP multiple selection bar #3221
  web/src/components/bulk-operate-bar.tsx
  web/src/hooks/use-mcp-request.ts
  web/src/pages/agent/chat/hooks.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/message-form/use-values.ts
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
  web/src/pages/profile-setting/mcp/index.tsx
  web/src/pages/profile-setting/mcp/mcp-card.tsx
  web/src/pages/profile-setting/mcp/use-bulk-operate-mcp.tsx
  web/src/pages/profile-setting/mcp/use-edit-mcp.ts
  web/src/utils/request.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8734 Fix: Change Ollama Embedding Keep Alive
  rag/llm/embedding_model.py
Labels: 🐞 bug, ci, size:XS

#8746 Docs: Updated upgrading guide
  docs/guides/upgrade_ragflow.mdx
Labels: 📖 documentation, size:S

#8757 Feat: Test MCP server #3221
  web/src/hooks/use-mcp-request.ts
  web/src/interfaces/database/mcp.ts
  web/src/interfaces/request/mcp.ts
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
  web/src/pages/profile-setting/mcp/mcp-card.tsx
  web/src/pages/profile-setting/mcp/tool-card.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8756 feat: Complete the UI drawing of price-page
  web/src/components/originui/number-input.tsx
  web/src/pages/price/components/AddOnCalculator.tsx
  web/src/pages/price/components/FAQs.tsx
  web/src/pages/price/components/PricingCard.tsx
  web/src/pages/price/index.less
  web/src/pages/price/index.tsx
  web/src/routes.ts
Labels: 💞 feature, ci, size:L

#8753 Fix: Increase default `chunk_token_num` from 128 to 512 in parser config
  api/utils/api_utils.py
  api/utils/validation_utils.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
Labels: 🐞 bug, ci, size:M, 🧪 test

#8760 fix: use tenant_id of kb to get index name in rm chunk func
  api/apps/chunk_app.py
Labels: 🐞 bug, ci, size:XS

#8768 Feat: Avoid the form sheet covering the chat sheet #3221
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/hooks/use-show-drawer.tsx
  web/src/pages/agent/log-sheet/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:S

#8772 Feat: Delete MCP server #3221
  web/src/hooks/use-mcp-request.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/profile-setting/mcp/mcp-card.tsx
  web/src/pages/profile-setting/mcp/mcp-dropdown.tsx
  web/src/pages/profile-setting/mcp/use-bulk-operate-mcp.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8773 Refa: refine retry gap.
  rag/llm/chat_model.py
Labels: ci, ☯️ refactor, size:XS

#8769 Fix: Resolve typo in /list route function
  api/apps/conversation_app.py
Labels: 🐞 bug, ci, size:XS

#8780 Feat: Modify the agent tool name #3221
  web/src/interfaces/database/agent.ts
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/agent-form/tool-popover/use-update-tools.ts
  web/src/pages/agent/hooks.tsx
  web/src/pages/agent/hooks/use-change-node-name.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8784 Feat: Edit MCP server #3221
  web/src/components/collapse.tsx
  web/src/hooks/use-mcp-request.ts
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
  web/src/pages/profile-setting/mcp/index.tsx
  web/src/pages/profile-setting/mcp/mcp-card.tsx
  web/src/pages/profile-setting/mcp/mcp-dropdown.tsx
  web/src/pages/profile-setting/mcp/use-edit-mcp.ts
  web/src/services/mcp-server-service.ts
Labels: 💞 feature, ci, size:L

#8781 Feat: add xAI provider
  conf/llm_factories.json
  docs/references/supported_models.mdx
  rag/llm/chat_model.py
  rag/llm/cv_model.py
Labels: 💞 feature, ci, size:M

#8777 Feat: change document status in bulk
  api/apps/document_app.py
Labels: 💞 feature, ci, size:M

#8786 fix: fix dataset-page's bugs
  web/src/components/entity-types-form-field.tsx
  web/src/components/entity-types-item.tsx
  web/src/components/list-filter-bar/use-handle-filter-submit.ts
  web/src/components/max-token-number-from-field.tsx
  web/src/components/originui/input.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/components/ui/input.tsx
  web/src/components/ui/popover.tsx
  web/src/components/ui/radio.tsx
  web/src/components/ui/segmented.tsx
  web/src/hooks/chunk-hooks.ts
  web/src/hooks/document-hooks.ts
  web/src/hooks/knowledge-hooks.ts
  web/src/hooks/logic-hooks.ts
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/hooks/use-document-request.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx
  web/src/pages/dataset/dataset/use-bulk-operate-dataset.tsx
  web/src/pages/dataset/setting/chunk-method-learn-more.tsx
  web/src/pages/dataset/setting/configuration/naive.tsx
  web/src/pages/dataset/setting/general-form.tsx
  web/src/pages/dataset/setting/index.tsx
Labels: 🐞 bug, ci, size:XL

#8792 Fix: Improve Memory Usage For Presentation
  rag/app/presentation.py
Labels: 🐞 bug, ci, size:S

#8775 Fix: better_handle_different_types
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:S

#8801 Refa: better MIME content type
  api/apps/document_app.py
  api/apps/file_app.py
  api/utils/web_utils.py
Labels: ci, ☯️ refactor, size:M

#8767 Feat: Add text and markdown file view
  web/src/pages/document-viewer/index.tsx
  web/src/pages/document-viewer/md/index.tsx
  web/src/pages/document-viewer/text/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#8820 Feat: Filter MCP server list by text. #3221
  web/src/hooks/use-mcp-request.ts
  web/src/locales/en.ts
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-form.tsx
  web/src/pages/profile-setting/mcp/index.tsx
  web/src/pages/profile-setting/mcp/use-edit-mcp.ts
  web/src/services/mcp-server-service.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8816 Perf:Remove Useless Convert When BGE Embedding
  rag/llm/embedding_model.py
Labels: ci, size:XS

#8823 Feat: refine create and list operations for MCP dashboard
  api/apps/mcp_server_app.py
  api/utils/mcp_server.py
Labels: ci, ☯️ refactor, size:L

#8826 Perf: Enhance timeout handling.
  api/apps/mcp_server_app.py
  api/utils/api_utils.py
  api/utils/mcp_server.py
  graphrag/general/community_reports_extractor.py
  graphrag/general/extractor.py
  graphrag/general/index.py
  graphrag/utils.py
  rag/raptor.py
  rag/svr/task_executor.py
  rag/utils/redis_conn.py
Labels: ci, size:L

#8832 Feat: Synchronize MCP data to agent #3221
  web/src/hooks/use-mcp-request.ts
  web/src/interfaces/database/mcp.ts
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/tool-form/index.tsx
  web/src/pages/agent/form/tool-form/mcp-form/index.tsx
  web/src/pages/agent/form/tool-form/mcp-form/mcp-card.tsx
  web/src/pages/agent/form/tool-form/mcp-form/use-values.ts
  web/src/pages/agent/form/tool-form/mcp-form/use-watch-change.ts
  web/src/pages/agent/utils.ts
  web/src/services/mcp-server-service.ts
Labels: 💞 feature, ci, size:L

#8841 Feat: Adjust agent mcp style #3221
  web/src/locales/en.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/begin-form/index.tsx
  web/src/pages/agent/form/categorize-form/index.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/iteration-form/index.tsx
  web/src/pages/agent/form/iteration-start-from/index.tsx
  web/src/pages/agent/form/message-form/index.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tool-form/index.tsx
  web/src/pages/agent/form/tool-form/mcp-form/index.tsx
  web/src/pages/agent/form/tool-form/mcp-form/mcp-card.tsx
  web/src/pages/agent/form/user-fill-up-form/index.tsx
  web/src/pages/agent/form/waiting-dialogue-form/index.tsx
  web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx
  web/src/pages/profile-setting/mcp/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8842 Fix: no chunks parsed out for Law
  rag/nlp/__init__.py
Labels: 🐞 bug, ci, size:XS

#8844 Fix: fixed context loss caused by separating markdown tables from original text
  deepdoc/parser/markdown_parser.py
  rag/app/naive.py
Labels: 🐞 bug, ci, size:L

#8836 Update embedding_model.py
  rag/llm/embedding_model.py
Labels: ci, size:XS

#8846 Perf: make `do_cancel` quicker.
  api/utils/api_utils.py
  rag/raptor.py
  rag/svr/task_executor.py
Labels: ci, size:M

#8830 Fix: Remove antd from dataset-page
  web/src/components/edit-tag/index.less
  web/src/components/edit-tag/index.tsx
  web/src/components/image/index.less
  web/src/components/image/index.tsx
  web/src/components/originui/input.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/components/ui/button.tsx
  web/src/components/ui/divider.tsx
  web/src/components/ui/hover-card.tsx
  web/src/components/ui/modal.tsx
  web/src/components/ui/space.tsx
  web/src/components/ui/textarea.tsx
  web/src/hooks/use-knowledge-request.ts
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/tag-feature-item.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/pdf-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/txt-preview.tsx
  web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.less
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/setting/tag-table/index.tsx
  web/src/pages/document-viewer/index.tsx
  web/src/pages/document-viewer/md/index.tsx
  web/src/pages/document-viewer/text/index.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:XXL

#8853 Pref: use redis to check if canceled.
  api/apps/document_app.py
  api/db/services/task_service.py
  rag/svr/task_executor.py
Labels: ci, size:M

#8851 Fix: fixed invalid save() arguments for slide thumbnails
  rag/app/presentation.py
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:S

#8857 Feat: Add CrawlerForm component #3221
  web/src/components/originui/select-with-search.tsx
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/crawler-form/index.tsx
  web/src/pages/agent/hooks/use-watch-form-change.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8858 Perf: retryable mysql connection.
  api/db/db_models.py
  graphrag/general/extractor.py
Labels: ci, size:M

#8860 Docs: Updated tag set tips.
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:S

#8859 Feat: Add agent tool CrawlerForm #3221
  web/src/pages/agent/form/crawler-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/crawler-form/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8845 Adds new Voyage embedding models
  conf/llm_factories.json
Labels: 💞 feature, ci, size:S

#8862 Fix: graphknowledge Tree structure not found for treeKey: combo (#7819)
  web/src/pages/add-knowledge/components/knowledge-graph/util.ts
Labels: 🐞 bug, ci, size:XS

#8867 Perf: set timeout of some steps in KG.
  graphrag/general/index.py
  graphrag/utils.py
  rag/svr/task_executor.py
Labels: 🌈 python, ci, size:S

#8866 Feat: add Kimi model series support
  conf/llm_factories.json
Labels: 💞 feature, ci, size:S

#8865 Fix: fix typo in OpenAI error logging message
  rag/llm/chat_model.py
Labels: ci, size:XS

#8874 Feat: Add sql form #3221
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/tool-popover/use-update-tools.ts
  web/src/pages/agent/form/components/form-wrapper.tsx
  web/src/pages/agent/form/exesql-form/index.tsx
  web/src/pages/agent/form/exesql-form/use-submit-form.ts
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/crawler-form/index.tsx
  web/src/pages/agent/form/tool-form/exesql-form/index.tsx
  web/src/pages/agent/form/tool-form/use-values.ts
  web/src/pages/agent/hooks/use-add-node.ts
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8881 Perf: add limit to embedding druing KG.
  graphrag/utils.py
Labels: ci, size:S

#8887 Refa: Remove useless conver and fix a bug for DefaultRerank
  rag/llm/rerank_model.py
Labels: ci, ☯️ refactor, size:XS

#8888 Feat: Display the thinking process according to the start_to_think flag of the message #3221
  web/src/components/llm-select/next.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/chat/hooks.ts
Labels: 💞 feature, ci, size:M

#8886 fix s3 init config .
  rag/utils/s3_conn.py
Labels: 🐞 bug, ci, size:XS

#8877 fix: Fix the problem that the custom footer of modal component
  web/package.json
  web/src/components/originui/number-input.tsx
  web/src/components/ui/modal.tsx
Labels: 🐞 bug, ci, 🧰 typescript, size:L

#8891 Fix: Fixed the issue that the knowledge graph could not be displayed #8890
  web/package-lock.json
  web/src/pages/add-knowledge/components/knowledge-graph/util.ts
Labels: 🐞 bug, ci, size:XS

#8897 Perf: test llm before RAPTOR.
  api/utils/api_utils.py
  deepdoc/parser/figure_parser.py
  graphrag/general/index.py
  rag/svr/task_executor.py
Labels: enhancement, ci

#8911 Feat: Adjust the EmbedDialog style #3221
  web/src/components/highlight-markdown/index.tsx
  web/src/components/ui/dialog.tsx
  web/src/pages/agent/embed-dialog/index.tsx
  web/src/pages/agent/index.tsx
Labels: 💞 feature, ci, size:L

#8906 Fix: when parse markdown support extract image at local
  rag/app/naive.py
Labels: 🐞 bug, ci, size:S

#8918 Fix: Fixed the issue that the content of the Dropdown section cannot be seen when selecting the next operator #3221
  web/src/components/highlight-markdown/index.tsx
  web/src/components/llm-select/next.tsx
  web/src/components/llm-setting-items/next.tsx
  web/src/components/originui/select-with-search.tsx
  web/src/hooks/use-agent-request.ts
  web/src/interfaces/request/agent.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/canvas/node/iteration-node.tsx
  web/src/pages/agent/canvas/node/toolbar.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form-sheet/single-debug-drawer/index.tsx
  web/src/pages/agent/form-sheet/single-debug-sheet/index.tsx
  web/src/pages/agent/form/categorize-form/dynamic-categorize.tsx
  web/src/pages/agent/form/categorize-form/dynamic-example.tsx
  web/src/pages/agent/form/categorize-form/index.tsx
  web/src/pages/agent/index.tsx
  web/src/pages/next-chats/hooks/use-send-shared-message.ts
  web/src/pages/next-chats/share/index.less
  web/src/pages/next-chats/share/index.tsx
  web/src/pages/next-chats/share/large.tsx
  web/src/pages/next-chats/utils.ts
  web/src/services/flow-service.ts
  web/src/utils/api.ts
Labels: 🐞 bug, ci, size:XL

#8921 Add OpenSearch support to Helm chart
  helm/templates/elasticsearch-config.yaml
  helm/templates/env.yaml
  helm/templates/opensearch-config.yaml
  helm/templates/opensearch.yaml
  helm/values.yaml
Labels: 💞 feature, ci, size:L

#8922 Feat: Adjust the style of the agent canvas connection line #3221
  web/src/pages/agent/canvas/edge/index.less
  web/src/pages/agent/canvas/edge/index.tsx
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/agent-node.tsx
  web/src/pages/agent/canvas/node/begin-node.tsx
  web/src/pages/agent/canvas/node/categorize-node.tsx
  web/src/pages/agent/canvas/node/index.tsx
  web/src/pages/agent/canvas/node/iteration-node.tsx
  web/src/pages/agent/canvas/node/logic-node.tsx
  web/src/pages/agent/canvas/node/message-node.tsx
  web/src/pages/agent/canvas/node/node-wrapper.tsx
  web/src/pages/agent/canvas/node/note-node/index.tsx
  web/src/pages/agent/canvas/node/retrieval-node.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/canvas/node/tool-node.tsx
  web/src/pages/agent/debug-content/index.tsx
  web/src/pages/agent/form-sheet/single-debug-sheet/index.tsx
Labels: ci, size:L

#8927 Docs: Updated knowledge graph-specific APIs
  docs/quickstart.mdx
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:S

#8936 Refactor improve codes for ranker
  rag/llm/rerank_model.py
Labels: ci, ☯️ refactor, size:S

#8923 Fix：Add a component of calendar
  web/package.json
  web/src/components/originui/calendar/index.less
  web/src/components/originui/calendar/index.tsx
  web/src/components/ui/modal.tsx
Labels: 🐞 bug, size:L

#8942 Feat: Display agent history versions #3221
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/canvas/index.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/index.tsx
  web/src/pages/agent/version-dialog/index.tsx
  web/tailwind.css
Labels: 💞 feature, ci, size:L

#8946 Fix: support cross language for API.
  api/apps/sdk/doc.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  graphrag/general/extractor.py
  graphrag/general/graph_extractor.py
  graphrag/light/graph_extractor.py
  sdk/python/ragflow_sdk/ragflow.py
Labels: 🐞 bug, ci, size:S

#8952 Fix: Generate avatar; Add knowledge graph; Modify the style of the MultiSelect component
  web/src/components/ragflow-avatar.tsx
  web/src/components/ui/multi-select.tsx
  web/src/hooks/use-knowledge-request.ts
  web/src/pages/dataset/knowledge-graph/constant.ts
  web/src/pages/dataset/knowledge-graph/force-graph.tsx
  web/src/pages/dataset/knowledge-graph/index.less
  web/src/pages/dataset/knowledge-graph/index.tsx
  web/src/pages/dataset/knowledge-graph/use-delete-graph.ts
  web/src/pages/dataset/knowledge-graph/util.ts
  web/src/pages/dataset/setting/tag-item.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/routes.ts
Labels: 🐞 bug, ci, size:XL

#8855 Feat: Add model editing functionality with improved UI labels
  api/apps/llm_app.py
  web/src/hooks/llm-hooks.tsx
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
  web/src/pages/user-setting/setting-model/hooks.ts
  web/src/pages/user-setting/setting-model/index.tsx
  web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:L

#8963 Fix:Improve float operation when rerank
  rag/llm/rerank_model.py
Labels: 🐞 bug, ci, size:XS

#8964 Fix: Fixed the issue that the key parameter duplication check of the begin operator was incorrect #3221
  web/src/pages/agent/form/begin-form/use-edit-query.ts
Labels: 🐞 bug, ci, size:XS

#8968 Feat: Add the option to use the knowledge graph to the retrieval form #3221
  web/src/components/cross-language-form-field.tsx
  web/src/components/cross-language-item-ui.tsx
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
  web/src/pages/dataset/testing/testing-form.tsx
Labels: 💞 feature, ci, size:L

#8973 Fix: correct cancel logic error
  api/apps/document_app.py
Labels: 🐞 bug, ci, ☯️ refactor, size:S

#8979 Refa: improve usability of Node.js/JavaScript code executor
  sandbox/README.md
  sandbox/executor_manager/api/handlers.py
  sandbox/executor_manager/api/routes.py
  sandbox/executor_manager/core/container.py
  sandbox/executor_manager/services/execution.py
Labels: ci, ☯️ refactor, size:M

#8778 Fix: Refactor parser config handling and add GraphRAG defaults
  api/utils/api_utils.py
  api/utils/validation_utils.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
Labels: 🐞 bug, 🌈 python, ci, size:L

#8981 Refa: remove temperature since some LLMs fail to support.
  graphrag/entity_resolution.py
  graphrag/general/community_reports_extractor.py
  graphrag/general/graph_extractor.py
  graphrag/general/mind_map_extractor.py
  graphrag/search.py
  rag/raptor.py
  rag/svr/task_executor.py
Labels: ci, ☯️ refactor, size:S

#8976 use quote_plus to escape password in opendal's mysql url
  rag/utils/opendal_conn.py
Labels: ci, size:XS

#8970 Fix: Adds newest Gemini models to fit google's standard API rate limits
  conf/llm_factories.json
Labels: ci, size:S

#8996 Fix: Increase timeouts for document parsing and model checks
  api/utils/api_utils.py
  test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py
  test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py
Labels: 🐞 bug, ci, size:S

#8992 Fix: Fixed the issue where the error prompt box on the Agent page would be covered #3221
  web/src/constants/agent.ts
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/services/agent-service.ts
  web/src/utils/api.ts
  web/src/utils/next-request.ts
  web/src/utils/register-server.ts
Labels: 🐞 bug, ci, size:L

#8997 Feat: OpenAI-compatible-API supports references
  api/apps/sdk/session.py
  docs/references/python_api_reference.md
Labels: 💞 feature, ci, size:L

#9012 Fix OpenSearch liveness probe
  helm/templates/opensearch.yaml
Labels: 🐞 bug, ci, size:S

#9015 Trival.
  graphrag/general/extractor.py
Labels: 🐞 bug, ci, size:XS

#9016 Ensure Redis volumeClaimTemplate labels are deterministic
  helm/templates/redis.yaml
Labels: 🐞 bug, ci, size:XS

#9014 fix: obfuscate additional server secrets values
  api/utils/__init__.py
Labels: ci, size:S

#9020 Feat: Modify the background color of the agent canvas #3221
  web/src/components/collapse.tsx
  web/src/components/cross-language-form-field.tsx
  web/src/components/page-header.tsx
  web/src/components/ui/sheet.tsx
  web/src/pages/agent/canvas/node/node-wrapper.tsx
  web/src/pages/agent/canvas/node/note-node/index.tsx
  web/src/pages/agent/canvas/node/note-node/use-watch-change.ts
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/components/background.tsx
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agents/index.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, size:L

#9022 Feat: Allows users to delete a condition of a conditional operator #3221
  web/src/components/originui/select-with-search.tsx
  web/src/components/ui/multi-select.tsx
  web/src/pages/agent/canvas/node/switch-node.tsx
  web/src/pages/agent/canvas/node/use-build-switch-handle-positions.ts
  web/src/pages/agent/form-sheet/form-config-map.tsx
  web/src/pages/agent/form/string-transform-form/index.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agents/agent-card.tsx
Labels: 💞 feature, ci, size:M

#9036 Feat: Downstream operators can get the variables defined by the user input operator #3221
  web/package-lock.json
  web/src/components/message-input/next.tsx
  web/src/hooks/use-agent-request.ts
  web/src/locales/pt-br.ts
  web/src/pages/agent/canvas/node/index.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/user-fill-up-form/index.tsx
  web/src/pages/agent/form/user-fill-up-form/use-watch-change.ts
Labels: 💞 feature, ci, size:M

#9032 Bug fix: OpenSearch chunk update some api error
  rag/utils/opensearch_conn.py
Labels: 🐞 bug, ci, size:XS

#9038 Feature: Support set chats kbs to empty
  api/apps/sdk/chat.py
Labels: 🌈 python, ci, size:XS

#9042 Refactor parser code
  deepdoc/parser/docx_parser.py
  deepdoc/parser/excel_parser.py
  deepdoc/parser/html_parser.py
Labels: ci, ☯️ refactor, size:S

#9040 Fix: Add parsing animations to the agent log and optimize some page styles
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/begin-form/query-table.tsx
  web/src/pages/agent/log-sheet/index.tsx
  web/src/pages/agents/agent-templates.tsx
Labels: 🐞 bug, ci, size:M

#9039 get keep alive from env
  rag/llm/cv_model.py
  rag/llm/embedding_model.py
Labels: ci, ☯️ refactor, size:S

#9037 Refa: validation utils to use Pydantic v2 style models
  api/utils/validation_utils.py
  test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_list_datasets.py
  test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
Labels: ci, ☯️ refactor, size:L

#9043 Refa: suppress DB migration error logs
  api/db/db_models.py
Labels: ci, ☯️ refactor, size:XS

#8962 Fix:in the knowledge base operation file will result in an error
  api/db/services/document_service.py
Labels: 🐞 bug, ci, size:M

#9059 adding platform: linux/amd64 to the mac build
  docker/docker-compose-macos.yml
Labels: 🐞 bug, ci, size:XS

#9018 Fix:When deleting a knowledge base that is currently performing a parsing task, the parsing queue will not be deleted!
  api/apps/sdk/dataset.py
  api/db/services/document_service.py
Labels: 🐞 bug, ci, size:XS

#9077 Feat: The operator is displayed only when the number of conditions is greater than 1 #3221
  web/src/pages/agent/form/retrieval-form/next.tsx
  web/src/pages/agent/form/switch-form/index.tsx
  web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
Labels: 💞 feature, ci, size:L

#9044 Added infinity rank_feature support
  api/apps/kb_app.py
  conf/infinity_mapping.json
  docker/docker-compose-base.yml
  docker/infinity_conf.toml
  helm/values.yaml
  rag/nlp/query.py
  rag/nlp/search.py
  rag/utils/infinity_conn.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_list_chunks.py
  test/testcases/test_web_api/test_chunk_app/test_list_chunks.py
Labels: wip, ci, ♾️infinity, size:L

#9081 Feat: Render the uploaded agent message file #3221
  web/src/components/next-message-item/index.tsx
  web/src/components/next-message-item/uploaded-message-files.tsx
  web/src/interfaces/database/chat.ts
  web/src/pages/agent/chat/box.tsx
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/next-chats/share/index.tsx
Labels: 💞 feature, ci, size:L

#9086 Feat: Add Google operator #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/code-form/index.tsx
  web/src/pages/agent/form/components/api-key-field.tsx
  web/src/pages/agent/form/google-form/index.tsx
  web/src/pages/agent/form/tavily-extract-form/index.tsx
  web/src/pages/agent/form/tavily-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/tavily-form/index.tsx
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: 💞 feature, ci, size:L

#9088 Feat: Add Yahoo Finance Operator #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/yahoo-finance-form/index.tsx
  web/src/pages/agent/form/yahoo-finance-form/index.tsx
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: 💞 feature, ci, size:L

#9102 Feat: Add Arxiv GoogleScholar operator #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/canvas/node/tool-node.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/agent-tools.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/arxiv-form/index.tsx
  web/src/pages/agent/form/duckduckgo-form/index.tsx
  web/src/pages/agent/form/email-form/index.tsx
  web/src/pages/agent/form/google-form/index.tsx
  web/src/pages/agent/form/google-scholar-form/index.tsx
  web/src/pages/agent/form/tool-form/arxiv-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/google-form/index.tsx
  web/src/pages/agent/form/tool-form/google-scholar-form/index.tsx
  web/src/pages/agent/form/wikipedia-form/index.tsx
  web/src/pages/agent/form/yahoo-finance-form/index.tsx
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: 💞 feature, ci, size:XL

#9083 Update embedding_model.py
  rag/llm/embedding_model.py
Labels: ci, size:XS

#9087 Feat: parsing supports jsonl or ldjson format
  api/utils/file_utils.py
  deepdoc/parser/json_parser.py
  rag/app/naive.py
Labels: 💞 feature, ci, size:M

#9073 docs: Complete tool calling bash script in MCP client example
  docs/develop/mcp/mcp_client_example.md
Labels: 📖 documentation, size:XS

#9106 Fix: fix error 429 api rate limit when building knowledge graph for all chat model and Mistral embedding model
  rag/llm/chat_model.py
  rag/llm/embedding_model.py
Labels: 🐞 bug, ci, size:M

#9112 Feat: Add invoke and github operators #3221
  web/src/locales/en.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/index.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/github-form/index.tsx
  web/src/pages/agent/form/invoke-form/dynamic-variables.tsx
  web/src/pages/agent/form/invoke-form/index.tsx
  web/src/pages/agent/form/invoke-form/schema.ts
  web/src/pages/agent/form/invoke-form/use-edit-variable.ts
  web/src/pages/agent/form/invoke-form/variable-dialog.tsx
  web/src/pages/agent/form/invoke-form/variable-table.tsx
  web/src/pages/agent/form/pubmed-form/index.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/github-form/index.tsx
  web/src/pages/agent/form/tool-form/pubmed-form/index.tsx
  web/src/pages/agent/form/yahoo-finance-form/index.tsx
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: 💞 feature, ci, size:XXL

#9097 Fix : API /document/thumbnails using wrong method to get ''doc_ids'
  api/apps/document_app.py
Labels: 🐞 bug, ci, size:XS

#9116 Feat: Add wencai operator #3221
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx
  web/src/pages/agent/form/tool-form/constant.tsx
  web/src/pages/agent/form/tool-form/wencai-form/index.tsx
  web/src/pages/agent/form/wencai-form/index.tsx
  web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Labels: ci, size:L

#9115 Refa: Update base64 test image with new sample data
  api/utils/base64_image.py
Labels: ci, ☯️ refactor, size:XS

#9118 Feat: Translate operator names and allow mailboxes to reference operator names #3221
  web/src/locales/en.ts
  web/src/locales/zh.ts
  web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form-sheet/index.less
  web/src/pages/agent/form-sheet/next.tsx
  web/src/pages/agent/form/components/prompt-editor/index.tsx
  web/src/pages/agent/form/email-form/index.tsx
  web/src/pages/agent/form/invoke-form/index.tsx
Labels: 💞 feature, ci, size:L

#9119 Feat: Add log-detail page,Improve the style of chat boxes
  web/src/components/next-message-item/index.tsx
  web/src/components/originui/time-range-picker.tsx
  web/src/hooks/use-send-message.ts
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/hooks/use-cache-chat-log.ts
  web/src/pages/agent/log-sheet/toolTimelineItem.tsx
  web/src/pages/agents/agent-log-detail-modal.tsx
  web/src/pages/agents/agent-log-page.tsx
  web/src/pages/next-chats/share/index.tsx
Labels: 🐞 bug, 💞 feature, ci, size:L

#9124 Feat: Make the agent dialog window exposed to the outside world fill in the begin form #3221
  web/src/components/llm-select/llm-label.tsx
  web/src/components/message-input/next.tsx
  web/src/hooks/use-agent-request.ts
  web/src/pages/agent/chat/use-send-agent-message.ts
  web/src/pages/agent/constant.tsx
  web/src/pages/agent/form/exesql-form/index.tsx
  web/src/pages/agent/index.tsx
  web/src/pages/next-chats/hooks/use-send-shared-message.ts
  web/src/pages/next-chats/share/index.tsx
  web/src/pages/next-chats/share/parameter-dialog.tsx
  web/src/services/agent-service.ts
  web/src/utils/api.ts
Labels: 💞 feature, ci, size:L

#9131 Rafe: Update LLMService type hints
  api/db/services/llm_service.py
Labels: ci, ☯️ refactor, size:XS

#9125 add Kimi-K2-Instruct from Tongyi-Qianwen API
  conf/llm_factories.json
Labels: 💞 feature, ci, size:XS
