Repository infiniflow/ragflow, pull requests merged in 2025-04, with the labels that each got.

#6699 fix: correct [AttributeError: 'set' object has no attribute 'nodes' T…
  graphrag/entity_resolution.py
  graphrag/general/extractor.py
Labels: 🐞 bug, ci, size:XS

#6701 Fix: `Email` error.
  agent/component/email.py
Labels: 🐞 bug, ci, size:XS

#6702 Feat: add qwq-plus-latest
  conf/llm_factories.json
Labels: 💞 feature, ci, size:XS

#6708 Feat: Allows users to search for models in the model selection drop-down box #3221
  web/src/components/operate-dropdown/index.tsx
  web/src/interfaces/database/knowledge.ts
  web/src/interfaces/database/llm.ts
  web/src/pages/user-setting/setting-model/system-model-setting-modal/index.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#6705 Hotfix ece5903
  graphrag/general/extractor.py
Labels: 🐞 bug, ci, size:XS, lgtm

#6109 Fix infinite recursion in RagTokenizer when processing repetitive characters
  rag/nlp/rag_tokenizer.py
Labels: 🌈 python, ci, ☯️ refactor, size:M

#6723 Feat: Interrupt streaming #6515
  web/src/components/message-input/index.tsx
  web/src/hooks/logic-hooks.ts
  web/src/pages/chat/chat-container/index.tsx
  web/src/pages/chat/hooks.ts
  web/src/pages/chat/share/large.tsx
  web/src/pages/chat/shared-hooks.ts
  web/src/pages/flow/chat/box.tsx
  web/src/pages/flow/chat/hooks.ts
  web/src/pages/search/hooks.ts
  web/src/pages/search/index.less
  web/src/pages/search/index.tsx
Labels: size:L

#6730 Miscellaneous doc updates and refactored team management doc.
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/dataset/set_page_rank.md
  docs/guides/manage_files.md
  docs/guides/manage_team_members.md
  docs/guides/run_health_check.md
  docs/guides/team/_category_.json
  docs/guides/team/join_or_leave_team.md
  docs/guides/team/manage_team_members.md
  docs/guides/upgrade_ragflow.mdx
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:L, lgtm

#6729 Feat: Add a notification logic to the team member invite feature #6610
  web/src/layouts/components/right-toolbar/index.tsx
Labels: 💞 feature, 🧰 typescript, size:S

#6724 Test: Skip test case for PR 6443
  sdk/python/test/conftest.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
Labels: ci, size:XS, 🧪 test

#6748 Feat: Support deleting knowledge graph #6747
  web/src/components/chunk-method-modal/index.tsx
  web/src/components/parse-configuration/graph-rag-items.tsx
  web/src/hooks/knowledge-hooks.ts
  web/src/pages/add-knowledge/components/knowledge-graph/index.tsx
  web/src/pages/add-knowledge/components/knowledge-graph/use-delete-graph.ts
  web/src/services/knowledge-service.ts
Labels: 💞 feature, 🧰 typescript, size:L

#6755 Fix: Using the Enter key does not send a complete message #6754
  web/src/components/message-input/index.tsx
  web/src/pages/chat/markdown-content/index.tsx
  web/src/pages/chat/utils.ts
Labels: size:M

#6756 Fix: The file upload prompt indicates "No authorization." #6516
  web/src/hooks/document-hooks.ts
Labels: 🐞 bug, 🧰 typescript, size:S

#6753 Fix: Change the field name of the document ID from "documents" to "do…
  sdk/python/ragflow_sdk/ragflow.py
Labels: 🐞 bug, ci, size:XS

#6758 Fix: Issue with Markdown Code Blocks Breaking Frontend Layout #5789
  web/src/pages/chat/markdown-content/index.tsx
Labels: size:XS

#6750 Log llm response on exception
  graphrag/general/extractor.py
  graphrag/general/graph_extractor.py
  graphrag/general/index.py
  rag/llm/chat_model.py
  rag/utils/redis_conn.py
Labels: ci, ☯️ refactor, size:L

#6764 Docs(api): align default values in create chat assistant HTTP API dos with implementation
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:XS

#6763 Test: Added test cases for Create Chat Assistant HTTP API
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/conftest.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/conftest.py
Labels: ci, size:L, 🧪 test

#6643 Fix: Handle the case of deleting empty blocks. Update the relevant message
  api/apps/sdk/doc.py
  rag/utils/es_conn.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
Labels: 🐞 bug, ci, size:S, 🧪 test

#6766 Test: Update test cases for PR #6643
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
Labels: ci, size:XS, 🧪 test

#6775 Docs: Fix for issue #6713
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:XS

#6774 Feat: add gemini-2.5-pro-exp-03-25
  conf/llm_factories.json
Labels: 💞 feature, ci, size:XS

#6777 Fix set_graph on non-existing edge
  graphrag/general/index.py
  graphrag/utils.py
  rag/utils/redis_conn.py
Labels: 🐞 bug, ci, size:S

#6779 Refa: copywriting refinement.
  api/db/services/dialog_service.py
Labels: ci, ☯️ refactor, size:XS

#6783 Feat: Clarify the use of OpenAI-API-compatible #6782
  web/src/locales/config.ts
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/user-setting/setting-model/index.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#6800 Fix: update chunk, empty question issue.
  api/apps/sdk/doc.py
Labels: 🐞 bug, ci, size:XS

#6799 Feat: Load the dialog page, prohibit calling the dialog/get interface #6798
  web/src/hooks/chat-hooks.ts
  web/src/pages/chat/hooks.ts
Labels: 💞 feature, 🧰 typescript, size:M

#6802 Refa: trival.
  deepdoc/vision/table_structure_recognizer.py
Labels: ci, ☯️ refactor, size:XS

#6804 Test: Update test cases for #6800
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
Labels: ci, size:XS, 🧪 test

#6805 Miscellaneous editorial updates
  docs/configurations.md
  docs/faq.mdx
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/guides/chat/start_chat.md
  docs/guides/models/deploy_local_llm.mdx
  docs/guides/team/join_or_leave_team.md
  docs/guides/team/manage_team_members.md
  docs/references/http_api_reference.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, ci, size:M, lgtm

#6812 Fix: improve Dockerfile build for China
  Dockerfile
  download_deps.py
Labels: 🐞 bug, ci, size:M

#6841 Update broken discord link
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: size:S

#6836 Fix:When parsing documents with graph, an error occurred:[ERROR][Exception]: 'method'
  graphrag/general/index.py
Labels: 🐞 bug, ci, size:XS, lgtm

#6839 Fix: docx image exceptions.
  rag/app/naive.py
Labels: 🐞 bug, ci, size:XS

#6851 Fix: Error message is incorrect when updating chat name #6850
  api/apps/sdk/chat.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
Labels: 🐞 bug, ci, size:S, 🧪 test

#6861 fix: add exception handling for get_by_id method
  api/db/services/common_service.py
Labels: 🐞 bug, ci, size:XS

#6840 Feat: add primitive support for function calls
  api/apps/sdk/session.py
  api/db/services/dialog_service.py
  api/db/services/llm_service.py
  api/utils/api_utils.py
  rag/llm/chat_model.py
Labels: 💞 feature, ci, size:XL

#6879 Test: Added test cases for Delete Chat Assistants HTTP API
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
Labels: ci, size:L, 🧪 test

#6874 Fix: handle waiting tasks when upstream is switch/categorize/relevant and normal path fails
  agent/canvas.py
Labels: 🐞 bug, ci, size:XS

#6898 Feat: Install sonner library #3221
  web/package-lock.json
  web/package.json
  web/src/components/ui/sonner.tsx
  web/src/components/ui/toast.tsx
  web/src/layouts/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#6902 Test: Added test cases for Create Session With Chat Assistant HTTP API
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/conftest.py
  sdk/python/test/test_http_api/test_chat_assistant_management/conftest.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_documents.py
  sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
  sdk/python/test/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
Labels: ci, size:L, 🧪 test

#6888 Fix delete duplicate assistant
  api/apps/sdk/chat.py
  api/apps/sdk/session.py
Labels: 🐞 bug, ci, size:M

#6904 Added a guide on setting chat variables
  docs/faq.mdx
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/guides/chat/accelerate_question_answering.mdx
  docs/guides/chat/implement_deep_research.md
  docs/guides/chat/set_chat_variables.md
  docs/guides/chat/start_chat.md
  docs/guides/dataset/construct_knowledge_graph.md
  docs/guides/dataset/use_tag_sets.md
  docs/guides/manage_files.md
  docs/guides/team/join_or_leave_team.md
  docs/quickstart.mdx
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  docs/release_notes.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/es.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/chat/chat-configuration-modal/index.tsx
Labels: 📖 documentation, ci, size:L, lgtm

#6909 Fix: local variable referenced before assignment
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:XS

#6906 Fix: assistant deleteion issue.
  api/apps/sdk/chat.py
  deepdoc/vision/layout_recognizer.py
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
Labels: 🐞 bug, ci, size:M

#6929 Test: Update test cases for PR 6906
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
Labels: ci, size:S, 🧪 test

#6912 Fix: remove deprecated `permission` field
  api/apps/kb_app.py
Labels: 🐞 bug, ci, size:XS

#6918 Added similarity scores in reference chunks
  rag/prompts.py
Labels: 💞 feature, 🌈 python, ci, size:XS

#6935 Feat: Add translation text to the prompt word of the generate operator to distinguish it from the prompt word of the knowledge base #6934
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/agent/form/generate-form/index.tsx
  web/src/pages/flow/form/generate-form/index.tsx
Labels: 💞 feature, ci, 🧰 typescript, size:M

#6932 Fix: incorrect total chunks count in retrieval function after similarity filtering (#6741)
  rag/nlp/search.py
Labels: 🐞 bug, ci, size:XS

#6951 Fix: In the dark night theme, the message input box is not displayed correctly. #6950
  web/src/components/message-input/index.less
  web/src/components/message-input/index.tsx
  web/src/locales/en.ts
  web/src/pages/chat/chat-configuration-modal/index.tsx
Labels: 🧰 typescript, size:S

#6955 fix bug [ERROR][Exception]: 8 vs. 9
  rag/raptor.py
Labels: 🐞 bug, ci, size:XS

#6973 Fix: Delete unused pages
  web/src/pages/api/index.tsx
Labels: 🐞 bug, size:S

#6971 Test: Update test cases for PR 6906 ISSUE 6875
  sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
Labels: ci, size:XS, 🧪 test

#6968 Test: Added test cases for Update Session With Chat Assistant HTTP API
  sdk/python/test/test_http_api/test_session_management/conftest.py
  sdk/python/test/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
Labels: ci, size:L, 🧪 test

#6959 Fix: KB update_time changed whenever system relaunched
  api/db/init_data.py
  api/db/services/knowledgebase_service.py
Labels: 🐞 bug, ci, size:S

#6859 fix RAGFlowPdfParser AttributeError: 'PdfReader' object has no attribute 'close' err
  deepdoc/parser/pdf_parser.py
Labels: 🐞 bug, ci, size:M

#6977 docs: update Docker build commands to specify platform as linux/amd64
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, ci, size:M, lgtm

#6980 Make error messages during PPT processing clearer.
  rag/app/presentation.py
Labels: ci, size:S

#6993 Fix: Fix api page translation issue. #3221
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 🐞 bug, size:XS

#6992 Fix update_progress issue
  api/ragflow_server.py
Labels: 🐞 bug, ci, size:XS

#7001 Fix: The selected state of the TreeView node cannot be seen on Mac #7000
  web/src/components/ui/tree-view.tsx
Labels: 🐞 bug, 🧰 typescript, size:XS

#7002 Docs: readme updating.
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 📖 documentation, size:M

#7009 Feat: Remove the rotation state of the button that parses the document #7008
  web/src/hooks/document-hooks.ts
  web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
Labels: 💞 feature, 🧰 typescript, size:S

#7007 Refa: update llms
  conf/llm_factories.json
Labels: ci, ☯️ refactor, size:S

#7018 Fix Helm Ingress template
  helm/templates/ingress.yaml
Labels: 🐞 bug, size:XS

#7014 Fix: add fallback for bad citation output
  api/db/services/dialog_service.py
  rag/prompts.py
Labels: 🐞 bug, ci, size:M

#7022 Refa.
  api/db/services/dialog_service.py
  api/db/services/user_service.py
  rag/prompts.py
Labels: ci, ☯️ refactor, size:M

#7005 Fix: when remove document do not delete the file in storage if the source is not knowledge base
  api/apps/document_app.py
Labels: 🐞 bug, ci, size:XS

#7025 Test: Added test cases for Delete Sessions With Chat Assistant HTTP API
  sdk/python/test/test_http_api/common.py
  sdk/python/test/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
Labels: ci, size:L, 🧪 test

#7042 Docs: updates.
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
Labels: size:M

#7054 Docs: Change DELETE to POST in Related Questions curl example
  docs/references/http_api_reference.md
Labels: 📖 documentation, size:XS

#7047 Miscellaneous editorial updates.
  docs/guides/dataset/construct_knowledge_graph.md
  docs/guides/team/join_or_leave_team.md
  docs/references/python_api_reference.md
Labels: 📖 documentation, size:S

#7066 Fix: Files being parsed are not allowed to be deleted in batches #7065
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/add-knowledge/components/knowledge-file/document-toolbar.tsx
  web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
  web/src/pages/add-knowledge/components/knowledge-file/index.tsx
Labels: 🐞 bug, 🧰 typescript, size:S

#7057 Fix: pymysql.err.InterfaceError: (0, '') during long time streaming chat responses (#6548)
  api/db/services/llm_service.py
Labels: 🐞 bug, 🌈 python, ci, size:S

#7094 Fix: Error in sending placeholder words in Chinese and Chinese-Traditional
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 🐞 bug, size:XS

#7091 Update utils.py
  graphrag/utils.py
Labels: 🐞 bug, ci, size:XS

#7093 Fix: wrong “available” property when list chunk
  api/apps/sdk/doc.py
Labels: 🐞 bug, ci, size:XS

#7121 Feat: Retrieval test #3221
  web/src/components/rerank.tsx
  web/src/components/similarity-slider/index.tsx
  web/src/components/switch-fom-field.tsx
  web/src/components/use-knowledge-graph-item.tsx
  web/src/hooks/use-knowledge-request.ts
  web/src/interfaces/request/knowledge.ts
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/dataset/testing/testing-form.tsx
Labels: size:L

#7127 Fix: handle sometimes graph index will miss explanation
  graphrag/general/index.py
Labels: 🐞 bug, 🌈 python, ci, size:XS

#7116 fix bug chunking:expected string or bytes-like object
  rag/app/table.py
Labels: 🐞 bug, ci, size:XS

#7138 Feat: Rendering a search test list with real data #3221
  web/src/hooks/use-knowledge-request.ts
  web/src/interfaces/database/knowledge.ts
  web/src/pages/dataset/testing/index.tsx
  web/src/pages/dataset/testing/testing-form.tsx
Labels: 💞 feature, 🧰 typescript, size:M

#7106 fix(nursery): Fix Closure Trap Issues in Trio Concurrent Tasks
  graphrag/entity_resolution.py
  graphrag/general/community_reports_extractor.py
  graphrag/general/extractor.py
  graphrag/general/mind_map_extractor.py
  graphrag/utils.py
  rag/raptor.py
  rag/svr/task_executor.py
Labels: 🐞 bug, 🌈 python, ci, size:M

#7117 Fix: cite disfunction for G component.
  agent/component/base.py
  agent/component/generate.py
  agent/component/retrieval.py
Labels: 🐞 bug, ci, size:M

#7073 feat: Recover pending tasks while pod restart.
  rag/svr/task_executor.py
  rag/utils/redis_conn.py
Labels: 💞 feature, ci, size:M

#7141 Docs: MCP server
  docs/guides/mcp.md
Labels: 📖 documentation, size:L

#7084 Feat: mcp server
  Dockerfile
  docker/docker-compose.yml
  docker/entrypoint.sh
  mcp/client/client.py
  mcp/server/server.py
  pyproject.toml
  uv.lock
Labels: 💞 feature, 🌈 python, ci, size:L

#7152 Fix: don't modify S3 file name when not using prefix_path
  rag/utils/s3_conn.py
Labels: 🐞 bug, ci, size:XS

#7163 Docs: add mcp self-host mode
  docs/develop/mcp.md
Labels: 📖 documentation, size:M

#7157 Feat: add mcp self-host mode
  docker/docker-compose.yml
  docker/entrypoint.sh
  mcp/client/client.py
  mcp/server/server.py
Labels: 💞 feature, ci, size:M

#7162 Feat: Rename a dataset #3221
  web/src/components/ui/dropdown-menu.tsx
  web/src/hooks/knowledge-hooks.ts
  web/src/pages/datasets/dataset-creating-dialog.tsx
  web/src/pages/datasets/dataset-dropdown.tsx
  web/src/pages/datasets/hooks.ts
  web/src/pages/datasets/index.tsx
  web/src/pages/datasets/use-rename-dataset.ts
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, 🧰 typescript, size:L

#6703 Refa: Optimize pptx shape extraction to reduce content loss
  deepdoc/parser/ppt_parser.py
Labels: ci, ☯️ refactor, size:M

#7186 Fix: KG search issue.
  graphrag/search.py
Labels: 🐞 bug, ci, size:XS

#7187 refactor: Update Redis configuration to use StatefulSet instead of deployment with pvc
  helm/templates/redis.yaml
Labels: ci, ☯️ refactor, size:L

#7196 Feat: Move langfuse configuration to api page #6155
  web/src/components/api-service/chat-overview-modal/api-content.tsx
  web/src/components/api-service/chat-overview-modal/markdown-toc.tsx
  web/src/pages/user-setting/setting-model/index.tsx
Labels: size:XS

#7197 Put the knowledge base list related hooks into use-knowledge-request.ts #3221
  web/src/hooks/knowledge-hooks.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/pages/datasets/dataset-dropdown.tsx
  web/src/pages/datasets/datasets-filter-popover.tsx
  web/src/pages/datasets/hooks.ts
  web/src/pages/datasets/index.tsx
  web/src/pages/datasets/use-rename-dataset.ts
Labels: size:L

#7174 Fix: fix retrieval tesing wrong pagination
  rag/nlp/search.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
Labels: 🐞 bug, ci, size:S

#7199 Fix: Knowledge Graph Extraction Conflict Between Dataset-Level and File-Specific Configurations #7198
  web/src/components/chunk-method-modal/index.tsx
  web/src/interfaces/database/knowledge.ts
Labels: 🐞 bug, 🧰 typescript, size:M

#7201 Feat: Even if the knowledge base has slices, the chunk method can be changed #7115
  web/src/pages/add-knowledge/components/knowledge-setting/configuration/common-item.tsx
Labels: size:XS

#7204 Feat: Show the owner of this knowledge base on the list card. #3221
  web/src/pages/datasets/index.tsx
  web/src/pages/datasets/use-display-owner.ts
Labels: 💞 feature, 🧰 typescript, size:L

#7205 [BREAKING CHANGE] GET to POST: enhance kb list capability
  api/apps/kb_app.py
  api/db/services/knowledgebase_service.py
  sdk/python/test/test_frontend_api/common.py
Labels: ci, ☯️ refactor, size:M

#7211 Added a RAPTOR guide
  docs/guides/dataset/construct_knowledge_graph.md
  docs/guides/dataset/enable_raptor.md
Labels: 📖 documentation, size:M, lgtm

#7209 Feat: Upload document #3221
  web/src/components/confirm-delete-dialog.tsx
  web/src/components/file-upload-dialog/index.tsx
  web/src/components/list-filter-bar.tsx
  web/src/hooks/use-document-request.ts
  web/src/hooks/use-file-request.ts
  web/src/pages/dataset/dataset/hooks.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-upload-document.ts
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/datasets/dataset-dropdown.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/files/hooks.ts
  web/src/pages/files/index.tsx
  web/src/pages/files/use-upload-file.ts
  web/src/pages/home/datasets.tsx
Labels: 💞 feature, ci, size:XL

#7185 v0.18.0 release notes
  docs/guides/dataset/enable_raptor.md
  docs/release_notes.md
Labels: 📖 documentation, size:S, lgtm

#7221 Updated v0.18.0 release notes
  docs/develop/mcp.md
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/release_notes.md
Labels: 📖 documentation, size:S

#7223 Docs: update for v0.18.0
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
  docker/.env
  docker/README.md
  docs/configurations.md
  docs/develop/build_docker_image.mdx
  docs/develop/mcp.md
  docs/faq.mdx
  docs/guides/chat/start_chat.md
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/manage_files.md
  docs/guides/upgrade_ragflow.mdx
  docs/quickstart.mdx
  helm/values.yaml
  pyproject.toml
  sdk/python/pyproject.toml
  sdk/python/uv.lock
  uv.lock
Labels: 📖 documentation, ci, size:L

#7220 Refa: knowledge_graph chunk method is deprecated
  api/apps/sdk/dataset.py
  api/settings.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
  sdk/python/test/test_sdk_api/t_dataset.py
Labels: 📖 documentation, ci, ☯️ refactor, size:M

#7228 Feat: Create a folder #3221
  web/src/components/list-filter-bar.tsx
  web/src/components/ui/single-tree-select.tsx
  web/src/hooks/logic-hooks/navigate-hooks.ts
  web/src/hooks/use-file-request.ts
  web/src/pages/agents/index.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/create-folder-dialog/create-folder-form.tsx
  web/src/pages/files/create-folder-dialog/index.tsx
  web/src/pages/files/file-breadcrumb.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/hooks.ts
  web/src/pages/files/index.tsx
  web/src/pages/files/move-dialog.tsx
  web/src/pages/files/use-create-folder.ts
  web/src/pages/files/use-move-file.ts
  web/src/pages/files/use-navigate-to-folder.ts
  web/src/pages/next-chats/index.tsx
  web/src/pages/next-searches/index.tsx
Labels: 💞 feature, size:XL

#7234 Feat: Deleting files in batches. #3221
  web/src/components/bulk-operate-bar.tsx
  web/src/components/confirm-delete-dialog.tsx
  web/src/hooks/use-file-request.ts
  web/src/interfaces/database/file-manager.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-bulk-operate-dataset.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/hooks.ts
  web/src/pages/files/index.tsx
  web/src/pages/files/use-bulk-operate-file.tsx
  web/src/pages/files/use-delete-file.ts
  web/src/pages/files/use-move-file.ts
Labels: 💞 feature, 🧰 typescript, size:XL

#6744 Fix: improve retrieval API
  api/apps/api_app.py
Labels: 🐞 bug, 💞 feature, ci, size:XS

#7251 Fix: mcp server start
  docker/entrypoint.sh
Labels: 🐞 bug, ci, size:XS

#7242 chore: adds pre-commit
  .pre-commit-config.yaml
  README.md
  README_id.md
  README_ja.md
  README_ko.md
  README_pt_br.md
  README_tzh.md
  README_zh.md
Labels: 💞 feature, size:M, lgtm

#7256 <think> tag is missing.
  agent/component/exesql.py
  agent/component/generate.py
  agent/component/keyword.py
  agentic_reasoning/deep_research.py
  api/db/services/dialog_service.py
  graphrag/general/extractor.py
  rag/prompts.py
  rag/raptor.py
Labels: 🐞 bug, ci, size:S

#7253 fix: task_executor bug fix
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7241 Feat: Display document parsing status #3221
  web/package-lock.json
  web/package.json
  web/src/components/confirm-delete-dialog.tsx
  web/src/components/ui/hover-card.tsx
  web/src/hooks/use-document-request.ts
  web/src/pages/dataset/dataset/constant.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/hooks.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/parsing-card.tsx
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/dataset/use-run-document.ts
  web/src/pages/dataset/dataset/utils.ts
Labels: 💞 feature, size:L

#7268 Feat: Delete and rename files in the knowledge base #3221
  web/src/components/rename-dialog/index.tsx
  web/src/components/rename-dialog/rename-form.tsx
  web/src/hooks/use-document-request.ts
  web/src/pages/dataset/dataset/dataset-action-cell.tsx
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/hooks.ts
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/dataset/use-rename-document.ts
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7140 Feat: Adds OpenSearch2.19.1 as the vector_database support
  api/settings.py
  conf/os_mapping.json
  conf/service_conf.yaml
  docker/.env
  docker/docker-compose-base.yml
  docker/service_conf.yaml.template
  pyproject.toml
  rag/settings.py
  rag/utils/opensearch_coon.py
  uv.lock
Labels: 💞 feature, 🌈 python, ci, size:XL

#7287 Feat: Replace the logo of novita
  web/src/assets/svg/llm/novita-ai.svg
Labels: size:XS

#7281 Fix: Qwen-vl-plus url error
  rag/llm/chat_model.py
Labels: 🐞 bug, ci, size:XS

#7293 Doc: Updated sharing behavior in the open-source editions.
  docker/.env
  docs/guides/team/join_or_leave_team.md
  docs/guides/team/manage_team_members.md
  docs/guides/team/share_agents.md
  docs/guides/team/share_knowledge_bases.md
  docs/guides/team/share_model.md
  docs/release_notes.md
Labels: 📖 documentation, size:M

#7302 Feat: Display the document configuration dialog with shadcn #3221
  web/src/components/auto-keywords-form-field.tsx
  web/src/components/chunk-method-dialog/index.tsx
  web/src/components/delimiter-form-field.tsx
  web/src/components/entity-types-form-field.tsx
  web/src/components/excel-to-html-form-field.tsx
  web/src/components/layout-recognize-form-field.tsx
  web/src/components/max-token-number-from-field.tsx
  web/src/components/parse-configuration/graph-rag-form-fields.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/components/slider-input-form-field.tsx
  web/src/components/ui/select.tsx
  web/src/hooks/use-document-request.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/hooks.ts
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/dataset/use-change-document-parser.ts
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
Labels: size:XXL

#7295 Fix pymysql interface error
  api/db/services/common_service.py
Labels: 🐞 bug, ci, size:XS

#7301 Fix: LLM generated tag issue.
  rag/prompts.py
Labels: 🐞 bug, ci, size:S

#7317 Feat: Save the configuration information of the knowledge base document #3221
  web/src/components/chunk-method-dialog/dynamic-page-range.tsx
  web/src/components/chunk-method-dialog/index.tsx
  web/src/components/chunk-method-dialog/use-default-parser-values.ts
  web/src/components/delimiter-form-field.tsx
  web/src/components/file-upload-dialog/index.tsx
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/dataset/use-change-document-parser.ts
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7124 Feat: Markdown add image
  rag/app/naive.py
  rag/nlp/__init__.py
  web/src/interfaces/database/knowledge.ts
  web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-card/index.tsx
Labels: 💞 feature, ci, size:L

#7323 Feat: Save document metadata #3221
  web/src/components/chunk-method-dialog/index.tsx
  web/src/hooks/use-document-request.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/parsing-status-cell.tsx
  web/src/pages/dataset/dataset/set-meta-dialog.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/dataset/use-save-meta.ts
  web/src/pages/dataset/sidebar/index.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7258 Fix: Creating Knowledge Base Support Enter Key
  web/src/pages/chat/chat-configuration-modal/index.tsx
  web/src/pages/flow/list/create-agent-modal.tsx
  web/src/pages/knowledge/knowledge-creating-modal/index.tsx
  web/src/pages/user-setting/setting-model/Tencent-modal/index.tsx
  web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
  web/src/pages/user-setting/setting-model/azure-openai-modal/index.tsx
  web/src/pages/user-setting/setting-model/google-modal/index.tsx
  web/src/pages/user-setting/setting-model/hunyuan-modal/index.tsx
  web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
  web/src/pages/user-setting/setting-model/spark-modal/index.tsx
  web/src/pages/user-setting/setting-model/yiyan-modal/index.tsx
Labels: 🐞 bug, 🧰 typescript, size:L

#7324 DOC: Miscellaneous UI and editorial updates
  api/apps/kb_app.py
  docs/faq.mdx
  docs/guides/agent/agent_component_reference/begin.mdx
  docs/guides/dataset/configure_knowledge_base.md
  docs/guides/dataset/construct_knowledge_graph.md
  docs/guides/dataset/enable_raptor.md
  docs/guides/dataset/run_retrieval_test.md
  docs/guides/dataset/set_page_rank.md
  docs/guides/dataset/use_tag_sets.md
  docs/quickstart.mdx
  docs/references/python_api_reference.md
  docs/release_notes.md
  web/src/locales/en.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
  web/src/pages/profile-setting/hooks.tsx
Labels: 📖 documentation, size:L

#7340 Feat: Filter document by running status and file type. #3221
  web/src/components/chunk-method-dialog/index.tsx
  web/src/components/list-filter-bar/filter-popover.tsx
  web/src/components/list-filter-bar/index.tsx
  web/src/components/list-filter-bar/interface.ts
  web/src/components/list-filter-bar/use-handle-filter-submit.ts
  web/src/components/parse-configuration/raptor-form-fields.tsx
  web/src/hooks/document-hooks.ts
  web/src/hooks/use-document-request.ts
  web/src/hooks/use-knowledge-request.ts
  web/src/interfaces/request/knowledge.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-select-filters.ts
  web/src/pages/datasets/index.tsx
  web/src/pages/datasets/use-select-owners.ts
  web/src/services/knowledge-service.ts
  web/src/utils/dataset-util.ts
Labels: 💞 feature, 🧰 typescript, size:L

#7343 Feat: Create empty document. #3221
  web/src/components/rename-dialog/index.tsx
  web/src/hooks/use-document-request.ts
  web/src/pages/dataset/dataset/dataset-action-cell.tsx
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/hooks.ts
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-create-empty-document.ts
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/tailwind.css
Labels: 💞 feature, 🧰 typescript, size:L

#7349 [BREAKING CHANGE] GET to POST: enhance document list capability
  api/apps/api_app.py
  api/apps/document_app.py
  api/db/__init__.py
  api/db/services/document_service.py
  api/db/services/knowledgebase_service.py
  sdk/python/test/test_frontend_api/common.py
Labels: 🌈 python, ci, ☯️ refactor, size:M

#7348 Updated RAPTOR-specific UI
  docs/guides/dataset/enable_raptor.md
  web/src/locales/de.ts
  web/src/locales/en.ts
  web/src/locales/id.ts
  web/src/locales/ja.ts
  web/src/locales/pt-br.ts
  web/src/locales/vi.ts
  web/src/locales/zh-traditional.ts
  web/src/locales/zh.ts
Labels: 📖 documentation, size:M

#7352 Feat: Batch operations on documents in a dataset #3221
  web/src/app.tsx
  web/src/components/list-filter-bar/filter-popover.tsx
  web/src/hooks/logic-hooks/use-row-selection.ts
  web/src/layouts/index.tsx
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-bulk-operate-dataset.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/datasets/datasets-filter-popover.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/index.tsx
  web/src/pages/files/use-bulk-operate-file.tsx
Labels: 💞 feature, size:L

#7335 Update Groq AI Model Config
  conf/llm_factories.json
Labels: 🐞 bug, ci, size:XS

#7331 Fix: tenant_id spelling error.
  api/utils/api_utils.py
Labels: 🐞 bug, ci, size:XS

#7329 Fix mcp server startup failure
  .gitattributes
  docker/docker-compose.yml
  docker/entrypoint.sh
  docs/develop/mcp.md
Labels: 🐞 bug, 📖 documentation, ci, size:S

#7355 Feat: Preview the file #3221
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/knowledge-cell.tsx
  web/src/pages/files/util.ts
Labels: 💞 feature, 🧰 typescript, size:L

#7356 perf: Optimize GraphRAG’s LOOP_PROMPT
  graphrag/general/graph_extractor.py
  graphrag/general/graph_prompt.py
Labels: ci, size:XS

#7360 feat: replace models of novita
  conf/llm_factories.json
  docs/references/supported_models.mdx
  docs/release_notes.md
  rag/llm/__init__.py
  web/src/constants/llm.ts
Labels: 📖 documentation, ci, 🧰 typescript, size:L

#7365 Fix: Add title_tks for Pictures
  rag/app/picture.py
Labels: 🐞 bug, ci, size:XS

#7377 Feat: Add AsyncTreeSelect component #3221
  web/src/components/list-filter-bar/filter-popover.tsx
  web/src/components/list-filter-bar/index.tsx
  web/src/components/ui/async-tree-select.tsx
  web/src/components/ui/single-tree-select.tsx
  web/src/pages/files/index.tsx
  web/src/pages/files/move-dialog.tsx
Labels: 💞 feature, 🧰 typescript, size:L

#7354 Fix:Update chat assistant with an empty dataset
  api/apps/sdk/chat.py
Labels: 🐞 bug, ci, size:M

#7382 Knowledge graph no longer exists as a chunking method
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
Labels: 📖 documentation, size:S

#7379 Feat: Add support for OAuth2 and OpenID Connect (OIDC) authentication
  api/apps/auth/README.md
  api/apps/auth/__init__.py
  api/apps/auth/oauth.py
  api/apps/auth/oidc.py
  api/apps/user_app.py
  api/settings.py
  conf/service_conf.yaml
  docker/service_conf.yaml.template
  docs/configurations.md
Labels: 📖 documentation, 💞 feature, ci, size:L

#7381 Refa: similarity calculations.
  rag/nlp/query.py
  sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
Labels: ci, ☯️ refactor, size:XS

#7385 Feat: Bind data to the agent module of the home page #3221
  web/src/components/list-filter-bar/index.tsx
  web/src/components/table-skeleton.tsx
  web/src/components/ui/async-tree-select.tsx
  web/src/components/ui/ragflow-pagination.tsx
  web/src/components/ui/tooltip.tsx
  web/src/hooks/logic-hooks/use-row-selection.ts
  web/src/hooks/use-agent-request.ts
  web/src/interfaces/database/flow.ts
  web/src/pages/dataset/dataset/dataset-table.tsx
  web/src/pages/dataset/dataset/index.tsx
  web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
  web/src/pages/dataset/sidebar/index.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/datasets/index.tsx
  web/src/pages/files/action-cell.tsx
  web/src/pages/files/files-table.tsx
  web/src/pages/files/index.tsx
  web/src/pages/files/link-to-dataset-dialog.tsx
  web/src/pages/files/use-bulk-operate-file.tsx
  web/src/pages/files/use-move-file.ts
  web/src/pages/home/agent-list.tsx
  web/src/pages/home/application-card.tsx
  web/src/pages/home/applications.tsx
  web/src/pages/home/datasets.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, ci, 🧰 typescript, size:L

#7375 fixed missing list input ref in query
  agent/component/keyword.py
Labels: 🐞 bug, ci, size:XS

#7405 Feat: Adjust the style of the home page #3221
  web/src/layouts/next-header.tsx
  web/src/pages/datasets/dataset-card.tsx
  web/src/pages/home/applications.tsx
  web/src/pages/home/banner.tsx
  web/src/pages/home/chat-list.tsx
  web/src/pages/home/datasets.tsx
  web/src/pages/home/index.tsx
  web/tailwind.config.js
  web/tailwind.css
Labels: 💞 feature, size:M

#7408 Fix: improve recover_pending_tasks timeout
  rag/svr/task_executor.py
Labels: 🐞 bug, ci, size:XS

#7393 Refa: http API create dataset and test cases
  .github/workflows/tests.yml
  api/apps/sdk/dataset.py
  api/utils/api_utils.py
  api/utils/validation_utils.py
  docs/references/http_api_reference.md
  docs/references/python_api_reference.md
  sdk/python/pyproject.toml
  sdk/python/ragflow_sdk/ragflow.py
  sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
  sdk/python/test/test_sdk_api/t_dataset.py
  sdk/python/uv.lock
Labels: 🐞 bug, 📖 documentation, wip, ci, ☯️ refactor, size:XXL, 🧪 test
